// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 8a429189ff65f2fa "Shareye Films", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' | 'Phone' | 'Variant 4' | 'Variant 5' // Variant
 * image1?: {src: string, srcSet?: string, alt?: string} // Image 1
 * image2?: {src: string, srcSet?: string, alt?: string} // Image 2
 * image3?: {src: string, srcSet?: string, alt?: string} // Image 3
 * title?: string // Title
 * location?: string // Location
 * link?: string // Link
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-ULIILFHK.js";
import { className, css, fonts } from "./chunks/chunk-6IVYILAF.js";
import { routes } from "./chunks/chunk-W2AWTVWO.js";

// virtual:album-image
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/bzJxod137ROqXKDXIBSW/t7hofFjN8IZjCZ5EwjF5/axr3X3wQ4.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	Image,
	Link,
	RichText,
	useActiveVariantCallback,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = [
	"whcuTJVDU",
	"NJfHDcu4W",
	"ae_P2MvE1",
	"At0u8XfN3",
	"I5Sm1NYr1",
];
var serializationHash = "framer-c8JDZ";
var variantClassNames = {
	ae_P2MvE1: "framer-v-umtju3",
	At0u8XfN3: "framer-v-1j0blrb",
	I5Sm1NYr1: "framer-v-tgaye6",
	NJfHDcu4W: "framer-v-1q0tk8i",
	whcuTJVDU: "framer-v-15qh5wp",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1,
		stiffness: 240,
		type: "spring",
	},
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Variant 1": "whcuTJVDU",
	"Variant 2": "NJfHDcu4W",
	"Variant 4": "At0u8XfN3",
	"Variant 5": "I5Sm1NYr1",
	Phone: "ae_P2MvE1",
};
var getProps = ({
	height,
	id,
	image1,
	image2,
	image3,
	link,
	location,
	title,
	width,
	...props
}) => {
	var _ref,
		_ref1,
		_ref2,
		_ref3,
		_humanReadableVariantMap_props_variant,
		_ref4,
		_ref5;
	return {
		...props,
		c38uhUV8w:
			(_ref =
				location !== null && location !== void 0
					? location
					: props.c38uhUV8w) !== null && _ref !== void 0
				? _ref
				: "Short Description",
		euUqu2bvv:
			(_ref1 = title !== null && title !== void 0 ? title : props.euUqu2bvv) !==
				null && _ref1 !== void 0
				? _ref1
				: "Album Title",
		hK6R_KXxq:
			(_ref2 =
				image3 !== null && image3 !== void 0 ? image3 : props.hK6R_KXxq) !==
				null && _ref2 !== void 0
				? _ref2
				: {
						src: "https://framerusercontent.com/images/JBQwp5PcY7eU5Y2iRSPkj9Q00.jpg?scale-down-to=2048",
						srcSet:
							"https://framerusercontent.com/images/JBQwp5PcY7eU5Y2iRSPkj9Q00.jpg?scale-down-to=1024 767w, https://framerusercontent.com/images/JBQwp5PcY7eU5Y2iRSPkj9Q00.jpg?scale-down-to=2048 1535w, https://framerusercontent.com/images/JBQwp5PcY7eU5Y2iRSPkj9Q00.jpg 2939w",
					},
		lyMxtJN0r:
			(_ref3 =
				image1 !== null && image1 !== void 0 ? image1 : props.lyMxtJN0r) !==
				null && _ref3 !== void 0
				? _ref3
				: {
						src: "https://framerusercontent.com/images/6vX7b4cpzAhbpoO1xAOWx3pweQg.jpg?scale-down-to=2048",
						srcSet:
							"https://framerusercontent.com/images/6vX7b4cpzAhbpoO1xAOWx3pweQg.jpg?scale-down-to=512 512w, https://framerusercontent.com/images/6vX7b4cpzAhbpoO1xAOWx3pweQg.jpg?scale-down-to=1024 1024w, https://framerusercontent.com/images/6vX7b4cpzAhbpoO1xAOWx3pweQg.jpg?scale-down-to=2048 2048w, https://framerusercontent.com/images/6vX7b4cpzAhbpoO1xAOWx3pweQg.jpg 3844w",
					},
		PlG8psyh0: link !== null && link !== void 0 ? link : props.PlG8psyh0,
		variant:
			(_ref4 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref4 !== void 0
				? _ref4
				: "whcuTJVDU",
		ZZB_u6RQP:
			(_ref5 =
				image2 !== null && image2 !== void 0 ? image2 : props.ZZB_u6RQP) !==
				null && _ref5 !== void 0
				? _ref5
				: {
						src: "https://framerusercontent.com/images/Fe0bBRUkdYPiitxPwjVp8ZZnog8.jpg?scale-down-to=2048",
						srcSet:
							"https://framerusercontent.com/images/Fe0bBRUkdYPiitxPwjVp8ZZnog8.jpg?scale-down-to=512 512w, https://framerusercontent.com/images/Fe0bBRUkdYPiitxPwjVp8ZZnog8.jpg?scale-down-to=1024 1024w, https://framerusercontent.com/images/Fe0bBRUkdYPiitxPwjVp8ZZnog8.jpg?scale-down-to=2048 2048w, https://framerusercontent.com/images/Fe0bBRUkdYPiitxPwjVp8ZZnog8.jpg?scale-down-to=4096 4096w, https://framerusercontent.com/images/Fe0bBRUkdYPiitxPwjVp8ZZnog8.jpg 6805w",
					},
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		lyMxtJN0r,
		ZZB_u6RQP,
		hK6R_KXxq,
		euUqu2bvv,
		c38uhUV8w,
		PlG8psyh0,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "whcuTJVDU",
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onMouseEnterb0hnrg = activeVariantCallback(async (...args) => {
		setVariant("NJfHDcu4W");
	});
	const onMouseLeave442sfr = activeVariantCallback(async (...args) => {
		setVariant("whcuTJVDU");
	});
	const onMouseEnter1hj3k53 = activeVariantCallback(async (...args) => {
		setVariant("I5Sm1NYr1");
	});
	const onMouseEnter1gn63su = activeVariantCallback(async (...args) => {
		setVariant("At0u8XfN3");
	});
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className, className2];
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Transition value={transition}>
				<Link href={PlG8psyh0}>
					<motion.a
						{...restProps}
						animate={variants}
						className={`${cx(serializationHash, ...sharedStyleClassNames, "framer-15qh5wp", className3, classNames)} framer-17w0byr`}
						data-border={true}
						data-framer-name={"Variant 1"}
						data-highlight={true}
						initial={variant}
						layoutDependency={layoutDependency}
						layoutId={"whcuTJVDU"}
						onHoverEnd={() =>
							setGestureState({
								isHovered: false,
							})
						}
						onHoverStart={() =>
							setGestureState({
								isHovered: true,
							})
						}
						onMouseEnter={onMouseEnterb0hnrg}
						onTap={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapCancel={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapStart={() =>
							setGestureState({
								isPressed: true,
							})
						}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-8c47652b-dea5-4767-a9f2-5d952dcce49a, rgba(255, 255, 255, 0.3))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							borderBottomLeftRadius: 42,
							borderBottomRightRadius: 42,
							borderTopLeftRadius: 42,
							borderTopRightRadius: 42,
							...style,
						}}
						variants={{
							ae_P2MvE1: {
								borderBottomLeftRadius: 20,
								borderBottomRightRadius: 20,
								borderTopLeftRadius: 20,
								borderTopRightRadius: 20,
							},
						}}
						{...addPropertyOverrides(
							{
								ae_P2MvE1: {
									"data-framer-name": "Phone",
									"data-highlight": void 0,
									onMouseEnter: void 0,
								},
								At0u8XfN3: {
									"data-framer-name": "Variant 4",
									onMouseLeave: onMouseLeave442sfr,
								},
								I5Sm1NYr1: {
									"data-framer-name": "Variant 5",
									onMouseLeave: onMouseLeave442sfr,
								},
								NJfHDcu4W: {
									"data-framer-name": "Variant 2",
									onMouseLeave: onMouseLeave442sfr,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-b31087"}
							data-framer-name={"Overlay"}
							layoutDependency={layoutDependency}
							layoutId={"vduTpKAp9"}
							style={{
								background:
									"linear-gradient(249deg, rgba(84, 84, 84, 0) 55.11597766684241%, rgba(0, 0, 0, 0.77) 100%)",
								opacity: 0,
							}}
							variants={{
								ae_P2MvE1: {
									opacity: 1,
								},
								At0u8XfN3: {
									opacity: 1,
								},
								I5Sm1NYr1: {
									opacity: 1,
								},
								NJfHDcu4W: {
									opacity: 1,
								},
							}}
						/>
						<motion.div
							className={"framer-1x52b2u"}
							layoutDependency={layoutDependency}
							layoutId={"X7x9faUZE"}
							style={{
								opacity: 0,
							}}
							variants={{
								ae_P2MvE1: {
									opacity: 1,
								},
								At0u8XfN3: {
									opacity: 1,
								},
								I5Sm1NYr1: {
									opacity: 1,
								},
								NJfHDcu4W: {
									opacity: 1,
								},
							}}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-vm3h56"}
								layoutDependency={layoutDependency}
								layoutId={"yKF3j6gHG"}
								style={{
									"--extracted-a0htzi":
										"var(--token-a3567fc0-2c6f-4fa8-ac8f-89ddd158e98d, rgb(255, 255, 255))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={euUqu2bvv}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h3
										className={"framer-styles-preset-ravud2"}
										data-styles-preset={"MjM7LH64L"}
										style={{
											"--framer-text-alignment": "left",
											"--framer-text-color":
												"var(--extracted-a0htzi, var(--token-a3567fc0-2c6f-4fa8-ac8f-89ddd158e98d, rgb(255, 255, 255)))",
										}}
									>
										{"Album Title"}
									</motion.h3>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1hsuuk1"}
								layoutDependency={layoutDependency}
								layoutId={"erCVQoSBg"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={c38uhUV8w}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-g6micz"}
										data-styles-preset={"iLvBdfOs8"}
									>
										{"Short Description"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						<motion.div
							className={"framer-nn5xgm"}
							data-framer-name={"Images"}
							layoutDependency={layoutDependency}
							layoutId={"DuCWFxbdn"}
							style={{
								backdropFilter: "blur(19px)",
								borderBottomLeftRadius: 40,
								borderBottomRightRadius: 40,
								borderTopLeftRadius: 40,
								borderTopRightRadius: 40,
								WebkitBackdropFilter: "blur(19px)",
							}}
							variants={{
								ae_P2MvE1: {
									borderBottomLeftRadius: 20,
									borderBottomRightRadius: 20,
									borderTopLeftRadius: 20,
									borderTopRightRadius: 20,
								},
							}}
						>
							<motion.div
								background={{
									alt: "",
									fit: "fill",
									intrinsicHeight: 3919,
									intrinsicWidth: 2939,
								}}
								className={"framer-1vqtcay"}
								data-framer-name={"3"}
								layoutDependency={layoutDependency}
								layoutId={"xBHePjQOG"}
								style={{
									borderBottomLeftRadius: 40,
									borderBottomRightRadius: 40,
									borderTopLeftRadius: 40,
									borderTopRightRadius: 40,
								}}
								variants={{
									ae_P2MvE1: {
										borderBottomLeftRadius: 20,
										borderBottomRightRadius: 20,
										borderTopLeftRadius: 20,
										borderTopRightRadius: 20,
									},
								}}
								{...addPropertyOverrides(
									{
										At0u8XfN3: {
											"data-highlight": true,
											onMouseEnter: onMouseEnter1hj3k53,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<Image
									background={{
										alt: "",
										fit: "fill",
										sizes: "1900px",
										...toResponsiveImage(hK6R_KXxq),
									}}
									className={"framer-h8gvni"}
									layoutDependency={layoutDependency}
									layoutId={"h6gYreio7"}
									style={{
										borderBottomLeftRadius: 40,
										borderBottomRightRadius: 40,
										borderTopLeftRadius: 40,
										borderTopRightRadius: 40,
									}}
									variants={{
										ae_P2MvE1: {
											borderBottomLeftRadius: 20,
											borderBottomRightRadius: 20,
											borderTopLeftRadius: 20,
											borderTopRightRadius: 20,
										},
									}}
								/>
							</motion.div>
							<motion.div
								background={{
									alt: "",
									fit: "fill",
									intrinsicHeight: 1944,
									intrinsicWidth: 2896,
								}}
								className={"framer-m4gi4f"}
								data-framer-name={"2"}
								layoutDependency={layoutDependency}
								layoutId={"mJn24fGK8"}
								style={{
									borderBottomLeftRadius: 40,
									borderBottomRightRadius: 40,
									borderTopLeftRadius: 40,
									borderTopRightRadius: 40,
									boxShadow: "30px 1px 42px 0px rgba(0,0,0,0.25)",
								}}
								variants={{
									ae_P2MvE1: {
										borderBottomLeftRadius: 20,
										borderBottomRightRadius: 20,
										borderTopLeftRadius: 20,
										borderTopRightRadius: 20,
									},
								}}
							>
								<Image
									background={{
										alt: "",
										fit: "fill",
										intrinsicHeight: 4537,
										intrinsicWidth: 6805,
										pixelHeight: 4537,
										pixelWidth: 6805,
										sizes: "1900px",
										...toResponsiveImage(ZZB_u6RQP),
									}}
									className={"framer-8vwkum"}
									layoutDependency={layoutDependency}
									layoutId={"WhCOyw0Uy"}
									style={{
										borderBottomLeftRadius: 40,
										borderBottomRightRadius: 40,
										borderTopLeftRadius: 40,
										borderTopRightRadius: 40,
									}}
									variants={{
										ae_P2MvE1: {
											borderBottomLeftRadius: 20,
											borderBottomRightRadius: 20,
											borderTopLeftRadius: 20,
											borderTopRightRadius: 20,
										},
									}}
									{...addPropertyOverrides(
										{
											I5Sm1NYr1: {
												"data-highlight": true,
												onMouseEnter: onMouseEnter1gn63su,
											},
											NJfHDcu4W: {
												"data-highlight": true,
												onMouseEnter: onMouseEnter1gn63su,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</motion.div>
							<motion.div
								background={{
									alt: "",
									fit: "fill",
									intrinsicHeight: 5702,
									intrinsicWidth: 3801,
									positionX: "left",
									positionY: "center",
								}}
								className={"framer-1m6kmi9"}
								data-framer-name={"1"}
								layoutDependency={layoutDependency}
								layoutId={"rxk3Ba5ki"}
								style={{
									borderBottomLeftRadius: 40,
									borderBottomRightRadius: 40,
									borderTopLeftRadius: 40,
									borderTopRightRadius: 40,
									boxShadow: "30px 1px 42px 0px rgba(0,0,0,0.25)",
								}}
								variants={{
									ae_P2MvE1: {
										borderBottomLeftRadius: 20,
										borderBottomRightRadius: 20,
										borderTopLeftRadius: 20,
										borderTopRightRadius: 20,
									},
								}}
							>
								<Image
									background={{
										alt: "",
										fit: "fill",
										intrinsicHeight: 3110,
										intrinsicWidth: 3844,
										pixelHeight: 3110,
										pixelWidth: 3844,
										sizes: "1900px",
										...toResponsiveImage(lyMxtJN0r),
									}}
									className={"framer-7fjhvc"}
									layoutDependency={layoutDependency}
									layoutId={"k0KaKhF_C"}
									style={{
										borderBottomLeftRadius: 40,
										borderBottomRightRadius: 40,
										borderTopLeftRadius: 40,
										borderTopRightRadius: 40,
									}}
									{...addPropertyOverrides(
										{
											At0u8XfN3: {
												"data-highlight": true,
												onMouseEnter: onMouseEnterb0hnrg,
											},
											I5Sm1NYr1: {
												"data-highlight": true,
												onMouseEnter: onMouseEnterb0hnrg,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</motion.div>
						</motion.div>
					</motion.a>
				</Link>
			</Transition>
		</LayoutGroup>
	);
});
var css3 = [
	'.framer-c8JDZ[data-border="true"]::after, .framer-c8JDZ [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-c8JDZ.framer-17w0byr, .framer-c8JDZ .framer-17w0byr { display: block; }",
	".framer-c8JDZ.framer-15qh5wp { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 650px; justify-content: center; overflow: hidden; padding: 5px 5px 5px 5px; position: relative; text-decoration: none; width: 1600px; will-change: var(--framer-will-change-override, transform); }",
	".framer-c8JDZ .framer-b31087 { flex: none; height: 100%; left: calc(50.00000000000002% - 100% / 2); overflow: visible; pointer-events: none; position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; z-index: 1; }",
	".framer-c8JDZ .framer-1x52b2u { align-content: flex-start; align-items: flex-start; bottom: 50px; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; left: 50px; overflow: visible; padding: 0px 0px 0px 0px; position: absolute; right: 50px; z-index: 1; }",
	".framer-c8JDZ .framer-vm3h56 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-c8JDZ .framer-1hsuuk1 { flex: none; height: auto; position: relative; white-space: pre; width: auto; z-index: 1; }",
	".framer-c8JDZ .framer-nn5xgm { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 44px; height: 100%; justify-content: center; overflow: hidden; padding: 60px 0px 0px 0px; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-c8JDZ .framer-1vqtcay, .framer-c8JDZ .framer-m4gi4f, .framer-c8JDZ .framer-1m6kmi9 { bottom: 0px; flex: none; height: 100%; left: 0px; overflow: hidden; position: absolute; right: 0px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-c8JDZ .framer-h8gvni, .framer-c8JDZ .framer-8vwkum, .framer-c8JDZ .framer-7fjhvc { flex: none; height: 100%; overflow: visible; position: absolute; right: 0px; top: calc(50.00000000000002% - 100% / 2); width: 1900px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-c8JDZ.framer-15qh5wp, .framer-c8JDZ .framer-1x52b2u, .framer-c8JDZ .framer-nn5xgm { gap: 0px; } .framer-c8JDZ.framer-15qh5wp > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-c8JDZ.framer-15qh5wp > :first-child { margin-left: 0px; } .framer-c8JDZ.framer-15qh5wp > :last-child { margin-right: 0px; } .framer-c8JDZ .framer-1x52b2u > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-c8JDZ .framer-1x52b2u > :first-child, .framer-c8JDZ .framer-nn5xgm > :first-child { margin-top: 0px; } .framer-c8JDZ .framer-1x52b2u > :last-child, .framer-c8JDZ .framer-nn5xgm > :last-child { margin-bottom: 0px; } .framer-c8JDZ .framer-nn5xgm > * { margin: 0px; margin-bottom: calc(44px / 2); margin-top: calc(44px / 2); } }",
	".framer-c8JDZ.framer-v-1q0tk8i .framer-m4gi4f, .framer-c8JDZ.framer-v-1j0blrb .framer-m4gi4f { right: 80px; }",
	".framer-c8JDZ.framer-v-1q0tk8i .framer-1m6kmi9 { right: 160px; }",
	".framer-c8JDZ.framer-v-umtju3.framer-15qh5wp { width: 390px; }",
	".framer-c8JDZ.framer-v-umtju3 .framer-1x52b2u { bottom: 20px; left: 20px; right: 20px; }",
	".framer-c8JDZ.framer-v-umtju3 .framer-m4gi4f { right: 28px; }",
	".framer-c8JDZ.framer-v-umtju3 .framer-1m6kmi9 { right: 60px; }",
	".framer-c8JDZ.framer-v-umtju3 .framer-7fjhvc { left: -635px; right: unset; }",
	".framer-c8JDZ.framer-v-1j0blrb .framer-1m6kmi9, .framer-c8JDZ.framer-v-tgaye6 .framer-1m6kmi9 { right: 700px; }",
	".framer-c8JDZ.framer-v-tgaye6 .framer-m4gi4f { right: 620px; }",
	...css,
	...css2,
];
var Frameraxr3X3wQ4 = withCSS(Component, css3, "framer-c8JDZ");
var stdin_default = Frameraxr3X3wQ4;
Frameraxr3X3wQ4.displayName = "Album - Image";
Frameraxr3X3wQ4.defaultProps = {
	height: 650,
	width: 1600,
};
addPropertyControls(Frameraxr3X3wQ4, {
	variant: {
		options: ["whcuTJVDU", "NJfHDcu4W", "ae_P2MvE1", "At0u8XfN3", "I5Sm1NYr1"],
		optionTitles: ["Variant 1", "Variant 2", "Phone", "Variant 4", "Variant 5"],
		title: "Variant",
		type: ControlType.Enum,
	},
	lyMxtJN0r: {
		__defaultAssetReference:
			"data:framer/asset-reference,6vX7b4cpzAhbpoO1xAOWx3pweQg.jpg?originalFilename=photo-1707661981342-6885666832a8%3Fcrop%3Dentropy%26cs%3Dsrgb%26fm%3Djpg%26ixid%3DM3wxMzc5NjJ8MHwxfGFsbHwyM3x8fHx8fDJ8fDE3MDc4MDM1NDF8%26ixlib%3Drb-4.0.jpg&preferredSize=auto",
		title: "Image 1",
		type: ControlType.ResponsiveImage,
	},
	ZZB_u6RQP: {
		__defaultAssetReference:
			"data:framer/asset-reference,Fe0bBRUkdYPiitxPwjVp8ZZnog8.jpg?originalFilename=photo-1707305311532-73bd64624a07%3Fcrop%3Dentropy%26cs%3Dsrgb%26fm%3Djpg%26ixid%3DM3wxMzc5NjJ8MHwxfGFsbHwyfHx8fHx8Mnx8MTcwNzgwMjMyNXw%26ixlib%3Drb-4.0.jpg&preferredSize=auto",
		title: "Image 2",
		type: ControlType.ResponsiveImage,
	},
	hK6R_KXxq: {
		__defaultAssetReference:
			"data:framer/asset-reference,JBQwp5PcY7eU5Y2iRSPkj9Q00.jpg?originalFilename=photo-1530109167181-4c8c11f6d317%3Fcrop%3Dentropy%26cs%3Dsrgb%26fm%3Djpg%26ixid%3DM3wxMzc5NjJ8MHwxfHNlYXJjaHwxMHx8c3RyZWV0fGVufDB8fHx8MTcwNzgwMzAwOXww%26ixlib%3Drb-4.0.jpg&preferredSize=auto",
		title: "Image 3",
		type: ControlType.ResponsiveImage,
	},
	euUqu2bvv: {
		defaultValue: "Album Title",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	c38uhUV8w: {
		defaultValue: "Short Description",
		displayTextArea: false,
		title: "Location",
		type: ControlType.String,
	},
	PlG8psyh0: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(Frameraxr3X3wQ4, [...fonts, ...fonts2]);

// virtual:album-image
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "ae_P2MvE1",
	xl: "whcuTJVDU",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8a429189ff65f2fafed7ae45547e59ca6084759351dbe5c21bdecf003cf56825"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders AlbumImageFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8a429189ff65f2fafed7ae45547e59ca6084759351dbe5c21bdecf003cf56825"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var album_image_default = ComponentWithRoot;
export { album_image_default as default };
