// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 8a429189ff65f2fa "Shareye Films", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Horizontal' | 'Vertical' // Variant
 * image?: {src: string, srcSet?: string, alt?: string} // Image
}} Props

 */
import { routes } from "./chunks/chunk-W2AWTVWO.js";

// virtual:brand-logos
import { Fragment } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/hErsdZHXqoX0BCMQOy96/QDhtigy0cNXN2ZXwrMLt/TJRW1qsJY.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	Image,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["NzbgiJYlF", "vStgjbRNM"];
var variantClassNames = {
	NzbgiJYlF: "framer-v-15os3xn",
	vStgjbRNM: "framer-v-1sqvbfx",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Horizontal: "NzbgiJYlF",
	Vertical: "vStgjbRNM",
};
var getProps = ({ height, id, image, width, ...props }) => {
	var _variant, ref, ref1;
	return {
		...props,
		variant:
			(ref =
				(_variant = humanReadableVariantMap[props.variant]) !== null &&
				_variant !== void 0
					? _variant
					: props.variant) !== null && ref !== void 0
				? ref
				: "NzbgiJYlF",
		XuQs49rUl:
			(ref1 = image !== null && image !== void 0 ? image : props.XuQs49rUl) !==
				null && ref1 !== void 0
				? ref1
				: {
						src: "https://framerusercontent.com/images/gk7QZqkTE0Z8JusfQWLflnjHLdU.svg",
					},
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale } = useLocaleInfo();
	const { style, className, layoutId, variant, XuQs49rUl, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "NzbgiJYlF",
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const defaultLayoutId = React.useId();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<motion.div
				initial={variant}
				animate={variants}
				onHoverStart={() =>
					setGestureState({
						isHovered: true,
					})
				}
				onHoverEnd={() =>
					setGestureState({
						isHovered: false,
					})
				}
				onTapStart={() =>
					setGestureState({
						isPressed: true,
					})
				}
				onTap={() =>
					setGestureState({
						isPressed: false,
					})
				}
				onTapCancel={() =>
					setGestureState({
						isPressed: false,
					})
				}
				className={cx("framer-Ar5WD", classNames)}
				style={{
					display: "contents",
				}}
			>
				<Transition value={transition}>
					<motion.div
						{...restProps}
						className={cx("framer-15os3xn", className)}
						data-border={true}
						data-framer-name={"Horizontal"}
						layoutDependency={layoutDependency}
						layoutId={"NzbgiJYlF"}
						ref={ref}
						style={{
							"--border-bottom-width": "0px",
							"--border-color":
								"var(--token-8c47652b-dea5-4767-a9f2-5d952dcce49a, rgba(255, 255, 255, 0.3))",
							"--border-left-width": "0px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "0px",
							...style,
						}}
						variants={{
							vStgjbRNM: {
								"--border-bottom-width": "0px",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-top-width": "0px",
							},
						}}
						{...addPropertyOverrides(
							{
								vStgjbRNM: {
									"data-framer-name": "Vertical",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<Image
							background={{
								alt: "",
								fit: "fit",
								sizes: "calc(min(172px, 100vw) - 40px)",
								...toResponsiveImage(XuQs49rUl),
							}}
							className={"framer-4ushn7"}
							layoutDependency={layoutDependency}
							layoutId={"sZvX9JX0Z"}
							{...addPropertyOverrides(
								{
									vStgjbRNM: {
										background: {
											alt: "",
											fit: "fit",
											sizes: "calc(min(222px, 100vw) - 24px)",
											...toResponsiveImage(XuQs49rUl),
										},
									},
								},
								baseVariant,
								gestureVariant,
							)}
						/>
					</motion.div>
				</Transition>
			</motion.div>
		</LayoutGroup>
	);
});
var css = [
	'.framer-Ar5WD [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Ar5WD .framer-1hsxb0p { display: block; }",
	".framer-Ar5WD .framer-15os3xn { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 88px; justify-content: center; overflow: hidden; padding: 0px 40px 0px 0px; position: relative; width: 172px; }",
	".framer-Ar5WD .framer-4ushn7 { flex: none; height: 100%; overflow: visible; position: relative; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-Ar5WD .framer-15os3xn { gap: 0px; } .framer-Ar5WD .framer-15os3xn > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-Ar5WD .framer-15os3xn > :first-child { margin-left: 0px; } .framer-Ar5WD .framer-15os3xn > :last-child { margin-right: 0px; } }",
	".framer-Ar5WD.framer-v-1sqvbfx .framer-15os3xn { height: 102px; padding: 12px 12px 12px 12px; width: 222px; }",
];
var FramerTJRW1qsJY = withCSS(Component, css, "framer-Ar5WD");
var stdin_default = FramerTJRW1qsJY;
FramerTJRW1qsJY.displayName = "Brand Logos";
FramerTJRW1qsJY.defaultProps = {
	height: 88,
	width: 172,
};
addPropertyControls(FramerTJRW1qsJY, {
	variant: {
		options: ["NzbgiJYlF", "vStgjbRNM"],
		optionTitles: ["Horizontal", "Vertical"],
		title: "Variant",
		type: ControlType.Enum,
	},
	XuQs49rUl: {
		__defaultAssetReference:
			"data:framer/asset-reference,gk7QZqkTE0Z8JusfQWLflnjHLdU.svg?originalFilename=logoipsum-291.svg&preferredSize=auto",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(FramerTJRW1qsJY, []);

// virtual:brand-logos
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8a429189ff65f2fafed7ae45547e59ca6084759351dbe5c21bdecf003cf56825"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders BrandLogosFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8a429189ff65f2fafed7ae45547e59ca6084759351dbe5c21bdecf003cf56825"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var brand_logos_default = ComponentWithRoot;
export { brand_logos_default as default };
