// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 8a429189ff65f2fa "Shareye Films", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * link?: string // Link
 * title?: string // Title
}} Props

 */
import { routes } from "./chunks/chunk-W2AWTVWO.js";

// virtual:button-simple
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/yXp2xtE8BDy6AmpJCJ9p/q00bIdsgMiQxk9ubVQYC/Y_7fWyPHp.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	Link,
	RichText,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var enabledGestures = {
	QeWOG18Gy: {
		hover: true,
	},
};
var cycleOrder = ["QeWOG18Gy"];
var variantClassNames = {
	QeWOG18Gy: "framer-v-1d0eirp",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var getProps = ({ height, id, link, title, width, ...props }) => {
	var _ref;
	return {
		...props,
		RAIkeOPKg:
			(_ref = title !== null && title !== void 0 ? title : props.RAIkeOPKg) !==
				null && _ref !== void 0
				? _ref
				: "Button Text",
		YxxGA7Jzn: link !== null && link !== void 0 ? link : props.YxxGA7Jzn,
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale } = useLocaleInfo();
	const {
		style,
		className,
		layoutId,
		variant,
		YxxGA7Jzn,
		RAIkeOPKg,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "QeWOG18Gy",
		enabledGestures,
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const defaultLayoutId = React.useId();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<motion.div
				initial={variant}
				animate={variants}
				onHoverStart={() =>
					setGestureState({
						isHovered: true,
					})
				}
				onHoverEnd={() =>
					setGestureState({
						isHovered: false,
					})
				}
				onTapStart={() =>
					setGestureState({
						isPressed: true,
					})
				}
				onTap={() =>
					setGestureState({
						isPressed: false,
					})
				}
				onTapCancel={() =>
					setGestureState({
						isPressed: false,
					})
				}
				className={cx("framer-0qZXU", classNames)}
				style={{
					display: "contents",
				}}
			>
				<Transition value={transition}>
					<Link href={YxxGA7Jzn}>
						<motion.a
							{...restProps}
							className={`${cx("framer-1d0eirp", className)} framer-jypr3x`}
							data-framer-name={"Variant 1"}
							data-reset={"button"}
							layoutDependency={layoutDependency}
							layoutId={"QeWOG18Gy"}
							ref={ref}
							style={{
								backdropFilter: "blur(15px)",
								backgroundColor: "rgb(255, 255, 255)",
								borderBottomLeftRadius: 40,
								borderBottomRightRadius: 40,
								borderTopLeftRadius: 40,
								borderTopRightRadius: 40,
								WebkitBackdropFilter: "blur(15px)",
								...style,
							}}
							variants={{
								"QeWOG18Gy-hover": {
									backgroundColor:
										"var(--token-4fdd7769-e1d0-45b2-8e3d-fe484baba321, rgb(255, 122, 59))",
								},
							}}
							{...addPropertyOverrides(
								{
									"QeWOG18Gy-hover": {
										"data-framer-name": void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-k8ngf7"}
								data-border={true}
								layoutDependency={layoutDependency}
								layoutId={"wAQVxknB4"}
								style={{
									"--border-bottom-width": "0px",
									"--border-color": "rgba(255, 255, 255, 0)",
									"--border-left-width": "2px",
									"--border-right-width": "0px",
									"--border-style": "solid",
									"--border-top-width": "2px",
									backdropFilter: "blur(13px)",
									borderBottomLeftRadius: 30,
									borderBottomRightRadius: 30,
									borderTopLeftRadius: 30,
									borderTopRightRadius: 30,
									WebkitBackdropFilter: "blur(13px)",
								}}
							>
								<motion.div
									className={"framer-ag1u5i"}
									layoutDependency={layoutDependency}
									layoutId={"BHA085RdR"}
									style={{
										borderBottomLeftRadius: 103,
										borderBottomRightRadius: 103,
										borderTopLeftRadius: 103,
										borderTopRightRadius: 103,
									}}
								/>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-osw0u0"}
									fonts={["GF;Syne-700"]}
									layoutDependency={layoutDependency}
									layoutId={"aCgtS2E0p"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-620fac81-7c2e-4342-b93a-72603d1fc89e, rgb(13, 13, 13))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
										"--framer-paragraph-spacing": "0px",
									}}
									text={RAIkeOPKg}
									variants={{
										"QeWOG18Gy-hover": {
											"--extracted-r6o4lv":
												"var(--token-a3567fc0-2c6f-4fa8-ac8f-89ddd158e98d, rgb(255, 255, 255))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											"QeWOG18Gy-hover": {
												children: (
													<React.Fragment>
														<motion.p
															style={{
																"--font-selector": "R0Y7U3luZS03MDA=",
																"--framer-font-family":
																	'"Syne", "Syne Placeholder", sans-serif',
																"--framer-font-weight": "700",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-a3567fc0-2c6f-4fa8-ac8f-89ddd158e98d, rgb(255, 255, 255)))",
															}}
														>
															{"text"}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											style={{
												"--font-selector": "R0Y7U3luZS03MDA=",
												"--framer-font-family":
													'"Syne", "Syne Placeholder", sans-serif',
												"--framer-font-weight": "700",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-620fac81-7c2e-4342-b93a-72603d1fc89e, rgb(13, 13, 13)))",
											}}
										>
											{"Button Text"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</motion.div>
		</LayoutGroup>
	);
});
var css = [
	'.framer-0qZXU [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-0qZXU .framer-jypr3x { display: block; }",
	".framer-0qZXU .framer-1d0eirp { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 38px; justify-content: center; overflow: hidden; padding: 0px 0px 0px 0px; position: relative; text-decoration: none; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-0qZXU .framer-k8ngf7 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 100%; justify-content: center; overflow: hidden; padding: 17px 33px 17px 33px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-0qZXU .framer-ag1u5i { flex: none; height: 100%; left: calc(50.00000000000002% - 100% / 2); overflow: visible; pointer-events: none; position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; z-index: 0; }",
	".framer-0qZXU .framer-osw0u0 { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
	".framer-0qZXU .framer-v-1d0eirp .framer-1d0eirp { cursor: pointer; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-0qZXU .framer-1d0eirp, .framer-0qZXU .framer-k8ngf7 { gap: 0px; } .framer-0qZXU .framer-1d0eirp > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-0qZXU .framer-1d0eirp > :first-child, .framer-0qZXU .framer-k8ngf7 > :first-child { margin-left: 0px; } .framer-0qZXU .framer-1d0eirp > :last-child, .framer-0qZXU .framer-k8ngf7 > :last-child { margin-right: 0px; } .framer-0qZXU .framer-k8ngf7 > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } }",
];
var FramerY_7fWyPHp = withCSS(Component, css, "framer-0qZXU");
var stdin_default = FramerY_7fWyPHp;
FramerY_7fWyPHp.displayName = "Button - Simple";
FramerY_7fWyPHp.defaultProps = {
	height: 38,
	width: 167,
};
addPropertyControls(FramerY_7fWyPHp, {
	YxxGA7Jzn: {
		title: "Link",
		type: ControlType.Link,
	},
	RAIkeOPKg: {
		defaultValue: "Button Text",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
});
addFonts(FramerY_7fWyPHp, [
	{
		family: "Syne",
		moduleAsset: {
			localModuleIdentifier: "local-module:canvasComponent/Y_7fWyPHp:default",
			url: "https://fonts.gstatic.com/s/syne/v22/8vIS7w4qzmVxsWxjBZRjr0FKM_3fvj6kR47NCV5Z.ttf",
		},
		style: "normal",
		url: "https://fonts.gstatic.com/s/syne/v22/8vIS7w4qzmVxsWxjBZRjr0FKM_3fvj6kR47NCV5Z.ttf",
		weight: "700",
	},
]);

// virtual:button-simple
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8a429189ff65f2fafed7ae45547e59ca6084759351dbe5c21bdecf003cf56825"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ButtonSimpleFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8a429189ff65f2fafed7ae45547e59ca6084759351dbe5c21bdecf003cf56825"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var button_simple_default = ComponentWithRoot;
export { button_simple_default as default };
