// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 8a429189ff65f2fa "Shareye Films", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Expanded' | 'Collapsed' // Variant
 * question?: string // Question
 * answer?: string // Answer
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-ULIILFHK.js";
import { className, css, fonts } from "./chunks/chunk-SZNAUKB7.js";
import { Icon } from "./chunks/chunk-47KIQF6Z.js";
import { routes } from "./chunks/chunk-W2AWTVWO.js";

// virtual:faq-single
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/bEmE3k6tDBn0TNi95JBs/mWvppJpxFhYqfgbAivuM/owSI6Hkfp.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var PhosphorFonts = getFonts(Icon);
var enabledGestures = {
	gFR672ewn: {
		hover: true,
	},
	tHx7IdcpF: {
		hover: true,
	},
};
var cycleOrder = ["tHx7IdcpF", "gFR672ewn"];
var serializationHash = "framer-0brUu";
var variantClassNames = {
	gFR672ewn: "framer-v-sbxogb",
	tHx7IdcpF: "framer-v-1a3ud5i",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.4,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Collapsed: "gFR672ewn",
	Expanded: "tHx7IdcpF",
};
var getProps = ({ answer, height, id, question, width, ...props }) => {
	var _ref, _ref1, _humanReadableVariantMap_props_variant, _ref2;
	return {
		...props,
		lYNDnMkcm:
			(_ref =
				question !== null && question !== void 0
					? question
					: props.lYNDnMkcm) !== null && _ref !== void 0
				? _ref
				: "What services do you offer as a video production company?",
		uVHMcNgTO:
			(_ref1 =
				answer !== null && answer !== void 0 ? answer : props.uVHMcNgTO) !==
				null && _ref1 !== void 0
				? _ref1
				: "Provide an overview of the types of video production services you specialize in, such as corporate videos, commercials, documentaries, and more.",
		variant:
			(_ref2 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref2 !== void 0
				? _ref2
				: "tHx7IdcpF",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		lYNDnMkcm,
		uVHMcNgTO,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "tHx7IdcpF",
		enabledGestures,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1gztd5u = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("gFR672ewn");
	});
	const onTappgz94i = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("tHx7IdcpF");
	});
	const ref1 = React.useRef(null);
	const isDisplayed = () => {
		if (gestureVariant === "gFR672ewn-hover") return false;
		if (baseVariant === "gFR672ewn") return false;
		return true;
	};
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className, className2];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-1a3ud5i",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Expanded"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"tHx7IdcpF"}
						onTap={onTap1gztd5u}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-8c47652b-dea5-4767-a9f2-5d952dcce49a, rgba(255, 255, 255, 0.3))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backdropFilter: "blur(10px)",
							background:
								'radial-gradient(25% 75% at 0% 0%, var(--token-31d2d8ec-6073-495b-98cd-5e142f56bc63, rgba(255, 255, 255, 0.15)) /* {"name":"White 15%"} */ 0%, rgba(0, 0, 0, 0) 100%)',
							borderBottomLeftRadius: 20,
							borderBottomRightRadius: 20,
							borderTopLeftRadius: 20,
							borderTopRightRadius: 20,
							WebkitBackdropFilter: "blur(10px)",
							...style,
						}}
						variants={{
							"gFR672ewn-hover": {
								background:
									'radial-gradient(30% 50% at 50% 0%, var(--token-31d2d8ec-6073-495b-98cd-5e142f56bc63, rgba(255, 255, 255, 0.15)) /* {"name":"White 15%"} */ 0%, rgba(0, 0, 0, 0) 100%)',
							},
							"tHx7IdcpF-hover": {
								background:
									'radial-gradient(50% 75% at 47.199999999999996% 0%, var(--token-31d2d8ec-6073-495b-98cd-5e142f56bc63, rgba(255, 255, 255, 0.15)) /* {"name":"White 15%"} */ 0%, rgba(0, 0, 0, 0) 100%)',
							},
						}}
						{...addPropertyOverrides(
							{
								"gFR672ewn-hover": {
									"data-framer-name": void 0,
								},
								"tHx7IdcpF-hover": {
									"data-framer-name": void 0,
								},
								gFR672ewn: {
									"data-framer-name": "Collapsed",
									onTap: onTappgz94i,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-6xi7gx"}
							layoutDependency={layoutDependency}
							layoutId={"c94hCKqbt"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-sif1fw"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"IFy3OtjLu"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
									opacity: 1,
								}}
								text={lYNDnMkcm}
								variants={{
									"gFR672ewn-hover": {
										opacity: 0.67,
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-usmfc9"}
										data-styles-preset={"IsgMMPEHU"}
									>
										{
											"What services do you offer as a video production company?"
										}
									</motion.p>
								</React.Fragment>
							</RichText>
							<ComponentViewportProvider>
								<motion.div
									className={"framer-1sm9r18-container"}
									layoutDependency={layoutDependency}
									layoutId={"CBJLwNYl_-container"}
									style={{
										rotate: 180,
									}}
									variants={{
										"gFR672ewn-hover": {
											rotate: 0,
										},
										gFR672ewn: {
											rotate: 0,
										},
									}}
								>
									<Icon
										color={
											"var(--token-a3567fc0-2c6f-4fa8-ac8f-89ddd158e98d, rgb(255, 255, 255))"
										}
										height={"100%"}
										iconSearch={"House"}
										iconSelection={"CaretDown"}
										id={"CBJLwNYl_"}
										layoutId={"CBJLwNYl_"}
										mirrored={false}
										selectByList={true}
										style={{
											height: "100%",
											width: "100%",
										}}
										weight={"regular"}
										width={"100%"}
										{...addPropertyOverrides(
											{
												"gFR672ewn-hover": {
													color:
														"var(--token-4fdd7769-e1d0-45b2-8e3d-fe484baba321, rgb(255, 171, 66))",
												},
												"tHx7IdcpF-hover": {
													color:
														"var(--token-2f560859-5998-4075-847c-9f666c5cfc0b, rgb(255, 99, 111))",
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
								</motion.div>
							</ComponentViewportProvider>
						</motion.div>
						{isDisplayed() && (
							<RichText
								__fromCanvasComponent={true}
								className={"framer-7tr3qf"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"p9pEpohx0"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-d9d01f21-7a47-443c-a8bc-56cdb453de6f, rgba(255, 255, 255, 0.8))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={uVHMcNgTO}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-g6micz"}
										data-styles-preset={"iLvBdfOs8"}
										style={{
											"--framer-text-alignment": "left",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-d9d01f21-7a47-443c-a8bc-56cdb453de6f, rgba(255, 255, 255, 0.8)))",
										}}
									>
										{
											"Provide an overview of the types of video production services you specialize in, such as corporate videos, commercials, documentaries, and more."
										}
									</motion.p>
								</React.Fragment>
							</RichText>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-0brUu.framer-16g2e6h, .framer-0brUu .framer-16g2e6h { display: block; }",
	".framer-0brUu.framer-1a3ud5i { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 26px; height: min-content; justify-content: center; overflow: hidden; padding: 24px; position: relative; width: 800px; will-change: var(--framer-will-change-override, transform); }",
	".framer-0brUu .framer-6xi7gx { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: hidden; padding: 0px; position: relative; width: 100%; z-index: 4; }",
	".framer-0brUu .framer-sif1fw { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 90%; word-break: break-word; word-wrap: break-word; }",
	".framer-0brUu .framer-1sm9r18-container { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 27px); position: relative; width: 25px; }",
	".framer-0brUu .framer-7tr3qf { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-0brUu.framer-1a3ud5i { gap: 0px; } .framer-0brUu.framer-1a3ud5i > * { margin: 0px; margin-bottom: calc(26px / 2); margin-top: calc(26px / 2); } .framer-0brUu.framer-1a3ud5i > :first-child { margin-top: 0px; } .framer-0brUu.framer-1a3ud5i > :last-child { margin-bottom: 0px; } }",
	".framer-0brUu.framer-v-sbxogb.hover.framer-1a3ud5i { padding: 24px 24px 24px 44px; }",
	...css,
	...css2,
	'.framer-0brUu[data-border="true"]::after, .framer-0brUu [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerowSI6Hkfp = withCSS(Component, css3, "framer-0brUu");
var stdin_default = FramerowSI6Hkfp;
FramerowSI6Hkfp.displayName = "FAQ - Single";
FramerowSI6Hkfp.defaultProps = {
	height: 146,
	width: 800,
};
addPropertyControls(FramerowSI6Hkfp, {
	variant: {
		options: ["tHx7IdcpF", "gFR672ewn"],
		optionTitles: ["Expanded", "Collapsed"],
		title: "Variant",
		type: ControlType.Enum,
	},
	lYNDnMkcm: {
		defaultValue: "What services do you offer as a video production company?",
		displayTextArea: true,
		title: "Question",
		type: ControlType.String,
	},
	uVHMcNgTO: {
		defaultValue:
			"Provide an overview of the types of video production services you specialize in, such as corporate videos, commercials, documentaries, and more.",
		displayTextArea: true,
		title: "Answer",
		type: ControlType.String,
	},
});
addFonts(
	FramerowSI6Hkfp,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...PhosphorFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:faq-single
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "gFR672ewn",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8a429189ff65f2fafed7ae45547e59ca6084759351dbe5c21bdecf003cf56825"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FaqSingleFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8a429189ff65f2fafed7ae45547e59ca6084759351dbe5c21bdecf003cf56825"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var faq_single_default = ComponentWithRoot;
export { faq_single_default as default };
