// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 8a429189ff65f2fa "Shareye Films", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' // Variant
 * file?: string // File
 * tap?: Function // Tap
 * title?: string // Title
 * client?: string // Client
 * cursor?: undefined // Cursor
}} Props

 */
import { Video } from "./chunks/chunk-U5XUVE5A.js";
import "./chunks/chunk-OHDHQFGI.js";
import { routes } from "./chunks/chunk-W2AWTVWO.js";

// virtual:featured-video-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/mzu4fP71otqF7pjhzbby/SeD17H2iCb3PyCzo8FTh/PsUfvsKBR.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getPropertyControls,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var VideoFonts = getFonts(Video);
var VideoControls = getPropertyControls(Video);
var cycleOrder = ["RxdcTC8ZX", "aJ_SkuXLs"];
var serializationHash = "framer-6wwJv";
var variantClassNames = {
	aJ_SkuXLs: "framer-v-1xurqt0",
	RxdcTC8ZX: "framer-v-3w977e",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "RxdcTC8ZX",
	"Variant 2": "aJ_SkuXLs",
};
var getProps = ({
	client,
	cursor,
	file,
	height,
	id,
	tap,
	title,
	width,
	...props
}) => {
	var _ref, _ref1, _humanReadableVariantMap_props_variant, _ref2, _ref3;
	return {
		...props,
		adALtMGad: cursor !== null && cursor !== void 0 ? cursor : props.adALtMGad,
		j3YDxvFwK: tap !== null && tap !== void 0 ? tap : props.j3YDxvFwK,
		PH62DGcwC:
			(_ref = file !== null && file !== void 0 ? file : props.PH62DGcwC) !==
				null && _ref !== void 0
				? _ref
				: "https://framerusercontent.com/assets/kdKvBb6UyIpSR2GIP2Bq6hhmuA.mp4",
		TshoKf3A0:
			(_ref1 =
				client !== null && client !== void 0 ? client : props.TshoKf3A0) !==
				null && _ref1 !== void 0
				? _ref1
				: "Client",
		variant:
			(_ref2 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref2 !== void 0
				? _ref2
				: "RxdcTC8ZX",
		Zk6V4eTO2:
			(_ref3 = title !== null && title !== void 0 ? title : props.Zk6V4eTO2) !==
				null && _ref3 !== void 0
				? _ref3
				: "Title of the video",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className,
		layoutId,
		variant,
		PH62DGcwC,
		j3YDxvFwK,
		Zk6V4eTO2,
		TshoKf3A0,
		adALtMGad,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "RxdcTC8ZX",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap106ylvp = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (j3YDxvFwK) {
			const res = await j3YDxvFwK(...args);
			if (res === false) return false;
		}
	});
	const onMouseEnter9ccmc8 = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: true,
		});
		setVariant("aJ_SkuXLs");
	});
	const onMouseLeave2wtfnr = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: false,
		});
		setVariant("RxdcTC8ZX");
	});
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-3w977e",
							className,
							classNames,
						)}
						data-framer-cursor={adALtMGad}
						data-framer-name={"Variant 1"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"RxdcTC8ZX"}
						onMouseEnter={onMouseEnter9ccmc8}
						onTap={onTap106ylvp}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							borderBottomLeftRadius: 51,
							borderBottomRightRadius: 51,
							borderTopLeftRadius: 51,
							borderTopRightRadius: 51,
							...style,
						}}
						{...addPropertyOverrides(
							{
								aJ_SkuXLs: {
									"data-framer-name": "Variant 2",
									onMouseLeave: onMouseLeave2wtfnr,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-z5z0w4"}
							layoutDependency={layoutDependency}
							layoutId={"VSLSMbvo7"}
						/>
						<ComponentViewportProvider>
							<motion.div
								className={"framer-6ckonu-container"}
								layoutDependency={layoutDependency}
								layoutId={"KVxLoV5wF-container"}
							>
								<Video
									backgroundColor={"rgba(0, 0, 0, 0)"}
									borderRadius={0}
									bottomLeftRadius={0}
									bottomRightRadius={0}
									controls={false}
									height={"100%"}
									id={"KVxLoV5wF"}
									isMixedBorderRadius={false}
									layoutId={"KVxLoV5wF"}
									loop={true}
									muted={true}
									objectFit={"cover"}
									playing={false}
									posterEnabled={false}
									srcFile={PH62DGcwC}
									srcType={"Upload"}
									srcUrl={
										"https://assets.mixkit.co/videos/preview/mixkit-ice-cream-glass-of-red-soda-5094-small.mp4"
									}
									startTime={0}
									style={{
										height: "100%",
										width: "100%",
									}}
									topLeftRadius={0}
									topRightRadius={0}
									volume={25}
									width={"100%"}
									{...addPropertyOverrides(
										{
											aJ_SkuXLs: {
												playing: true,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</motion.div>
						</ComponentViewportProvider>
						<motion.div
							className={"framer-10l3fb5"}
							layoutDependency={layoutDependency}
							layoutId={"tcUoN2clB"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-tgrrpw"}
								fonts={["GF;Syne-600"]}
								layoutDependency={layoutDependency}
								layoutId={"YDB_PCxRv"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-a3567fc0-2c6f-4fa8-ac8f-89ddd158e98d, rgb(255, 255, 255))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={Zk6V4eTO2}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										style={{
											"--font-selector": "R0Y7U3luZS02MDA=",
											"--framer-font-family": '"Syne", sans-serif',
											"--framer-font-size": "24px",
											"--framer-font-weight": "600",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-a3567fc0-2c6f-4fa8-ac8f-89ddd158e98d, rgb(255, 255, 255)))",
										}}
									>
										{"Title of the video"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-102kxjx"}
								fonts={["GF;Syne-regular"]}
								layoutDependency={layoutDependency}
								layoutId={"yHdGxckjH"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-a3567fc0-2c6f-4fa8-ac8f-89ddd158e98d, rgb(255, 255, 255))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={TshoKf3A0}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										style={{
											"--font-selector": "R0Y7U3luZS1yZWd1bGFy",
											"--framer-font-family":
												'"Syne", "Syne Placeholder", sans-serif',
											"--framer-font-size": "13px",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-a3567fc0-2c6f-4fa8-ac8f-89ddd158e98d, rgb(255, 255, 255)))",
										}}
									>
										{"Client"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-6wwJv.framer-32z9fl, .framer-6wwJv .framer-32z9fl { display: block; }",
	".framer-6wwJv.framer-3w977e { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 580px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 580px; will-change: var(--framer-will-change-override, transform); }",
	".framer-6wwJv .framer-z5z0w4 { cursor: none; flex: none; height: 100%; left: calc(50.00000000000002% - 100% / 2); overflow: visible; position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; z-index: 1; }",
	".framer-6wwJv .framer-6ckonu-container { flex: none; height: 100%; position: relative; width: 100%; }",
	".framer-6wwJv .framer-10l3fb5 { align-content: flex-start; align-items: flex-start; bottom: 39px; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; left: 34px; mix-blend-mode: difference; overflow: visible; padding: 0px; position: absolute; width: min-content; z-index: 1; }",
	".framer-6wwJv .framer-tgrrpw, .framer-6wwJv .framer-102kxjx { flex: none; height: auto; position: relative; white-space: pre; width: auto; z-index: 1; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-6wwJv.framer-3w977e, .framer-6wwJv .framer-10l3fb5 { gap: 0px; } .framer-6wwJv.framer-3w977e > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-6wwJv.framer-3w977e > :first-child, .framer-6wwJv .framer-10l3fb5 > :first-child { margin-top: 0px; } .framer-6wwJv.framer-3w977e > :last-child, .framer-6wwJv .framer-10l3fb5 > :last-child { margin-bottom: 0px; } .framer-6wwJv .framer-10l3fb5 > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } }",
	".framer-6wwJv.framer-v-1xurqt0.framer-3w977e { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 580px); }",
];
var FramerPsUfvsKBR = withCSS(Component, css, "framer-6wwJv");
var stdin_default = FramerPsUfvsKBR;
FramerPsUfvsKBR.displayName = "Featured Video Card";
FramerPsUfvsKBR.defaultProps = {
	height: 580,
	width: 580,
};
addPropertyControls(FramerPsUfvsKBR, {
	variant: {
		options: ["RxdcTC8ZX", "aJ_SkuXLs"],
		optionTitles: ["Variant 1", "Variant 2"],
		title: "Variant",
		type: ControlType.Enum,
	},
	PH62DGcwC: (VideoControls === null || VideoControls === void 0
		? void 0
		: VideoControls["srcFile"]) && {
		...VideoControls["srcFile"],
		__defaultAssetReference:
			"data:framer/asset-reference,kdKvBb6UyIpSR2GIP2Bq6hhmuA.mp4?originalFilename=production_id_4488737+%28360p%29.mp4",
		description: void 0,
		hidden: void 0,
		title: "File",
	},
	j3YDxvFwK: {
		title: "Tap",
		type: ControlType.EventHandler,
	},
	Zk6V4eTO2: {
		defaultValue: "Title of the video",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	TshoKf3A0: {
		defaultValue: "Client",
		displayTextArea: false,
		title: "Client",
		type: ControlType.String,
	},
	adALtMGad: {
		title: "Cursor",
		type: ControlType.CustomCursor,
	},
});
addFonts(
	FramerPsUfvsKBR,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Syne",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/syne/v22/8vIS7w4qzmVxsWxjBZRjr0FKM_3mvj6hR47NCV5Z.woff2",
					weight: "600",
				},
				{
					family: "Syne",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/syne/v22/8vIS7w4qzmVxsWxjBZRjr0FKM_04uT6hR47NCV5Z.woff2",
					weight: "400",
				},
			],
		},
		...VideoFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:featured-video-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "aJ_SkuXLs",
	xl: "RxdcTC8ZX",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8a429189ff65f2fafed7ae45547e59ca6084759351dbe5c21bdecf003cf56825"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FeaturedVideoCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8a429189ff65f2fafed7ae45547e59ca6084759351dbe5c21bdecf003cf56825"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var featured_video_card_default = ComponentWithRoot;
export { featured_video_card_default as default };
