// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 8a429189ff65f2fa "Shareye Films", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Expanded' | 'Collapsed' | 'Phone Collapsed' | 'Phone Expanded' // Variant
 * title?: string // Title
 * description?: string // Description
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * row1?: string // Row 1
 * row2?: string // Row 2
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-6IVYILAF.js";
import { className, css, fonts } from "./chunks/chunk-J47HK3IR.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-PU5SU6N7.js";
import { Icon } from "./chunks/chunk-47KIQF6Z.js";
import { routes } from "./chunks/chunk-W2AWTVWO.js";

// virtual:homepage-service
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/q3WlJ1hDXhkFGA3po1ro/BQQESK3EAAlTNuBvpcIF/IVozL5jyY.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	Image,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var PhosphorFonts = getFonts(Icon);
var enabledGestures = {
	M4x0ZduiV: {
		hover: true,
	},
	NvSY0AjTO: {
		hover: true,
	},
};
var cycleOrder = ["NvSY0AjTO", "M4x0ZduiV", "i3OUhIoZi", "YR7CuyKoH"];
var serializationHash = "framer-EpPDH";
var variantClassNames = {
	i3OUhIoZi: "framer-v-lpc4rc",
	M4x0ZduiV: "framer-v-1s6d1df",
	NvSY0AjTO: "framer-v-pxhdii",
	YR7CuyKoH: "framer-v-1urtpzu",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 270,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var humanReadableVariantMap = {
	"Phone Collapsed": "i3OUhIoZi",
	"Phone Expanded": "YR7CuyKoH",
	Collapsed: "M4x0ZduiV",
	Expanded: "NvSY0AjTO",
};
var getProps = ({
	description,
	height,
	id,
	image,
	row1,
	row2,
	title,
	width,
	...props
}) => {
	var _ref,
		_ref1,
		_ref2,
		_humanReadableVariantMap_props_variant,
		_ref3,
		_ref4,
		_ref5;
	return {
		...props,
		DFIDx_49F:
			(_ref = image !== null && image !== void 0 ? image : props.DFIDx_49F) !==
				null && _ref !== void 0
				? _ref
				: {
						src: "https://framerusercontent.com/images/cU8i3FwPr0fkSH5zeivVz7Q3AY.jpg?scale-down-to=1024",
						srcSet:
							"https://framerusercontent.com/images/cU8i3FwPr0fkSH5zeivVz7Q3AY.jpg?scale-down-to=1024 682w,https://framerusercontent.com/images/cU8i3FwPr0fkSH5zeivVz7Q3AY.jpg?scale-down-to=2048 1365w,https://framerusercontent.com/images/cU8i3FwPr0fkSH5zeivVz7Q3AY.jpg 2334w",
					},
		I43n4JqNq:
			(_ref1 = row2 !== null && row2 !== void 0 ? row2 : props.I43n4JqNq) !==
				null && _ref1 !== void 0
				? _ref1
				: "Storyboarding\nLocation Scouting\nCasting",
		i5O03YodR:
			(_ref2 =
				description !== null && description !== void 0
					? description
					: props.i5O03YodR) !== null && _ref2 !== void 0
				? _ref2
				: "Where creativity meets strategy. We collaborate to shape your vision into a actionable plan.",
		variant:
			(_ref3 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref3 !== void 0
				? _ref3
				: "NvSY0AjTO",
		wfGtFKOCx:
			(_ref4 = title !== null && title !== void 0 ? title : props.wfGtFKOCx) !==
				null && _ref4 !== void 0
				? _ref4
				: "Video Editing",
		YEq393da6:
			(_ref5 = row1 !== null && row1 !== void 0 ? row1 : props.YEq393da6) !==
				null && _ref5 !== void 0
				? _ref5
				: "Concept Development\nScriptwriting\nStoryboarding\n",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		wfGtFKOCx,
		i5O03YodR,
		DFIDx_49F,
		YEq393da6,
		I43n4JqNq,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureHandlers,
		gestureVariant,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "NvSY0AjTO",
		enabledGestures,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1nm0m5i = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("M4x0ZduiV");
	});
	const onTap1d1jhgp = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("NvSY0AjTO");
	});
	const onTaptvijn1 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("YR7CuyKoH");
	});
	const onTap1j3lih6 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("i3OUhIoZi");
	});
	const ref1 = React.useRef(null);
	const isDisplayed = () => {
		if (["i3OUhIoZi", "YR7CuyKoH"].includes(baseVariant)) return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (gestureVariant === "M4x0ZduiV-hover") return false;
		if (["M4x0ZduiV", "i3OUhIoZi"].includes(baseVariant)) return false;
		return true;
	};
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className2, className, className3];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-pxhdii",
							className4,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Expanded"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"NvSY0AjTO"}
						onTap={onTap1nm0m5i}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-8c47652b-dea5-4767-a9f2-5d952dcce49a, rgba(255, 255, 255, 0.3))",
							"--border-left-width": "2px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "2px",
							background:
								'radial-gradient(50% 50% at 0% 0%, var(--token-31d2d8ec-6073-495b-98cd-5e142f56bc63, rgba(255, 255, 255, 0.15)) /* {"name":"White 15%"} */ 2.210024196147939%, hsla(0, 0%, 100%, 0) 100%)',
							borderBottomLeftRadius: 30,
							borderBottomRightRadius: 30,
							borderTopLeftRadius: 30,
							borderTopRightRadius: 30,
							...style,
						}}
						variants={{
							"M4x0ZduiV-hover": {
								"--border-color":
									"var(--token-8296390c-3e4f-4c48-afd6-ee4e9808dfbe, rgba(255, 255, 255, 0.5))",
								"--border-left-width": "1px",
								background:
									'radial-gradient(50% 50% at 50% 0%, var(--token-31d2d8ec-6073-495b-98cd-5e142f56bc63, rgba(255, 255, 255, 0.15)) /* {"name":"White 15%"} */ 2.210024196147939%, hsla(0, 0%, 100%, 0) 100%)',
							},
							"NvSY0AjTO-hover": {
								"--border-color":
									"var(--token-8296390c-3e4f-4c48-afd6-ee4e9808dfbe, rgba(255, 255, 255, 0.5))",
								"--border-left-width": "1px",
								background:
									'radial-gradient(50% 50% at 50% 0%, var(--token-31d2d8ec-6073-495b-98cd-5e142f56bc63, rgba(255, 255, 255, 0.15)) /* {"name":"White 15%"} */ 2.210024196147939%, hsla(0, 0%, 100%, 0) 100%)',
							},
						}}
						{...addPropertyOverrides(
							{
								"M4x0ZduiV-hover": {
									"data-framer-name": void 0,
								},
								"NvSY0AjTO-hover": {
									"data-framer-name": void 0,
								},
								i3OUhIoZi: {
									"data-framer-name": "Phone Collapsed",
									onTap: onTaptvijn1,
								},
								M4x0ZduiV: {
									"data-framer-name": "Collapsed",
									onTap: onTap1d1jhgp,
								},
								YR7CuyKoH: {
									"data-framer-name": "Phone Expanded",
									onTap: onTap1j3lih6,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{isDisplayed() && (
							<motion.div
								className={"framer-16szu7u"}
								data-framer-name={"Image Wrapper"}
								layoutDependency={layoutDependency}
								layoutId={"gLkubF5Dt"}
								style={{
									rotate: 0,
								}}
								variants={{
									"M4x0ZduiV-hover": {
										rotate: -5,
									},
									M4x0ZduiV: {
										rotate: 4,
									},
								}}
							>
								<Image
									background={{
										alt: "",
										fit: "fill",
										intrinsicHeight: 3500,
										intrinsicWidth: 2334,
										pixelHeight: 3500,
										pixelWidth: 2334,
										sizes: "254px",
										...toResponsiveImage(DFIDx_49F),
									}}
									className={"framer-d64ho6"}
									layoutDependency={layoutDependency}
									layoutId={"eQMOKUzrn"}
									style={{
										borderBottomLeftRadius: 20,
										borderBottomRightRadius: 20,
										borderTopLeftRadius: 20,
										borderTopRightRadius: 20,
										filter: "none",
										opacity: 1,
										WebkitFilter: "none",
									}}
									variants={{
										"M4x0ZduiV-hover": {
											opacity: 1,
										},
										M4x0ZduiV: {
											filter: "grayscale(1)",
											opacity: 0,
											WebkitFilter: "grayscale(1)",
										},
									}}
								/>
							</motion.div>
						)}
						<RichText
							__fromCanvasComponent={true}
							className={"framer-624c68"}
							data-framer-name={"Title"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"favR92Sax"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							text={wfGtFKOCx}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									"M4x0ZduiV-hover": {
										children: (
											<React.Fragment>
												<motion.h3
													className={"framer-styles-preset-ravud2"}
													data-styles-preset={"MjM7LH64L"}
													style={{
														"--framer-text-alignment": "left",
													}}
												>
													<motion.span
														data-text-fill={"true"}
														style={{
															backgroundImage:
																"linear-gradient(216deg, rgb(255, 255, 255) -2.22753e-15%, rgba(255, 255, 255, 0.7) 100%)",
														}}
													>
														{"Video Editing"}
													</motion.span>
												</motion.h3>
											</React.Fragment>
										),
									},
									"NvSY0AjTO-hover": {
										children: (
											<React.Fragment>
												<motion.h3
													className={"framer-styles-preset-ravud2"}
													data-styles-preset={"MjM7LH64L"}
													style={{
														"--framer-text-alignment": "left",
													}}
												>
													<motion.span
														data-text-fill={"true"}
														style={{
															backgroundImage:
																"linear-gradient(256deg, rgb(255, 255, 255) 0%, rgba(255, 255, 255, 0.58) 100%)",
														}}
													>
														{"Video Editing"}
													</motion.span>
												</motion.h3>
											</React.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.h3
									className={"framer-styles-preset-ravud2"}
									data-styles-preset={"MjM7LH64L"}
									style={{
										"--framer-text-alignment": "left",
									}}
								>
									<motion.span
										data-text-fill={"true"}
										style={{
											backgroundImage:
												"linear-gradient(98deg, rgb(255, 255, 255) -2.22753e-15%, rgba(255, 255, 255, 0.77) 100%)",
										}}
									>
										{"Video Editing"}
									</motion.span>
								</motion.h3>
							</React.Fragment>
						</RichText>
						<motion.div
							className={"framer-mzim4c"}
							data-framer-name={"Text Wrapperr"}
							layoutDependency={layoutDependency}
							layoutId={"S0gaq_Nec"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-ez4gff"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"mSvbEgZSa"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-d9d01f21-7a47-443c-a8bc-56cdb453de6f, rgba(255, 255, 255, 0.8))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={i5O03YodR}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-smtg16"}
										data-styles-preset={"DuMLJ2VUN"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-d9d01f21-7a47-443c-a8bc-56cdb453de6f, rgba(255, 255, 255, 0.8)))",
										}}
									>
										{
											"Where creativity meets strategy. We collaborate to shape your vision into a actionable plan."
										}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						{isDisplayed1() && (
							<motion.div
								className={"framer-1fmuphu"}
								data-framer-name={"Services"}
								layoutDependency={layoutDependency}
								layoutId={"qScPo0TMV"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-whod3y"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"GkRNnTxQA"}
									style={{
										"--extracted-1w3ko1f":
											"var(--token-d9d01f21-7a47-443c-a8bc-56cdb453de6f, rgba(255, 255, 255, 0.8))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={YEq393da6}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-5vsgqx"}
											data-styles-preset={"urlDCZwpF"}
										>
											<motion.span
												style={{
													"--framer-text-color":
														"var(--extracted-1w3ko1f, var(--token-d9d01f21-7a47-443c-a8bc-56cdb453de6f, rgba(255, 255, 255, 0.8)))",
												}}
											>
												{"Concept Development"}
												<motion.br />
												{"Scriptwriting"}
												<motion.br />
												{"Storyboarding"}
												<motion.br />
											</motion.span>
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1g4e4u"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"qLEc_yo46"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-d9d01f21-7a47-443c-a8bc-56cdb453de6f, rgba(255, 255, 255, 0.8))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={I43n4JqNq}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-5vsgqx"}
											data-styles-preset={"urlDCZwpF"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-d9d01f21-7a47-443c-a8bc-56cdb453de6f, rgba(255, 255, 255, 0.8)))",
											}}
										>
											{"Storyboarding"}
											<motion.br />
											{"Location Scouting"}
											<motion.br />
											{"Casting"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						)}
						<motion.div
							className={"framer-fbz94t"}
							data-border={true}
							data-framer-name={"Button"}
							layoutDependency={layoutDependency}
							layoutId={"PnVVD8JYe"}
							style={{
								"--border-bottom-width": "0.5px",
								"--border-color":
									"var(--token-8c47652b-dea5-4767-a9f2-5d952dcce49a, rgba(255, 255, 255, 0.3))",
								"--border-left-width": "0.5px",
								"--border-right-width": "0.5px",
								"--border-style": "solid",
								"--border-top-width": "0.5px",
								backdropFilter: "blur(5px)",
								backgroundColor:
									"var(--token-620fac81-7c2e-4342-b93a-72603d1fc89e, rgb(13, 13, 13))",
								borderBottomLeftRadius: 27,
								borderBottomRightRadius: 27,
								borderTopLeftRadius: 27,
								borderTopRightRadius: 27,
								WebkitBackdropFilter: "blur(5px)",
							}}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-q9a98g"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"ojKptD9Sg"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-a3567fc0-2c6f-4fa8-ac8f-89ddd158e98d, rgb(255, 255, 255))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										i3OUhIoZi: {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-5vsgqx"}
														data-styles-preset={"urlDCZwpF"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-a3567fc0-2c6f-4fa8-ac8f-89ddd158e98d, rgb(255, 255, 255)))",
														}}
													>
														{"Learn More"}
													</motion.p>
												</React.Fragment>
											),
										},
										M4x0ZduiV: {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-5vsgqx"}
														data-styles-preset={"urlDCZwpF"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-a3567fc0-2c6f-4fa8-ac8f-89ddd158e98d, rgb(255, 255, 255)))",
														}}
													>
														{"Learn More"}
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-5vsgqx"}
										data-styles-preset={"urlDCZwpF"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-a3567fc0-2c6f-4fa8-ac8f-89ddd158e98d, rgb(255, 255, 255)))",
										}}
									>
										{"Hide details"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<ComponentViewportProvider>
								<motion.div
									className={"framer-4xy95o-container"}
									layoutDependency={layoutDependency}
									layoutId={"qz1COLjl_-container"}
									style={{
										rotate: 270,
									}}
									variants={{
										"M4x0ZduiV-hover": {
											rotate: 0,
										},
										"NvSY0AjTO-hover": {
											rotate: 180,
										},
										i3OUhIoZi: {
											rotate: 0,
										},
										M4x0ZduiV: {
											rotate: -90,
										},
										YR7CuyKoH: {
											rotate: 180,
										},
									}}
								>
									<Icon
										color={
											"var(--token-d9d01f21-7a47-443c-a8bc-56cdb453de6f, rgba(255, 255, 255, 0.8))"
										}
										height={"100%"}
										iconSearch={"House"}
										iconSelection={"ArrowCircleDown"}
										id={"qz1COLjl_"}
										layoutId={"qz1COLjl_"}
										mirrored={false}
										selectByList={true}
										style={{
											height: "100%",
											width: "100%",
										}}
										weight={"thin"}
										width={"100%"}
										{...addPropertyOverrides(
											{
												"M4x0ZduiV-hover": {
													color:
														"var(--token-4fdd7769-e1d0-45b2-8e3d-fe484baba321, rgb(255, 171, 66))",
													weight: "duotone",
												},
												"NvSY0AjTO-hover": {
													color:
														"var(--token-2f560859-5998-4075-847c-9f666c5cfc0b, rgb(255, 99, 111))",
													weight: "duotone",
												},
												i3OUhIoZi: {
													color:
														"var(--token-4fdd7769-e1d0-45b2-8e3d-fe484baba321, rgb(255, 171, 66))",
													weight: "duotone",
												},
												YR7CuyKoH: {
													color:
														"var(--token-2f560859-5998-4075-847c-9f666c5cfc0b, rgb(255, 99, 111))",
													weight: "duotone",
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
								</motion.div>
							</ComponentViewportProvider>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-EpPDH.framer-xxlfh1, .framer-EpPDH .framer-xxlfh1 { display: block; }",
	".framer-EpPDH.framer-pxhdii { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 21px; height: min-content; justify-content: center; overflow: visible; padding: 40px; position: relative; width: 750px; }",
	".framer-EpPDH .framer-16szu7u { align-content: center; align-items: center; bottom: -1px; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: center; left: -290px; overflow: visible; padding: 0px; pointer-events: none; position: absolute; width: 254px; z-index: 1; }",
	".framer-EpPDH .framer-d64ho6 { flex: none; height: 100%; left: calc(50.14164305949011% - 100% / 2); mix-blend-mode: difference; overflow: visible; position: absolute; top: calc(50.12987012987015% - 100% / 2); width: 100%; z-index: 2; }",
	".framer-EpPDH .framer-624c68 { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-EpPDH .framer-mzim4c, .framer-EpPDH .framer-1fmuphu { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-EpPDH .framer-ez4gff, .framer-EpPDH .framer-whod3y, .framer-EpPDH .framer-1g4e4u { -webkit-user-select: none; flex: 1 0 0px; height: auto; pointer-events: none; position: relative; user-select: none; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-EpPDH .framer-fbz94t { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 5px; height: min-content; justify-content: center; overflow: visible; padding: 5px 3px 5px 20px; pointer-events: none; position: relative; width: min-content; }",
	".framer-EpPDH .framer-q9a98g { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-EpPDH .framer-4xy95o-container { flex: none; height: 30px; position: relative; width: 30px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-EpPDH.framer-pxhdii, .framer-EpPDH .framer-16szu7u, .framer-EpPDH .framer-mzim4c, .framer-EpPDH .framer-1fmuphu, .framer-EpPDH .framer-fbz94t { gap: 0px; } .framer-EpPDH.framer-pxhdii > * { margin: 0px; margin-bottom: calc(21px / 2); margin-top: calc(21px / 2); } .framer-EpPDH.framer-pxhdii > :first-child, .framer-EpPDH .framer-16szu7u > :first-child { margin-top: 0px; } .framer-EpPDH.framer-pxhdii > :last-child, .framer-EpPDH .framer-16szu7u > :last-child { margin-bottom: 0px; } .framer-EpPDH .framer-16szu7u > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-EpPDH .framer-mzim4c > *, .framer-EpPDH .framer-1fmuphu > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-EpPDH .framer-mzim4c > :first-child, .framer-EpPDH .framer-1fmuphu > :first-child, .framer-EpPDH .framer-fbz94t > :first-child { margin-left: 0px; } .framer-EpPDH .framer-mzim4c > :last-child, .framer-EpPDH .framer-1fmuphu > :last-child, .framer-EpPDH .framer-fbz94t > :last-child { margin-right: 0px; } .framer-EpPDH .framer-fbz94t > * { margin: 0px; margin-left: calc(5px / 2); margin-right: calc(5px / 2); } }",
	".framer-EpPDH.framer-v-1s6d1df .framer-16szu7u { bottom: unset; left: unset; right: 30px; top: -180px; }",
	".framer-EpPDH.framer-v-lpc4rc.framer-pxhdii, .framer-EpPDH.framer-v-1urtpzu.framer-pxhdii { padding: 30px 20px 30px 20px; }",
	".framer-EpPDH.framer-v-1urtpzu .framer-1fmuphu { flex-direction: column; gap: 0px; }",
	".framer-EpPDH.framer-v-1urtpzu .framer-whod3y, .framer-EpPDH.framer-v-1urtpzu .framer-1g4e4u { flex: none; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-EpPDH.framer-v-1urtpzu .framer-1fmuphu { gap: 0px; } .framer-EpPDH.framer-v-1urtpzu .framer-1fmuphu > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-EpPDH.framer-v-1urtpzu .framer-1fmuphu > :first-child { margin-top: 0px; } .framer-EpPDH.framer-v-1urtpzu .framer-1fmuphu > :last-child { margin-bottom: 0px; } }",
	".framer-EpPDH.framer-v-1s6d1df.hover .framer-16szu7u { bottom: unset; left: calc(52.26666666666668% - 254px / 2); right: unset; top: -203px; }",
	".framer-EpPDH.framer-v-1s6d1df.hover .framer-fbz94t { gap: 15px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-EpPDH.framer-v-1s6d1df.hover .framer-fbz94t { gap: 0px; } .framer-EpPDH.framer-v-1s6d1df.hover .framer-fbz94t > * { margin: 0px; margin-left: calc(15px / 2); margin-right: calc(15px / 2); } .framer-EpPDH.framer-v-1s6d1df.hover .framer-fbz94t > :first-child { margin-left: 0px; } .framer-EpPDH.framer-v-1s6d1df.hover .framer-fbz94t > :last-child { margin-right: 0px; } }",
	".framer-EpPDH.framer-v-pxhdii.hover .framer-fbz94t { gap: 16px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-EpPDH.framer-v-pxhdii.hover .framer-fbz94t { gap: 0px; } .framer-EpPDH.framer-v-pxhdii.hover .framer-fbz94t > * { margin: 0px; margin-left: calc(16px / 2); margin-right: calc(16px / 2); } .framer-EpPDH.framer-v-pxhdii.hover .framer-fbz94t > :first-child { margin-left: 0px; } .framer-EpPDH.framer-v-pxhdii.hover .framer-fbz94t > :last-child { margin-right: 0px; } }",
	...css2,
	...css,
	...css3,
	'.framer-EpPDH[data-border="true"]::after, .framer-EpPDH [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerIVozL5jyY = withCSS(Component, css4, "framer-EpPDH");
var stdin_default = FramerIVozL5jyY;
FramerIVozL5jyY.displayName = "Homepage - Service";
FramerIVozL5jyY.defaultProps = {
	height: 354,
	width: 750,
};
addPropertyControls(FramerIVozL5jyY, {
	variant: {
		options: ["NvSY0AjTO", "M4x0ZduiV", "i3OUhIoZi", "YR7CuyKoH"],
		optionTitles: [
			"Expanded",
			"Collapsed",
			"Phone Collapsed",
			"Phone Expanded",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
	wfGtFKOCx: {
		defaultValue: "Video Editing",
		displayTextArea: true,
		title: "Title",
		type: ControlType.String,
	},
	i5O03YodR: {
		defaultValue:
			"Where creativity meets strategy. We collaborate to shape your vision into a actionable plan.",
		displayTextArea: true,
		title: "Description",
		type: ControlType.String,
	},
	DFIDx_49F: {
		__defaultAssetReference:
			"data:framer/asset-reference,cU8i3FwPr0fkSH5zeivVz7Q3AY.jpg?originalFilename=photo-1695209387889-dd34362dc1cc%3Fcrop%3Dentropy%26cs%3Dsrgb%26fm%3Djpg%26ixid%3DM3wxMzc5NjJ8MHwxfGFsbHwyfHx8fHx8Mnx8MTY5NTQwMDIxMHw%26ixlib%3Drb-4.0.jpg&preferredSize=auto",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	YEq393da6: {
		defaultValue: "Concept Development\nScriptwriting\nStoryboarding\n",
		displayTextArea: true,
		title: "Row 1",
		type: ControlType.String,
	},
	I43n4JqNq: {
		defaultValue: "Storyboarding\nLocation Scouting\nCasting",
		displayTextArea: true,
		title: "Row 2",
		type: ControlType.String,
	},
});
addFonts(
	FramerIVozL5jyY,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://app.framerstatic.com/Inter-Regular.cyrillic-ext-CFTLRB35.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://app.framerstatic.com/Inter-Regular.cyrillic-KKLZBALH.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://app.framerstatic.com/Inter-Regular.greek-ext-ULEBLIFV.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://app.framerstatic.com/Inter-Regular.greek-IRHSNFQB.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://app.framerstatic.com/Inter-Regular.latin-ext-VZDUGU3Q.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://app.framerstatic.com/Inter-Regular.latin-JLQMKCHE.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://app.framerstatic.com/Inter-Regular.vietnamese-QK7VSWXK.woff2",
					weight: "400",
				},
			],
		},
		...PhosphorFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:homepage-service
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "i3OUhIoZi",
	xl: "M4x0ZduiV",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8a429189ff65f2fafed7ae45547e59ca6084759351dbe5c21bdecf003cf56825"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HomepageServiceFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8a429189ff65f2fafed7ae45547e59ca6084759351dbe5c21bdecf003cf56825"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var homepage_service_default = ComponentWithRoot;
export { homepage_service_default as default };
