// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 8a429189ff65f2fa "Shareye Films", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' | 'Variant 3' // Variant
 * image1?: {src: string, srcSet?: string, alt?: string} // Image 1
 * image2?: {src: string, srcSet?: string, alt?: string} // Image 2
 * image3?: {src: string, srcSet?: string, alt?: string} // Image 3
}} Props

 */
import { routes } from "./chunks/chunk-W2AWTVWO.js";

// virtual:image-slideshow-about-us-page
import { Fragment } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/k8SQ5eFaBkoAlKFuVvD0/zHUurGpq1DXgiooOw51w/d2ihu3mGR.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	Image,
	useActiveVariantCallback,
	useLocaleInfo,
	useOnVariantChange,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["sDDCnlv0x", "q86QxoCAO", "bGftNU2h_"];
var variantClassNames = {
	bGftNU2h_: "framer-v-o94xhb",
	q86QxoCAO: "framer-v-mlg8re",
	sDDCnlv0x: "framer-v-1wmihwa",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		mass: 6.6,
		stiffness: 97,
		type: "spring",
	},
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Variant 1": "sDDCnlv0x",
	"Variant 2": "q86QxoCAO",
	"Variant 3": "bGftNU2h_",
};
var getProps = ({ height, id, image1, image2, image3, width, ...props }) => {
	var _ref, _ref1, _ref2, _humanReadableVariantMap_props_variant, _ref3;
	return {
		...props,
		duKTqhcrf:
			(_ref =
				image1 !== null && image1 !== void 0 ? image1 : props.duKTqhcrf) !==
				null && _ref !== void 0
				? _ref
				: {
						src: "https://framerusercontent.com/images/d6N41UBevEZe6qcpCyi5XKfGs4.jpg?scale-down-to=1024",
						srcSet:
							"https://framerusercontent.com/images/d6N41UBevEZe6qcpCyi5XKfGs4.jpg?scale-down-to=512 512w, https://framerusercontent.com/images/d6N41UBevEZe6qcpCyi5XKfGs4.jpg?scale-down-to=1024 1024w, https://framerusercontent.com/images/d6N41UBevEZe6qcpCyi5XKfGs4.jpg?scale-down-to=2048 2048w, https://framerusercontent.com/images/d6N41UBevEZe6qcpCyi5XKfGs4.jpg?scale-down-to=4096 4096w, https://framerusercontent.com/images/d6N41UBevEZe6qcpCyi5XKfGs4.jpg 5760w",
					},
		M9q6OGnh9:
			(_ref1 =
				image3 !== null && image3 !== void 0 ? image3 : props.M9q6OGnh9) !==
				null && _ref1 !== void 0
				? _ref1
				: {
						src: "https://framerusercontent.com/images/xbXkBDo9mvpVFEBpvk41UO4f9RA.jpg?scale-down-to=1024",
						srcSet:
							"https://framerusercontent.com/images/xbXkBDo9mvpVFEBpvk41UO4f9RA.jpg?scale-down-to=512 512w, https://framerusercontent.com/images/xbXkBDo9mvpVFEBpvk41UO4f9RA.jpg?scale-down-to=1024 1024w, https://framerusercontent.com/images/xbXkBDo9mvpVFEBpvk41UO4f9RA.jpg?scale-down-to=2048 2048w, https://framerusercontent.com/images/xbXkBDo9mvpVFEBpvk41UO4f9RA.jpg 2792w",
					},
		v_aHxy8b0:
			(_ref2 =
				image2 !== null && image2 !== void 0 ? image2 : props.v_aHxy8b0) !==
				null && _ref2 !== void 0
				? _ref2
				: {
						src: "https://framerusercontent.com/images/62fBwAmnlMEZezATDj3tVnxPgbY.jpg?scale-down-to=1024",
						srcSet:
							"https://framerusercontent.com/images/62fBwAmnlMEZezATDj3tVnxPgbY.jpg?scale-down-to=512 512w, https://framerusercontent.com/images/62fBwAmnlMEZezATDj3tVnxPgbY.jpg?scale-down-to=1024 1024w, https://framerusercontent.com/images/62fBwAmnlMEZezATDj3tVnxPgbY.jpg?scale-down-to=2048 2048w, https://framerusercontent.com/images/62fBwAmnlMEZezATDj3tVnxPgbY.jpg?scale-down-to=4096 4096w, https://framerusercontent.com/images/62fBwAmnlMEZezATDj3tVnxPgbY.jpg 7950w",
					},
		variant:
			(_ref3 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref3 !== void 0
				? _ref3
				: "sDDCnlv0x",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale } = useLocaleInfo();
	const {
		style,
		className,
		layoutId,
		variant,
		duKTqhcrf,
		v_aHxy8b0,
		M9q6OGnh9,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "sDDCnlv0x",
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onAppear12y5ha1 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("q86QxoCAO"), 2e3);
	});
	const onAppear1oa55ry = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("bGftNU2h_"), 2e3);
	});
	const onAppearjsp91l = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("sDDCnlv0x"), 2e3);
	});
	useOnVariantChange(baseVariant, {
		bGftNU2h_: onAppearjsp91l,
		default: onAppear12y5ha1,
		q86QxoCAO: onAppear1oa55ry,
	});
	const defaultLayoutId = React.useId();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<motion.div
				initial={variant}
				animate={variants}
				onHoverStart={() =>
					setGestureState({
						isHovered: true,
					})
				}
				onHoverEnd={() =>
					setGestureState({
						isHovered: false,
					})
				}
				onTapStart={() =>
					setGestureState({
						isPressed: true,
					})
				}
				onTap={() =>
					setGestureState({
						isPressed: false,
					})
				}
				onTapCancel={() =>
					setGestureState({
						isPressed: false,
					})
				}
				className={cx("framer-UJ4yi", classNames)}
				style={{
					display: "contents",
				}}
			>
				<Transition value={transition}>
					<motion.div
						{...restProps}
						className={cx("framer-1wmihwa", className)}
						data-framer-name={"Variant 1"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"sDDCnlv0x"}
						ref={ref}
						style={{
							borderBottomLeftRadius: 4,
							borderBottomRightRadius: 4,
							borderTopLeftRadius: 4,
							borderTopRightRadius: 4,
							...style,
						}}
						{...addPropertyOverrides(
							{
								bGftNU2h_: {
									"data-framer-name": "Variant 3",
								},
								q86QxoCAO: {
									"data-framer-name": "Variant 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-7ru6qx"}
							data-framer-name={"Image Wrapper"}
							layoutDependency={layoutDependency}
							layoutId={"zyBL6hejy"}
						>
							<motion.div
								className={"framer-1lzn9eu"}
								layoutDependency={layoutDependency}
								layoutId={"mluPEEBwM"}
								style={{
									borderBottomLeftRadius: 20,
									borderBottomRightRadius: 20,
									borderTopLeftRadius: 20,
									borderTopRightRadius: 20,
								}}
							>
								<Image
									background={{
										alt: "",
										fit: "fill",
										sizes: "490px",
										...toResponsiveImage(duKTqhcrf),
									}}
									className={"framer-9xojpt"}
									data-framer-name={"Image 1"}
									layoutDependency={layoutDependency}
									layoutId={"Wnpzgn2Cn"}
									style={{
										borderBottomLeftRadius: 20,
										borderBottomRightRadius: 20,
										borderTopLeftRadius: 20,
										borderTopRightRadius: 20,
									}}
									{...addPropertyOverrides(
										{
											bGftNU2h_: {
												background: {
													alt: "",
													fit: "fill",
													sizes: "632px",
													...toResponsiveImage(duKTqhcrf),
												},
											},
											q86QxoCAO: {
												background: {
													alt: "",
													fit: "fill",
													sizes: "632px",
													...toResponsiveImage(duKTqhcrf),
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</motion.div>
							<motion.div
								className={"framer-1rqrhi1"}
								layoutDependency={layoutDependency}
								layoutId={"PklMMfIf1"}
								style={{
									borderBottomLeftRadius: 20,
									borderBottomRightRadius: 20,
									borderTopLeftRadius: 20,
									borderTopRightRadius: 20,
								}}
							>
								<Image
									background={{
										alt: "",
										fit: "fill",
										sizes: "632px",
										...toResponsiveImage(v_aHxy8b0),
									}}
									className={"framer-1lw4bmh"}
									data-framer-name={"Image 2"}
									layoutDependency={layoutDependency}
									layoutId={"alvHiWt1x"}
									style={{
										borderBottomLeftRadius: 20,
										borderBottomRightRadius: 20,
										borderTopLeftRadius: 20,
										borderTopRightRadius: 20,
									}}
									{...addPropertyOverrides(
										{
											q86QxoCAO: {
												background: {
													alt: "",
													fit: "fill",
													sizes: "490px",
													...toResponsiveImage(v_aHxy8b0),
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</motion.div>
							<motion.div
								className={"framer-twnhvd"}
								layoutDependency={layoutDependency}
								layoutId={"lRYxDqwkF"}
								style={{
									borderBottomLeftRadius: 20,
									borderBottomRightRadius: 20,
									borderTopLeftRadius: 20,
									borderTopRightRadius: 20,
								}}
							>
								<Image
									background={{
										alt: "",
										fit: "fill",
										sizes: "632px",
										...toResponsiveImage(M9q6OGnh9),
									}}
									className={"framer-9856yu"}
									data-framer-name={"Image 3"}
									layoutDependency={layoutDependency}
									layoutId={"l9CvLKwTk"}
									style={{
										borderBottomLeftRadius: 20,
										borderBottomRightRadius: 20,
										borderTopLeftRadius: 20,
										borderTopRightRadius: 20,
									}}
									{...addPropertyOverrides(
										{
											bGftNU2h_: {
												background: {
													alt: "",
													fit: "fill",
													sizes: "490px",
													...toResponsiveImage(M9q6OGnh9),
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</motion.div>
		</LayoutGroup>
	);
});
var css = [
	'.framer-UJ4yi [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-UJ4yi .framer-9u7kax { display: block; }",
	".framer-UJ4yi .framer-1wmihwa { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 326px; justify-content: flex-end; overflow: hidden; padding: 0px 0px 0px 0px; position: relative; width: 588px; will-change: var(--framer-will-change-override, transform); }",
	".framer-UJ4yi .framer-7ru6qx { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 100%; justify-content: center; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: 1px; }",
	".framer-UJ4yi .framer-1lzn9eu { flex: 1 0 0px; height: 100%; overflow: hidden; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-UJ4yi .framer-9xojpt { flex: none; height: 100%; left: calc(50.00000000000002% - 490px / 2); overflow: hidden; position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 490px; will-change: var(--framer-will-change-override, transform); }",
	".framer-UJ4yi .framer-1rqrhi1, .framer-UJ4yi .framer-twnhvd { flex: 0.1 0 0px; height: 100%; overflow: hidden; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-UJ4yi .framer-1lw4bmh { flex: none; height: 129%; left: calc(48.97959183673471% - 632px / 2); overflow: visible; position: absolute; top: calc(50.00000000000002% - 129% / 2); width: 632px; }",
	".framer-UJ4yi .framer-9856yu { flex: none; height: 129%; left: calc(51.02040816326533% - 632px / 2); overflow: visible; position: absolute; top: calc(50.00000000000002% - 129% / 2); width: 632px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-UJ4yi .framer-1wmihwa, .framer-UJ4yi .framer-7ru6qx { gap: 0px; } .framer-UJ4yi .framer-1wmihwa > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-UJ4yi .framer-1wmihwa > :first-child, .framer-UJ4yi .framer-7ru6qx > :first-child { margin-left: 0px; } .framer-UJ4yi .framer-1wmihwa > :last-child, .framer-UJ4yi .framer-7ru6qx > :last-child { margin-right: 0px; } .framer-UJ4yi .framer-7ru6qx > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } }",
	".framer-UJ4yi.framer-v-mlg8re .framer-1lzn9eu, .framer-UJ4yi.framer-v-o94xhb .framer-1lzn9eu { flex: 0.1 0 0px; }",
	".framer-UJ4yi.framer-v-mlg8re .framer-9xojpt { height: 129%; left: calc(51.02040816326533% - 632px / 2); top: calc(50.00000000000002% - 129.14110429447854% / 2); width: 632px; }",
	".framer-UJ4yi.framer-v-mlg8re .framer-1rqrhi1, .framer-UJ4yi.framer-v-o94xhb .framer-twnhvd { flex: 1 0 0px; }",
	".framer-UJ4yi.framer-v-mlg8re .framer-1lw4bmh, .framer-UJ4yi.framer-v-o94xhb .framer-9856yu { height: 100%; left: calc(50.00000000000002% - 490px / 2); top: calc(50.00000000000002% - 100% / 2); width: 490px; }",
	".framer-UJ4yi.framer-v-o94xhb .framer-9xojpt { height: 129%; left: calc(51.02040816326533% - 632px / 2); top: calc(50.00000000000002% - 129% / 2); width: 632px; }",
	".framer-UJ4yi.framer-v-o94xhb .framer-1lw4bmh { left: calc(51.02040816326533% - 632px / 2); }",
];
var Framerd2ihu3mGR = withCSS(Component, css, "framer-UJ4yi");
var stdin_default = Framerd2ihu3mGR;
Framerd2ihu3mGR.displayName = "Image Slideshow - About us Page";
Framerd2ihu3mGR.defaultProps = {
	height: 326,
	width: 588,
};
addPropertyControls(Framerd2ihu3mGR, {
	variant: {
		options: ["sDDCnlv0x", "q86QxoCAO", "bGftNU2h_"],
		optionTitles: ["Variant 1", "Variant 2", "Variant 3"],
		title: "Variant",
		type: ControlType.Enum,
	},
	duKTqhcrf: {
		__defaultAssetReference:
			"data:framer/asset-reference,d6N41UBevEZe6qcpCyi5XKfGs4.jpg?originalFilename=photo-1497015289639-54688650d173%3Fcrop%3Dentropy%26cs%3Dsrgb%26fm%3Djpg%26ixid%3DM3wxMzc5NjJ8MHwxfHNlYXJjaHwyfHxWaWRlbyUyMHNldHxlbnwwfHx8fDE2OTY2MDQ3NjR8MA%26ixlib%3Drb-4.0.jpg&preferredSize=auto",
		title: "Image 1",
		type: ControlType.ResponsiveImage,
	},
	v_aHxy8b0: {
		__defaultAssetReference:
			"data:framer/asset-reference,62fBwAmnlMEZezATDj3tVnxPgbY.jpg?originalFilename=photo-1612043071344-94c20c4c837e%3Fcrop%3Dentropy%26cs%3Dsrgb%26fm%3Djpg%26ixid%3DM3wxMzc5NjJ8MHwxfHNlYXJjaHw3fHxWaWRlbyUyMFN0dWRpb3xlbnwwfHx8fDE2OTY2Njc1NjR8MA%26ixlib%3Drb-4.0.jpg&preferredSize=auto",
		title: "Image 2",
		type: ControlType.ResponsiveImage,
	},
	M9q6OGnh9: {
		__defaultAssetReference:
			"data:framer/asset-reference,xbXkBDo9mvpVFEBpvk41UO4f9RA.jpg?originalFilename=photo-1602261320832-b087fc36979a%3Fcrop%3Dentropy%26cs%3Dsrgb%26fm%3Djpg%26ixid%3DM3wxMzc5NjJ8MHwxfHNlYXJjaHwxMHx8VmlkZW8lMjBzZXR8ZW58MHx8fHwxNjk2NjA0NzY0fDA%26ixlib%3Drb-4.0.jpg&preferredSize=auto",
		title: "Image 3",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(Framerd2ihu3mGR, []);

// virtual:image-slideshow-about-us-page
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8a429189ff65f2fafed7ae45547e59ca6084759351dbe5c21bdecf003cf56825"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ImageSlideshowAboutUsPageFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8a429189ff65f2fafed7ae45547e59ca6084759351dbe5c21bdecf003cf56825"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var image_slideshow_about_us_page_default = ComponentWithRoot;
export { image_slideshow_about_us_page_default as default };
