// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 8a429189ff65f2fa "Shareye Films", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Phone' // Variant
}} Props

 */
import { routes } from "./chunks/chunk-W2AWTVWO.js";

// virtual:links-product
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/8Tk0fPVvZB2SIV7gyMDK/LL15F2tnQVz0ox2luibL/NBTuPFvlD.js
import { jsx as e, jsxs as r } from "react/jsx-runtime";
import {
	addFonts as t,
	addPropertyControls as a,
	ControlType as o,
	cx as i,
	RichText as n,
	SVG as l,
	useLocaleInfo as d,
	useVariantState as m,
	withCSS as f,
} from "unframer";
import {
	LayoutGroup as p,
	motion as s,
	MotionConfigContext as g,
} from "unframer";
import * as h from "react";
var c = ["kp61pjfVI", "yS6mwB6Z5"];
var y = {
	kp61pjfVI: "framer-v-1ovlhd9",
	yS6mwB6Z5: "framer-v-egxmoz",
};
function w(e2, ...r2) {
	let t2 = {};
	return null == r2 || r2.forEach((r3) => r3 && Object.assign(t2, e2[r3])), t2;
}
var b = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var u = ({ value: r2, children: t2 }) => {
	let a2 = h.useContext(g),
		o2 = null != r2 ? r2 : a2.transition,
		i2 = h.useMemo(
			() => ({
				...a2,
				transition: o2,
			}),
			[JSON.stringify(o2)],
		);
	return <g.Provider value={i2}>{t2}</g.Provider>;
};
var v = {
	Desktop: "kp61pjfVI",
	Phone: "yS6mwB6Z5",
};
var k = ({ height: e2, id: r2, width: t2, ...a2 }) => {
	var o2, i2;
	return {
		...a2,
		variant:
			null !==
				(i2 =
					null !== (o2 = v[a2.variant]) && void 0 !== o2 ? o2 : a2.variant) &&
			void 0 !== i2
				? i2
				: "kp61pjfVI",
	};
};
var I = (e2, r2) => r2.join("-") + e2.layoutDependency;
var A = /* @__PURE__ */ h.forwardRef(function (t2, a2) {
	let { activeLocale: o2 } = d(),
		{ style: f2, className: g2, layoutId: x2, variant: v2, ...A2 } = k(t2),
		{
			baseVariant: z2,
			classNames: C2,
			gestureVariant: j,
			setGestureState: B,
			setVariant: Z,
			transition: S,
			variants: P,
		} = m({
			cycleOrder: c,
			defaultVariant: "kp61pjfVI",
			transitions: b,
			variant: v2,
			variantClassNames: y,
		}),
		L = I(t2, P),
		D = h.useRef(null),
		V = h.useId();
	return e(p, {
		id: null != x2 ? x2 : V,
		children: (
			<s.div
				initial={v2}
				animate={P}
				onHoverStart={() =>
					B({
						isHovered: true,
					})
				}
				onHoverEnd={() =>
					B({
						isHovered: false,
					})
				}
				onTapStart={() =>
					B({
						isPressed: true,
					})
				}
				onTap={() =>
					B({
						isPressed: false,
					})
				}
				onTapCancel={() =>
					B({
						isPressed: false,
					})
				}
				className={i("framer-e0gyA", ...[], C2)}
				style={{
					display: "contents",
				}}
			>
				{e(u, {
					value: S,
					children: (
						<s.div
							{...A2}
							className={i("framer-1ovlhd9", g2)}
							data-border={true}
							data-framer-name={"Desktop"}
							layoutDependency={L}
							layoutId={"kp61pjfVI"}
							ref={null != a2 ? a2 : D}
							style={{
								"--border-bottom-width": "1px",
								"--border-color": "rgb(34, 34, 34)",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backgroundColor: "rgb(17, 17, 17)",
								borderBottomLeftRadius: 15,
								borderBottomRightRadius: 15,
								borderTopLeftRadius: 15,
								borderTopRightRadius: 15,
								...f2,
							}}
							variants={{
								yS6mwB6Z5: {
									"--border-bottom-width": "0px",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-top-width": "0px",
									backgroundColor: "rgb(0, 0, 0)",
									borderBottomLeftRadius: 0,
									borderBottomRightRadius: 0,
									borderTopLeftRadius: 0,
									borderTopRightRadius: 0,
								},
							}}
							{...w(
								{
									yS6mwB6Z5: {
										"data-framer-name": "Phone",
									},
								},
								z2,
								j,
							)}
						>
							{"yS6mwB6Z5" === z2 &&
								e(n, {
									__fromCanvasComponent: true,
									children: (
										<h.Fragment>
											<s.p
												style={{
													"--font-selector": "SW50ZXItTWVkaXVt",
													"--framer-font-family":
														'"Inter-Medium", "Inter", "Inter Placeholder", sans-serif',
													"--framer-font-size": "10px",
													"--framer-font-weight": "500",
													"--framer-letter-spacing": "0.05em",
													"--framer-line-height": "1.5em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgba(255, 255, 255, 0.4))",
												}}
											>
												{"PRODUCT"}
											</s.p>
										</h.Fragment>
									),
									className: "framer-1ggfq41",
									fonts: ["Inter-Medium"],
									layoutDependency: L,
									layoutId: "toFcxpGZz",
									style: {
										"--extracted-r6o4lv": "rgba(255, 255, 255, 0.4)",
										"--framer-paragraph-spacing": "0px",
									},
									verticalAlignment: "top",
									withExternalLayout: true,
								})}
							<s.div
								className={"framer-veaejg"}
								data-framer-name={"Item"}
								layoutDependency={L}
								layoutId={"iFXhCOTgf"}
								style={{
									"--border-bottom-width": "0px",
									"--border-color": "rgba(0, 0, 0, 0)",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-style": "solid",
									"--border-top-width": "0px",
								}}
								variants={{
									yS6mwB6Z5: {
										"--border-bottom-width": "1px",
										"--border-color": "rgb(34, 34, 34)",
										"--border-left-width": "0px",
										"--border-right-width": "0px",
										"--border-style": "solid",
										"--border-top-width": "0px",
									},
								}}
								{...w(
									{
										yS6mwB6Z5: {
											"data-border": true,
										},
									},
									z2,
									j,
								)}
							>
								{"yS6mwB6Z5" !== z2 &&
									e(l, {
										className: "framer-ov1ko1",
										"data-framer-name": "Icon",
										layout: "position",
										layoutDependency: L,
										layoutId: "sR3ujzrrb",
										opacity: 1,
										svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 20 20"><g><defs><path d="M 2 4 C 2 2.895 2.895 2 4 2 L 16 2 C 17.105 2 18 2.895 18 4 L 18 16 C 18 17.105 17.105 18 16 18 L 4 18 C 2.895 18 2 17.105 2 16 Z" id="a1004z"></path><clipPath id="a1005z"><use xlink:href="#a1004z"></use></clipPath></defs><use xlink:href="#a1004z" fill="#333" clip-path="url(#a1005z)" stroke-width="2" stroke="#444"></use></g></svg>',
										svgContentId: 1591582209,
										withExternalLayout: true,
									})}
								{e(n, {
									__fromCanvasComponent: true,
									children: (
										<h.Fragment>
											<s.p
												style={{
													"--font-selector": "SW50ZXItTWVkaXVt",
													"--framer-font-family":
														'"Inter-Medium", "Inter", "Inter Placeholder", sans-serif',
													"--framer-font-size": "15px",
													"--framer-font-weight": "500",
													"--framer-letter-spacing": "-0.01em",
													"--framer-line-height": "1.5em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(255, 255, 255))",
												}}
											>
												{"Design"}
											</s.p>
										</h.Fragment>
									),
									className: "framer-176g607",
									fonts: ["Inter-Medium"],
									layoutDependency: L,
									layoutId: "uVhIrKtzd",
									style: {
										"--extracted-r6o4lv": "rgb(255, 255, 255)",
										"--framer-paragraph-spacing": "0px",
									},
									verticalAlignment: "top",
									withExternalLayout: true,
								})}
							</s.div>
							<s.div
								className={"framer-6nay60"}
								data-framer-name={"Item"}
								layoutDependency={L}
								layoutId={"UNqYpXgOT"}
								style={{
									"--border-bottom-width": "0px",
									"--border-color": "rgba(0, 0, 0, 0)",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-style": "solid",
									"--border-top-width": "0px",
								}}
								variants={{
									yS6mwB6Z5: {
										"--border-bottom-width": "1px",
										"--border-color": "rgb(34, 34, 34)",
										"--border-left-width": "0px",
										"--border-right-width": "0px",
										"--border-style": "solid",
										"--border-top-width": "0px",
									},
								}}
								{...w(
									{
										yS6mwB6Z5: {
											"data-border": true,
										},
									},
									z2,
									j,
								)}
							>
								{"yS6mwB6Z5" !== z2 &&
									e(l, {
										className: "framer-1y0ajbr",
										"data-framer-name": "Icon",
										layout: "position",
										layoutDependency: L,
										layoutId: "Q3wDn_sQk",
										opacity: 1,
										svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 20 20"><g><defs><path d="M 1 9.975 C 1 5.004 5.029 0.975 10 0.975 L 10 0.975 C 14.971 0.975 19 5.004 19 9.975 L 19 10.025 C 19 14.996 14.971 19.025 10 19.025 L 10 19.025 C 5.029 19.025 1 14.996 1 10.025 Z" id="a1006z"></path><clipPath id="a1007z"><use xlink:href="#a1006z"></use></clipPath></defs><use xlink:href="#a1006z" fill="#333" clip-path="url(#a1007z)" stroke-width="2" stroke="#444"></use></g></svg>',
										svgContentId: 128669276,
										withExternalLayout: true,
									})}
								{e(n, {
									__fromCanvasComponent: true,
									children: (
										<h.Fragment>
											<s.p
												style={{
													"--font-selector": "SW50ZXItTWVkaXVt",
													"--framer-font-family":
														'"Inter-Medium", "Inter", "Inter Placeholder", sans-serif',
													"--framer-font-size": "15px",
													"--framer-font-weight": "500",
													"--framer-letter-spacing": "-0.01em",
													"--framer-line-height": "1.5em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(255, 255, 255))",
												}}
											>
												{"Content"}
											</s.p>
										</h.Fragment>
									),
									className: "framer-1gq2ffe",
									fonts: ["Inter-Medium"],
									layoutDependency: L,
									layoutId: "CsItxWTlF",
									style: {
										"--extracted-r6o4lv": "rgb(255, 255, 255)",
										"--framer-paragraph-spacing": "0px",
									},
									verticalAlignment: "top",
									withExternalLayout: true,
								})}
							</s.div>
							<s.div
								className={"framer-cgelfi"}
								data-framer-name={"Item"}
								layoutDependency={L}
								layoutId={"vbmJBUWQp"}
								style={{
									"--border-bottom-width": "0px",
									"--border-color": "rgba(0, 0, 0, 0)",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-style": "solid",
									"--border-top-width": "0px",
								}}
								variants={{
									yS6mwB6Z5: {
										"--border-bottom-width": "1px",
										"--border-color": "rgb(34, 34, 34)",
										"--border-left-width": "0px",
										"--border-right-width": "0px",
										"--border-style": "solid",
										"--border-top-width": "0px",
									},
								}}
								{...w(
									{
										yS6mwB6Z5: {
											"data-border": true,
										},
									},
									z2,
									j,
								)}
							>
								{"yS6mwB6Z5" !== z2 &&
									e(l, {
										className: "framer-1hwlmgy",
										"data-framer-name": "Icon",
										layout: "position",
										layoutDependency: L,
										layoutId: "CLekhYJce",
										opacity: 1,
										svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 20 20"><g><defs><path d="M 8.293 2.293 C 9.073 1.016 10.927 1.016 11.707 2.293 L 19.14 14.457 C 19.955 15.79 18.996 17.5 17.434 17.5 L 2.566 17.5 C 1.004 17.5 0.045 15.79 0.86 14.457 Z" id="a1008z"></path><clipPath id="a1009z"><use xlink:href="#a1008z"></use></clipPath></defs><use xlink:href="#a1008z" fill="#333" clip-path="url(#a1009z)" stroke-width="2" stroke="#444"></use></g></svg>',
										svgContentId: 413734896,
										withExternalLayout: true,
									})}
								{e(n, {
									__fromCanvasComponent: true,
									children: (
										<h.Fragment>
											<s.p
												style={{
													"--font-selector": "SW50ZXItTWVkaXVt",
													"--framer-font-family":
														'"Inter-Medium", "Inter", "Inter Placeholder", sans-serif',
													"--framer-font-size": "15px",
													"--framer-font-weight": "500",
													"--framer-letter-spacing": "-0.01em",
													"--framer-line-height": "1.5em",
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(255, 255, 255))",
												}}
											>
												{"Publish"}
											</s.p>
										</h.Fragment>
									),
									className: "framer-1e23fa3",
									fonts: ["Inter-Medium"],
									layoutDependency: L,
									layoutId: "CPpwKMK2K",
									style: {
										"--extracted-r6o4lv": "rgb(255, 255, 255)",
										"--framer-paragraph-spacing": "0px",
									},
									verticalAlignment: "top",
									withExternalLayout: true,
								})}
							</s.div>
						</s.div>
					),
				})}
			</s.div>
		),
	});
});
var z = [
	'.framer-e0gyA [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-e0gyA .framer-elb4se { display: block; }",
	".framer-e0gyA .framer-1ovlhd9 { align-content: start; align-items: start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 5px; height: min-content; justify-content: flex-start; padding: 15px 15px 15px 15px; position: relative; width: 150px; }",
	".framer-e0gyA .framer-1ggfq41 { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-e0gyA .framer-veaejg, .framer-e0gyA .framer-6nay60, .framer-e0gyA .framer-cgelfi { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 15px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px 0px 0px 0px; position: relative; width: 100%; }",
	".framer-e0gyA .framer-ov1ko1, .framer-e0gyA .framer-1y0ajbr, .framer-e0gyA .framer-1hwlmgy { flex: none; height: 20px; position: relative; width: 20px; }",
	".framer-e0gyA .framer-176g607, .framer-e0gyA .framer-1gq2ffe, .framer-e0gyA .framer-1e23fa3 { -webkit-user-select: none; flex: 1 0 0px; height: auto; position: relative; user-select: none; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-e0gyA .framer-1ovlhd9, .framer-e0gyA .framer-veaejg, .framer-e0gyA .framer-6nay60, .framer-e0gyA .framer-cgelfi { gap: 0px; } .framer-e0gyA .framer-1ovlhd9 > * { margin: 0px; margin-bottom: calc(5px / 2); margin-top: calc(5px / 2); } .framer-e0gyA .framer-1ovlhd9 > :first-child { margin-top: 0px; } .framer-e0gyA .framer-1ovlhd9 > :last-child { margin-bottom: 0px; } .framer-e0gyA .framer-veaejg > *, .framer-e0gyA .framer-6nay60 > *, .framer-e0gyA .framer-cgelfi > * { margin: 0px; margin-left: calc(15px / 2); margin-right: calc(15px / 2); } .framer-e0gyA .framer-veaejg > :first-child, .framer-e0gyA .framer-6nay60 > :first-child, .framer-e0gyA .framer-cgelfi > :first-child { margin-left: 0px; } .framer-e0gyA .framer-veaejg > :last-child, .framer-e0gyA .framer-6nay60 > :last-child, .framer-e0gyA .framer-cgelfi > :last-child { margin-right: 0px; } }",
	".framer-e0gyA.framer-v-egxmoz .framer-1ovlhd9 { gap: 0px; padding: 32px 0px 0px 0px; }",
	".framer-e0gyA.framer-v-egxmoz .framer-1ggfq41 { order: 0; }",
	".framer-e0gyA.framer-v-egxmoz .framer-veaejg { height: 56px; order: 1; }",
	".framer-e0gyA.framer-v-egxmoz .framer-6nay60 { height: 56px; order: 2; }",
	".framer-e0gyA.framer-v-egxmoz .framer-cgelfi { height: 56px; order: 3; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-e0gyA.framer-v-egxmoz .framer-1ovlhd9 { gap: 0px; } .framer-e0gyA.framer-v-egxmoz .framer-1ovlhd9 > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-e0gyA.framer-v-egxmoz .framer-1ovlhd9 > :first-child { margin-top: 0px; } .framer-e0gyA.framer-v-egxmoz .framer-1ovlhd9 > :last-child { margin-bottom: 0px; } }",
];
var C = f(A, z, "framer-e0gyA");
var stdin_default = C;
(C.displayName = "Links: Product"),
	(C.defaultProps = {
		height: 108,
		width: 150,
	}),
	a(C, {
		variant: {
			options: ["kp61pjfVI", "yS6mwB6Z5"],
			optionTitles: ["Desktop", "Phone"],
			title: "Variant",
			type: o.Enum,
		},
	}),
	t(C, []);

// virtual:links-product
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8a429189ff65f2fafed7ae45547e59ca6084759351dbe5c21bdecf003cf56825"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders LinksProductFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8a429189ff65f2fafed7ae45547e59ca6084759351dbe5c21bdecf003cf56825"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var links_product_default = ComponentWithRoot;
export { links_product_default as default };
