// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 8a429189ff65f2fa "Shareye Films", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * click?: Function // Click
 * scrollSection?: undefined // Scroll Section
 * scrollSection2?: undefined // Scroll Section 2
}} Props

 */
import { Video } from "./chunks/chunk-U5XUVE5A.js";
import "./chunks/chunk-OHDHQFGI.js";
import { stdin_default } from "./chunks/chunk-SC2IXIR7.js";
import "./chunks/chunk-47KIQF6Z.js";
import { routes } from "./chunks/chunk-W2AWTVWO.js";

// virtual:section-showreel
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/AFYOgWqSq6wooFVTntni/HHy64I5fyFjBpUCxdkBG/gzJHgXTG8.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var RichTextWithFX = withFX(RichText);
var ButtonRoundFonts = getFonts(stdin_default);
var VideoFonts = getFonts(Video);
var MotionDivWithFX = withFX(motion.div);
var serializationHash = "framer-n8hkf";
var variantClassNames = {
	iOopVsPls: "framer-v-pmyxpx",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	click,
	height,
	id,
	scrollSection,
	scrollSection2,
	width,
	...props
}) => {
	return {
		...props,
		Giptc6Pij: scrollSection ?? props.Giptc6Pij,
		gUX8uVBPK: scrollSection2 ?? props.gUX8uVBPK,
		iu_neD1zS: click ?? props.iu_neD1zS,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		iu_neD1zS: iu_neD1zS2,
		Giptc6Pij: Giptc6Pij2,
		gUX8uVBPK: gUX8uVBPK2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "iOopVsPls",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const mWyYPPeu7wrrsmd = activeVariantCallback(async (...args) => {
		if (iu_neD1zS2) {
			const res = await iu_neD1zS2(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.section
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-pmyxpx",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"iOopVsPls"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<motion.div
							className={"framer-194lqnz"}
							layoutDependency={layoutDependency}
							layoutId={"H5BbDPgJC"}
							style={{
								backgroundColor:
									"var(--token-620fac81-7c2e-4342-b93a-72603d1fc89e, rgb(13, 13, 13))",
							}}
						>
							<RichTextWithFX
								__framer__spring={{
									damping: 60,
									delay: 0,
									duration: 0.3,
									ease: [0.44, 0, 0.56, 1],
									mass: 1,
									stiffness: 308,
									type: "spring",
								}}
								__framer__styleTransformEffectEnabled={true}
								__framer__transformTargets={[
									{
										target: {
											opacity: 1,
											rotate: 0,
											rotateX: 0,
											rotateY: 0,
											scale: 1,
											skewX: 0,
											skewY: 0,
											x: 0,
											y: 0,
										},
									},
									{
										ref: Giptc6Pij2,
										target: {
											opacity: 1,
											rotate: 0,
											rotateX: 0,
											rotateY: 0,
											scale: 0.7,
											skewX: 0,
											skewY: 0,
											x: 0,
											y: 0,
										},
									},
								]}
								__framer__transformTrigger={"onScrollTarget"}
								__framer__transformViewportThreshold={1}
								__fromCanvasComponent={true}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-9bvh77"}
								fonts={["GF;Syne-700"]}
								layoutDependency={layoutDependency}
								layoutId={"Fxdf6LAh9"}
								style={{
									"--extracted-r6o4lv": "rgb(255, 255, 255)",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
									transformPerspective: 1200,
								}}
								verticalAlignment={"top"}
								viewBox={"0 0 518 80"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										style={{
											"--font-selector": "R0Y7U3luZS03MDA=",
											"--framer-font-family":
												'"Syne", "Syne Placeholder", sans-serif',
											"--framer-font-size": "80px",
											"--framer-font-weight": "700",
											"--framer-letter-spacing": "-0.05em",
											"--framer-line-height": "1em",
											"--framer-text-color":
												"var(--extracted-r6o4lv, rgb(255, 255, 255))",
										}}
									>
										<motion.span
											data-text-fill={"true"}
											style={{
												backgroundImage:
													"linear-gradient(132deg, var(--token-5e392320-6dc2-4ced-ada4-6b8aba2f2b33, rgb(255, 255, 255)) 11.682368062196925%, rgba(0, 0, 0, 0) 100%)",
											}}
										>
											{"SHOWREEL"}
										</motion.span>
									</motion.p>
								</React.Fragment>
							</RichTextWithFX>
							<motion.div
								className={"framer-8d4d49"}
								data-framer-name={"Overlay"}
								layoutDependency={layoutDependency}
								layoutId={"cSCdIaQ31"}
								style={{
									background:
										"linear-gradient(180deg, rgba(13, 13, 13, 0) 26.775956284153008%, rgb(13, 13, 13) 100%)",
								}}
							/>
							<MotionDivWithFX
								__framer__spring={{
									damping: 39,
									delay: 0,
									duration: 0.3,
									ease: [0.44, 0, 0.56, 1],
									mass: 1,
									stiffness: 114,
									type: "spring",
								}}
								__framer__styleTransformEffectEnabled={true}
								__framer__transformTargets={[
									{
										target: {
											opacity: 1,
											rotate: 0,
											rotateX: 0,
											rotateY: 0,
											scale: 0.1,
											skewX: 0,
											skewY: 0,
											x: 0,
											y: 0,
										},
									},
									{
										ref: gUX8uVBPK2,
										target: {
											opacity: 1,
											rotate: 0,
											rotateX: 0,
											rotateY: 0,
											scale: 1,
											skewX: 0,
											skewY: 0,
											x: 0,
											y: 0,
										},
									},
								]}
								__framer__transformTrigger={"onScrollTarget"}
								__framer__transformViewportThreshold={1}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-tpvi5m"}
								data-framer-name={"Video Container"}
								layoutDependency={layoutDependency}
								layoutId={"mEnhzIUl5"}
								style={{
									borderBottomLeftRadius: 40,
									borderBottomRightRadius: 40,
									borderTopLeftRadius: 40,
									borderTopRightRadius: 40,
									transformPerspective: 1200,
								}}
							>
								<ComponentViewportProvider
									height={136}
									y={(componentViewport?.y || 0) + 0 + 0 + 332}
								>
									<SmartComponentScopedContainer
										className={"framer-1lhvbc1-container"}
										layoutDependency={layoutDependency}
										layoutId={"bk1vWSWS_-container"}
										nodeId={"bk1vWSWS_"}
										rendersWithMotion={true}
										scopeId={"gzJHgXTG8"}
										transformTemplate={transformTemplate1}
									>
										{_jsx(stdin_default, {
											height: "100%",
											id: "bk1vWSWS_",
											layoutId: "bk1vWSWS_",
											mWyYPPeu7: mWyYPPeu7wrrsmd,
											Qv3m015X1: "PLAY SHOWREEL",
											variant: "fNFyT6fqd",
											vKuZZtuTY: true,
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-19exss5-container"}
										isAuthoredByUser={true}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"XxPKdbCMx-container"}
										nodeId={"XxPKdbCMx"}
										rendersWithMotion={true}
										scopeId={"gzJHgXTG8"}
									>
										<Video
											backgroundColor={"rgba(0, 0, 0, 0)"}
											borderRadius={0}
											bottomLeftRadius={0}
											bottomRightRadius={0}
											controls={false}
											height={"100%"}
											id={"XxPKdbCMx"}
											isMixedBorderRadius={false}
											layoutId={"XxPKdbCMx"}
											loop={true}
											muted={true}
											objectFit={"cover"}
											playing={true}
											posterEnabled={false}
											srcFile={
												"https://framerusercontent.com/assets/t3oWwHTiHPdqvISgXglF9dJecA.mp4"
											}
											srcType={"Upload"}
											srcUrl={
												"https://assets.mixkit.co/videos/preview/mixkit-shining-sun-in-the-sky-surrounded-by-moving-clouds-31793-small.mp4"
											}
											startTime={0}
											style={{
												height: "100%",
												width: "100%",
											}}
											topLeftRadius={0}
											topRightRadius={0}
											volume={25}
											width={"100%"}
										/>
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</MotionDivWithFX>
						</motion.div>
					</motion.section>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-n8hkf.framer-8x9oa1, .framer-n8hkf .framer-8x9oa1 { display: block; }",
	".framer-n8hkf.framer-pmyxpx { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 1600px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1200px; }",
	".framer-n8hkf .framer-194lqnz { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 800px; justify-content: center; overflow: visible; padding: 20px; position: sticky; top: 0px; width: 1px; z-index: 1; }",
	".framer-n8hkf .framer-9bvh77 { flex: none; height: auto; left: 0px; position: absolute; right: 0px; top: 0px; white-space: pre; z-index: 2; }",
	".framer-n8hkf .framer-8d4d49 { flex: none; height: 134px; left: calc(50.00000000000002% - 100% / 2); overflow: visible; pointer-events: none; position: absolute; top: -133px; width: 100%; z-index: 1; }",
	".framer-n8hkf .framer-tpvi5m { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 800px; justify-content: center; overflow: hidden; padding: 0px; position: sticky; top: 0px; width: 1px; will-change: var(--framer-will-change-override, transform); z-index: 4; }",
	".framer-n8hkf .framer-1lhvbc1-container { flex: none; height: auto; left: 50%; position: absolute; top: 50%; width: auto; z-index: 1; }",
	".framer-n8hkf .framer-19exss5-container { flex: none; height: 100%; position: relative; width: 100%; }",
];
var FramergzJHgXTG8 = withCSS(Component, css, "framer-n8hkf");
var stdin_default2 = FramergzJHgXTG8;
FramergzJHgXTG8.displayName = "Section - Showreel";
FramergzJHgXTG8.defaultProps = {
	height: 1600,
	width: 1200,
};
addPropertyControls(FramergzJHgXTG8, {
	iu_neD1zS: {
		title: "Click",
		type: ControlType.EventHandler,
	},
	Giptc6Pij: {
		title: "Scroll Section",
		type: ControlType.ScrollSectionRef,
	},
	gUX8uVBPK: {
		title: "Scroll Section 2",
		type: ControlType.ScrollSectionRef,
	},
});
addFonts(
	FramergzJHgXTG8,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Syne",
					source: "google",
					style: "normal",
					uiFamilyName: "Syne",
					url: "https://fonts.gstatic.com/s/syne/v24/8vIS7w4qzmVxsWxjBZRjr0FKM_3fvj6hR47NCV5Z.woff2",
					weight: "700",
				},
			],
		},
		...ButtonRoundFonts,
		...VideoFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:section-showreel
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8a429189ff65f2fafed7ae45547e59ca6084759351dbe5c21bdecf003cf56825"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SectionShowreelFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8a429189ff65f2fafed7ae45547e59ca6084759351dbe5c21bdecf003cf56825"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var section_showreel_default = ComponentWithRoot;
export { section_showreel_default as default };
