// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 8a429189ff65f2fa "Shareye Films", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop - Expanded' | 'Desktop - Collapsed' | 'Phone - Expanded' | 'Phone - Collapsed' // Variant
 * serial?: string // Serial
 * catagory?: string // Catagory
 * description?: string // Description
 * image1?: {src: string, srcSet?: string, alt?: string} // Image 1
 * image2?: {src: string, srcSet?: string, alt?: string} // Image 2
 * image3?: {src: string, srcSet?: string, alt?: string} // Image 3
 * projectLink?: string // Project Link
}} Props

 */
import { stdin_default } from "./chunks/chunk-N6JY7WXA.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-PPTQYH4F.js";
import { className, css, fonts } from "./chunks/chunk-J47HK3IR.js";
import { Icon } from "./chunks/chunk-47KIQF6Z.js";
import { routes } from "./chunks/chunk-W2AWTVWO.js";

// virtual:service-page-category-details
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/iNLIzcVtMiofKV9EJqhz/r0p16FhOBht7UfmoV9Ms/EGhl5RkCf.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts as getFonts2,
	getFontsFromSharedStyle,
	RichText,
	useActiveVariantCallback as useActiveVariantCallback2,
	useComponentViewport,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";

// /:https://framerusercontent.com/modules/qm0kpikAgwDZYJ0UBprY/OHiZ3PnU2jvUWihzisxJ/YXPo0YJtw.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFonts,
	Image,
	useActiveVariantCallback,
	useLocaleInfo,
	useOnVariantChange,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var ButtonRoundFonts = getFonts(stdin_default);
var enabledGestures = {
	k4r30pUuI: {
		hover: true,
	},
	N_IFlfAyq: {
		hover: true,
	},
	X3alJWNDu: {
		hover: true,
	},
};
var cycleOrder = ["k4r30pUuI", "N_IFlfAyq", "X3alJWNDu"];
var variantClassNames = {
	k4r30pUuI: "framer-v-84dsi3",
	N_IFlfAyq: "framer-v-cfabto",
	X3alJWNDu: "framer-v-qhnnwy",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transitions = {
	default: {
		damping: 80,
		delay: 0,
		mass: 2.8,
		stiffness: 362,
		type: "spring",
	},
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var transformTemplate = (_, t) => `translate(-50%, -50%) ${t}`;
var transformTemplate1 = (_, t) => `translateY(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Variant 1": "k4r30pUuI",
	"Variant 2": "N_IFlfAyq",
	"Variant 3": "X3alJWNDu",
};
var getProps = ({
	height,
	id,
	image1,
	image2,
	image3,
	newTab,
	projectLink,
	width,
	...props
}) => {
	var _ref, _ref1, _ref2, _ref3, _humanReadableVariantMap_props_variant, _ref4;
	return {
		...props,
		dM92iMAXW:
			projectLink !== null && projectLink !== void 0
				? projectLink
				: props.dM92iMAXW,
		duKTqhcrf:
			(_ref =
				image1 !== null && image1 !== void 0 ? image1 : props.duKTqhcrf) !==
				null && _ref !== void 0
				? _ref
				: {
						src: "https://framerusercontent.com/images/d6N41UBevEZe6qcpCyi5XKfGs4.jpg?scale-down-to=1024",
						srcSet:
							"https://framerusercontent.com/images/d6N41UBevEZe6qcpCyi5XKfGs4.jpg?scale-down-to=512 512w, https://framerusercontent.com/images/d6N41UBevEZe6qcpCyi5XKfGs4.jpg?scale-down-to=1024 1024w, https://framerusercontent.com/images/d6N41UBevEZe6qcpCyi5XKfGs4.jpg?scale-down-to=2048 2048w, https://framerusercontent.com/images/d6N41UBevEZe6qcpCyi5XKfGs4.jpg?scale-down-to=4096 4096w, https://framerusercontent.com/images/d6N41UBevEZe6qcpCyi5XKfGs4.jpg 5760w",
					},
		M9q6OGnh9:
			(_ref1 =
				image3 !== null && image3 !== void 0 ? image3 : props.M9q6OGnh9) !==
				null && _ref1 !== void 0
				? _ref1
				: {
						src: "https://framerusercontent.com/images/xbXkBDo9mvpVFEBpvk41UO4f9RA.jpg?scale-down-to=1024",
						srcSet:
							"https://framerusercontent.com/images/xbXkBDo9mvpVFEBpvk41UO4f9RA.jpg?scale-down-to=512 512w, https://framerusercontent.com/images/xbXkBDo9mvpVFEBpvk41UO4f9RA.jpg?scale-down-to=1024 1024w, https://framerusercontent.com/images/xbXkBDo9mvpVFEBpvk41UO4f9RA.jpg?scale-down-to=2048 2048w, https://framerusercontent.com/images/xbXkBDo9mvpVFEBpvk41UO4f9RA.jpg 2792w",
					},
		v_aHxy8b0:
			(_ref2 =
				image2 !== null && image2 !== void 0 ? image2 : props.v_aHxy8b0) !==
				null && _ref2 !== void 0
				? _ref2
				: {
						src: "https://framerusercontent.com/images/62fBwAmnlMEZezATDj3tVnxPgbY.jpg?scale-down-to=1024",
						srcSet:
							"https://framerusercontent.com/images/62fBwAmnlMEZezATDj3tVnxPgbY.jpg?scale-down-to=512 512w, https://framerusercontent.com/images/62fBwAmnlMEZezATDj3tVnxPgbY.jpg?scale-down-to=1024 1024w, https://framerusercontent.com/images/62fBwAmnlMEZezATDj3tVnxPgbY.jpg?scale-down-to=2048 2048w, https://framerusercontent.com/images/62fBwAmnlMEZezATDj3tVnxPgbY.jpg?scale-down-to=4096 4096w, https://framerusercontent.com/images/62fBwAmnlMEZezATDj3tVnxPgbY.jpg 7950w",
					},
		v1qXQLzpm:
			(_ref3 =
				newTab !== null && newTab !== void 0 ? newTab : props.v1qXQLzpm) !==
				null && _ref3 !== void 0
				? _ref3
				: true,
		variant:
			(_ref4 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref4 !== void 0
				? _ref4
				: "k4r30pUuI",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale } = useLocaleInfo();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		duKTqhcrf,
		v_aHxy8b0,
		M9q6OGnh9,
		dM92iMAXW,
		v1qXQLzpm,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "k4r30pUuI",
		enabledGestures,
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onAppearyhfoxr = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("N_IFlfAyq"), 2e3);
	});
	const onAppear1q9b8m6 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("X3alJWNDu"), 2e3);
	});
	const onAppeary8dj0y = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("k4r30pUuI"), 2e3);
	});
	useOnVariantChange(baseVariant, {
		ahdOKuYN8: void 0,
		default: onAppearyhfoxr,
		N_IFlfAyq: onAppear1q9b8m6,
		X3alJWNDu: onAppeary8dj0y,
	});
	const isDisplayed = () => {
		if (["N_IFlfAyq-hover", "X3alJWNDu-hover"].includes(gestureVariant))
			return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (gestureVariant === "k4r30pUuI-hover") return false;
		return true;
	};
	const defaultLayoutId = React.useId();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<motion.div
				initial={variant}
				animate={variants}
				onHoverStart={() =>
					setGestureState({
						isHovered: true,
					})
				}
				onHoverEnd={() =>
					setGestureState({
						isHovered: false,
					})
				}
				onTapStart={() =>
					setGestureState({
						isPressed: true,
					})
				}
				onTap={() =>
					setGestureState({
						isPressed: false,
					})
				}
				onTapCancel={() =>
					setGestureState({
						isPressed: false,
					})
				}
				className={cx("framer-8MxlG", classNames)}
				style={{
					display: "contents",
				}}
			>
				<Transition value={transition}>
					<motion.div
						{...restProps}
						className={cx("framer-84dsi3", className3)}
						data-framer-name={"Variant 1"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"k4r30pUuI"}
						ref={ref}
						style={{
							borderBottomLeftRadius: 4,
							borderBottomRightRadius: 4,
							borderTopLeftRadius: 4,
							borderTopRightRadius: 4,
							...style,
						}}
						{...addPropertyOverrides(
							{
								"k4r30pUuI-hover": {
									"data-framer-name": void 0,
								},
								"N_IFlfAyq-hover": {
									"data-framer-name": void 0,
								},
								"X3alJWNDu-hover": {
									"data-framer-name": void 0,
									"data-highlight": void 0,
								},
								N_IFlfAyq: {
									"data-framer-name": "Variant 2",
								},
								X3alJWNDu: {
									"data-framer-name": "Variant 3",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1rh5og8"}
							data-framer-name={"Image Wrapper"}
							layoutDependency={layoutDependency}
							layoutId={"WA7kw2b3y"}
						>
							<motion.div
								className={"framer-1kuyrsd"}
								layoutDependency={layoutDependency}
								layoutId={"K05dLQjD2"}
								style={{
									borderBottomLeftRadius: 20,
									borderBottomRightRadius: 20,
									borderTopLeftRadius: 20,
									borderTopRightRadius: 20,
								}}
							>
								<Image
									background={{
										alt: "",
										fit: "fill",
										sizes: "490px",
										...toResponsiveImage(duKTqhcrf),
									}}
									className={"framer-avet0v"}
									data-framer-name={"Image 1"}
									layoutDependency={layoutDependency}
									layoutId={"AVeOCFohV"}
									style={{
										borderBottomLeftRadius: 20,
										borderBottomRightRadius: 20,
										borderTopLeftRadius: 20,
										borderTopRightRadius: 20,
									}}
									transformTemplate={transformTemplate}
									{...addPropertyOverrides(
										{
											N_IFlfAyq: {
												background: {
													alt: "",
													fit: "fill",
													sizes: "632px",
													...toResponsiveImage(duKTqhcrf),
												},
											},
											X3alJWNDu: {
												background: {
													alt: "",
													fit: "fill",
													sizes: "632px",
													...toResponsiveImage(duKTqhcrf),
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
								{isDisplayed() && (
									<motion.div
										className={"framer-1c5jsc4-container"}
										layoutDependency={layoutDependency}
										layoutId={"wmKVkgRUY-container"}
										style={{
											opacity: 0,
										}}
										transformTemplate={transformTemplate}
										variants={{
											"k4r30pUuI-hover": {
												opacity: 1,
											},
										}}
									>
										{_jsx(stdin_default, {
											height: "100%",
											id: "wmKVkgRUY",
											layoutId: "wmKVkgRUY",
											Qv3m015X1: "PLAY SHOWREEL",
											variant: "wdO2JzPep",
											vKuZZtuTY: v1qXQLzpm,
											width: "100%",
											xNjg5hAFz: dM92iMAXW,
										})}
									</motion.div>
								)}
							</motion.div>
							<motion.div
								className={"framer-uyzejv"}
								layoutDependency={layoutDependency}
								layoutId={"alamtZUxP"}
								style={{
									borderBottomLeftRadius: 20,
									borderBottomRightRadius: 20,
									borderTopLeftRadius: 20,
									borderTopRightRadius: 20,
								}}
							>
								<Image
									background={{
										alt: "",
										fit: "fill",
										sizes: "490px",
										...toResponsiveImage(v_aHxy8b0),
									}}
									className={"framer-1h31ibg"}
									data-framer-name={"Image 2"}
									layoutDependency={layoutDependency}
									layoutId={"CMMeqsovj"}
									style={{
										borderBottomLeftRadius: 20,
										borderBottomRightRadius: 20,
										borderTopLeftRadius: 20,
										borderTopRightRadius: 20,
									}}
									transformTemplate={transformTemplate}
									{...addPropertyOverrides(
										{
											N_IFlfAyq: {
												transformTemplate: transformTemplate1,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
								{isDisplayed1() && (
									<motion.div
										className={"framer-162yh1o-container"}
										layoutDependency={layoutDependency}
										layoutId={"tLxX_GZYj-container"}
										style={{
											opacity: 0,
										}}
										transformTemplate={transformTemplate}
										variants={{
											"N_IFlfAyq-hover": {
												opacity: 1,
											},
										}}
									>
										{_jsx(stdin_default, {
											height: "100%",
											id: "tLxX_GZYj",
											layoutId: "tLxX_GZYj",
											Qv3m015X1: "PLAY SHOWREEL",
											variant: "wdO2JzPep",
											vKuZZtuTY: true,
											width: "100%",
											xNjg5hAFz: dM92iMAXW,
										})}
									</motion.div>
								)}
							</motion.div>
							<motion.div
								className={"framer-1nbydcc"}
								layoutDependency={layoutDependency}
								layoutId={"YZbayIx9W"}
								style={{
									borderBottomLeftRadius: 20,
									borderBottomRightRadius: 20,
									borderTopLeftRadius: 20,
									borderTopRightRadius: 20,
								}}
							>
								<Image
									background={{
										alt: "",
										fit: "fill",
										sizes:
											"calc(max(max(min(588px, 100vw), 0px) / 12, 0px) + 583px)",
										...toResponsiveImage(M9q6OGnh9),
									}}
									className={"framer-skwi6l"}
									data-framer-name={"Image 3"}
									layoutDependency={layoutDependency}
									layoutId={"pDpZDWpHF"}
									style={{
										borderBottomLeftRadius: 20,
										borderBottomRightRadius: 20,
										borderTopLeftRadius: 20,
										borderTopRightRadius: 20,
									}}
									transformTemplate={transformTemplate1}
									{...addPropertyOverrides(
										{
											"X3alJWNDu-hover": {
												transformTemplate: void 0,
											},
											X3alJWNDu: {
												background: {
													alt: "",
													fit: "fill",
													sizes: "max(max(min(588px, 100vw), 0px) / 1.2, 0px)",
													...toResponsiveImage(M9q6OGnh9),
												},
												transformTemplate: void 0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
								{isDisplayed1() && (
									<motion.div
										className={"framer-1k20zgu-container"}
										layoutDependency={layoutDependency}
										layoutId={"jtg7yyjw0-container"}
										style={{
											opacity: 0,
										}}
										transformTemplate={transformTemplate}
										variants={{
											"X3alJWNDu-hover": {
												opacity: 1,
											},
										}}
									>
										{_jsx(stdin_default, {
											height: "100%",
											id: "jtg7yyjw0",
											layoutId: "jtg7yyjw0",
											Qv3m015X1: "PLAY SHOWREEL",
											variant: "wdO2JzPep",
											vKuZZtuTY: true,
											width: "100%",
											xNjg5hAFz: dM92iMAXW,
										})}
									</motion.div>
								)}
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</motion.div>
		</LayoutGroup>
	);
});
var css3 = [
	'.framer-8MxlG [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-8MxlG .framer-1j30zg2 { display: block; }",
	".framer-8MxlG .framer-84dsi3 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 326px; justify-content: flex-end; overflow: hidden; padding: 0px 0px 0px 0px; position: relative; width: 588px; will-change: var(--framer-will-change-override, transform); }",
	".framer-8MxlG .framer-1rh5og8 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 100%; justify-content: center; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: 1px; }",
	".framer-8MxlG .framer-1kuyrsd { flex: 1 0 0px; height: 100%; overflow: hidden; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-8MxlG .framer-avet0v { aspect-ratio: 1.5030674846625767 / 1; flex: none; height: 100%; left: 50%; overflow: hidden; position: absolute; top: 50%; width: var(--framer-aspect-ratio-supported, 490px); will-change: var(--framer-will-change-override, transform); }",
	".framer-8MxlG .framer-1c5jsc4-container, .framer-8MxlG .framer-162yh1o-container, .framer-8MxlG .framer-1k20zgu-container { flex: none; height: auto; left: 50%; position: absolute; top: 50%; width: auto; z-index: 1; }",
	".framer-8MxlG .framer-uyzejv, .framer-8MxlG .framer-1nbydcc { flex: 0.1 0 0px; height: 100%; overflow: hidden; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-8MxlG .framer-1h31ibg { aspect-ratio: 1.5030674846625767 / 1; flex: none; height: 129%; left: 50%; overflow: visible; position: absolute; top: 50%; width: var(--framer-aspect-ratio-supported, 633px); }",
	".framer-8MxlG .framer-skwi6l { aspect-ratio: 1.5030674846625767 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 420px); left: -290px; overflow: visible; position: absolute; right: -292px; top: 50%; }",
	".framer-8MxlG .framer-v-84dsi3 .framer-84dsi3, .framer-8MxlG .framer-v-cfabto .framer-84dsi3, .framer-8MxlG .framer-v-qhnnwy .framer-84dsi3 { cursor: pointer; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-8MxlG .framer-84dsi3, .framer-8MxlG .framer-1rh5og8 { gap: 0px; } .framer-8MxlG .framer-84dsi3 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-8MxlG .framer-84dsi3 > :first-child, .framer-8MxlG .framer-1rh5og8 > :first-child { margin-left: 0px; } .framer-8MxlG .framer-84dsi3 > :last-child, .framer-8MxlG .framer-1rh5og8 > :last-child { margin-right: 0px; } .framer-8MxlG .framer-1rh5og8 > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } }",
	".framer-8MxlG.framer-v-cfabto .framer-1kuyrsd, .framer-8MxlG.framer-v-qhnnwy .framer-1kuyrsd { flex: 0.1 0 0px; }",
	".framer-8MxlG.framer-v-cfabto .framer-avet0v { height: 129%; width: var(--framer-aspect-ratio-supported, 631px); }",
	".framer-8MxlG.framer-v-cfabto .framer-uyzejv, .framer-8MxlG.framer-v-qhnnwy .framer-1nbydcc { flex: 1 0 0px; }",
	".framer-8MxlG.framer-v-cfabto .framer-1h31ibg { height: 100%; left: unset; right: 0px; width: var(--framer-aspect-ratio-supported, 490px); }",
	".framer-8MxlG.framer-v-qhnnwy .framer-avet0v { height: 129%; left: 51%; width: var(--framer-aspect-ratio-supported, 632px); }",
	".framer-8MxlG.framer-v-qhnnwy .framer-skwi6l { aspect-ratio: unset; height: 100%; left: 0px; right: 0px; top: calc(50.00000000000002% - 100% / 2); }",
	".framer-8MxlG.framer-v-84dsi3.hover .framer-1c5jsc4-container, .framer-8MxlG.framer-v-cfabto.hover .framer-162yh1o-container, .framer-8MxlG.framer-v-qhnnwy.hover .framer-1k20zgu-container { z-index: 7; }",
	".framer-8MxlG.framer-v-cfabto.hover .framer-1h31ibg { left: unset; }",
	".framer-8MxlG.framer-v-qhnnwy.hover .framer-skwi6l { aspect-ratio: unset; }",
];
var FramerYXPo0YJtw = withCSS(Component, css3, "framer-8MxlG");
var stdin_default2 = FramerYXPo0YJtw;
FramerYXPo0YJtw.displayName = "Image Slideshow - Category Details";
FramerYXPo0YJtw.defaultProps = {
	height: 326,
	width: 588,
};
addPropertyControls(FramerYXPo0YJtw, {
	variant: {
		options: ["k4r30pUuI", "N_IFlfAyq", "X3alJWNDu"],
		optionTitles: ["Variant 1", "Variant 2", "Variant 3"],
		title: "Variant",
		type: ControlType.Enum,
	},
	duKTqhcrf: {
		__defaultAssetReference:
			"data:framer/asset-reference,d6N41UBevEZe6qcpCyi5XKfGs4.jpg?originalFilename=photo-1497015289639-54688650d173%3Fcrop%3Dentropy%26cs%3Dsrgb%26fm%3Djpg%26ixid%3DM3wxMzc5NjJ8MHwxfHNlYXJjaHwyfHxWaWRlbyUyMHNldHxlbnwwfHx8fDE2OTY2MDQ3NjR8MA%26ixlib%3Drb-4.0.jpg&preferredSize=auto",
		title: "Image 1",
		type: ControlType.ResponsiveImage,
	},
	v_aHxy8b0: {
		__defaultAssetReference:
			"data:framer/asset-reference,62fBwAmnlMEZezATDj3tVnxPgbY.jpg?originalFilename=photo-1612043071344-94c20c4c837e%3Fcrop%3Dentropy%26cs%3Dsrgb%26fm%3Djpg%26ixid%3DM3wxMzc5NjJ8MHwxfHNlYXJjaHw3fHxWaWRlbyUyMFN0dWRpb3xlbnwwfHx8fDE2OTY2Njc1NjR8MA%26ixlib%3Drb-4.0.jpg&preferredSize=auto",
		title: "Image 2",
		type: ControlType.ResponsiveImage,
	},
	M9q6OGnh9: {
		__defaultAssetReference:
			"data:framer/asset-reference,xbXkBDo9mvpVFEBpvk41UO4f9RA.jpg?originalFilename=photo-1602261320832-b087fc36979a%3Fcrop%3Dentropy%26cs%3Dsrgb%26fm%3Djpg%26ixid%3DM3wxMzc5NjJ8MHwxfHNlYXJjaHwxMHx8VmlkZW8lMjBzZXR8ZW58MHx8fHwxNjk2NjA0NzY0fDA%26ixlib%3Drb-4.0.jpg&preferredSize=auto",
		title: "Image 3",
		type: ControlType.ResponsiveImage,
	},
	dM92iMAXW: {
		title: "Project Link",
		type: ControlType.Link,
	},
	v1qXQLzpm: {
		defaultValue: true,
		title: "New Tab",
		type: ControlType.Boolean,
	},
});
addFonts(FramerYXPo0YJtw, [...ButtonRoundFonts]);

// /:https://framerusercontent.com/modules/iNLIzcVtMiofKV9EJqhz/r0p16FhOBht7UfmoV9Ms/EGhl5RkCf.js
var ImageSlideshowCategoryDetailsFonts = getFonts2(stdin_default2);
var PhosphorFonts = getFonts2(Icon);
var enabledGestures2 = {
	wi2qDkgJj: {
		hover: true,
	},
};
var cycleOrder2 = ["Lg1Zenq5X", "wi2qDkgJj", "zT0irbevk", "CiMvFKy7d"];
var serializationHash = "framer-fc9ZM";
var variantClassNames2 = {
	CiMvFKy7d: "framer-v-178e25m",
	Lg1Zenq5X: "framer-v-1qpqfxv",
	wi2qDkgJj: "framer-v-1bbko61",
	zT0irbevk: "framer-v-1qqe8ut",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 205,
	type: "spring",
};
var toResponsiveImage2 = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var transformTemplate12 = (_, t) => `translateY(-50%) ${t}`;
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants = motion2(React2.Fragment);
var humanReadableVariantMap2 = {
	"Desktop - Collapsed": "wi2qDkgJj",
	"Desktop - Expanded": "Lg1Zenq5X",
	"Phone - Collapsed": "CiMvFKy7d",
	"Phone - Expanded": "zT0irbevk",
};
var getProps2 = ({
	catagory,
	description,
	height,
	id,
	image1,
	image2,
	image3,
	projectLink,
	serial,
	width,
	...props
}) => {
	var _ref, _ref1, _humanReadableVariantMap_props_variant, _ref2, _ref3;
	return {
		...props,
		BRPsyl9RH:
			(_ref =
				serial !== null && serial !== void 0 ? serial : props.BRPsyl9RH) !==
				null && _ref !== void 0
				? _ref
				: "01",
		Bu7z7eHlo: image1 !== null && image1 !== void 0 ? image1 : props.Bu7z7eHlo,
		H5PsDbGue:
			(_ref1 =
				catagory !== null && catagory !== void 0
					? catagory
					: props.H5PsDbGue) !== null && _ref1 !== void 0
				? _ref1
				: "Corporate",
		uGIlsRwAH: image3 !== null && image3 !== void 0 ? image3 : props.uGIlsRwAH,
		variant:
			(_ref2 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap2[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref2 !== void 0
				? _ref2
				: "Lg1Zenq5X",
		VdEpnLz0g:
			(_ref3 =
				description !== null && description !== void 0
					? description
					: props.VdEpnLz0g) !== null && _ref3 !== void 0
				? _ref3
				: "We believe in the power of imagination and creative thinking. We strive to infuse innovation and originality into everything we do, producing unique and captivating video content.",
		VPtaTMmsx:
			projectLink !== null && projectLink !== void 0
				? projectLink
				: props.VPtaTMmsx,
		wgvCliqxO: image2 !== null && image2 !== void 0 ? image2 : props.wgvCliqxO,
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo2();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		BRPsyl9RH,
		H5PsDbGue,
		VdEpnLz0g,
		Bu7z7eHlo,
		wgvCliqxO,
		uGIlsRwAH,
		VPtaTMmsx,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		gestureHandlers,
		gestureVariant,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "Lg1Zenq5X",
		enabledGestures: enabledGestures2,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback2(baseVariant);
	const onTapfhiexl = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("wi2qDkgJj");
	});
	const onTap1d485b6 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("Lg1Zenq5X");
	});
	const onTap1iohyd7 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("CiMvFKy7d");
	});
	const onTap1r4hm6k = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("zT0irbevk");
	});
	const ref1 = React2.useRef(null);
	const isDisplayed = () => {
		if (gestureVariant === "wi2qDkgJj-hover") return false;
		if (["wi2qDkgJj", "zT0irbevk", "CiMvFKy7d"].includes(baseVariant))
			return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (gestureVariant === "wi2qDkgJj-hover") return false;
		if (["wi2qDkgJj", "CiMvFKy7d"].includes(baseVariant)) return false;
		return true;
	};
	const defaultLayoutId = React2.useId();
	const sharedStyleClassNames = [className2, className];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup2
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition2 value={transition1}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							serializationHash,
							...sharedStyleClassNames,
							"framer-1qpqfxv",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop - Expanded"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"Lg1Zenq5X"}
						onTap={onTapfhiexl}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								"wi2qDkgJj-hover": {
									"data-framer-name": void 0,
								},
								CiMvFKy7d: {
									"data-framer-name": "Phone - Collapsed",
									onTap: onTap1r4hm6k,
								},
								wi2qDkgJj: {
									"data-framer-name": "Desktop - Collapsed",
									onTap: onTap1d485b6,
								},
								zT0irbevk: {
									"data-framer-name": "Phone - Expanded",
									onTap: onTap1iohyd7,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-1xvspow"}
							layoutDependency={layoutDependency}
							layoutId={"QmhipP9et"}
							style={{
								rotate: 0,
							}}
							variants={{
								"wi2qDkgJj-hover": {
									rotate: 2,
								},
							}}
						>
							{isDisplayed() && (
								<ComponentViewportProvider>
									<motion2.div
										className={"framer-6zysw-container"}
										layoutDependency={layoutDependency}
										layoutId={"UQDdZ2S4R-container"}
									>
										{_jsx2(stdin_default2, {
											dM92iMAXW: VPtaTMmsx,
											duKTqhcrf: toResponsiveImage2(Bu7z7eHlo),
											height: "100%",
											id: "UQDdZ2S4R",
											layoutId: "UQDdZ2S4R",
											M9q6OGnh9: toResponsiveImage2(uGIlsRwAH),
											style: {
												height: "100%",
												width: "100%",
											},
											v_aHxy8b0: toResponsiveImage2(wgvCliqxO),
											v1qXQLzpm: true,
											variant: "k4r30pUuI",
											width: "100%",
										})}
									</motion2.div>
								</ComponentViewportProvider>
							)}
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1cpg24q"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"qbi8TTPh6"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-a3567fc0-2c6f-4fa8-ac8f-89ddd158e98d, rgb(255, 255, 255))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={H5PsDbGue}
								variants={{
									"wi2qDkgJj-hover": {
										"--extracted-r6o4lv":
											"var(--token-8296390c-3e4f-4c48-afd6-ee4e9808dfbe, rgba(255, 255, 255, 0.5))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides2(
									{
										"wi2qDkgJj-hover": {
											children: (
												<React2.Fragment>
													<motion2.p
														className={"framer-styles-preset-fprirg"}
														data-styles-preset={"OjogGp4K9"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-8296390c-3e4f-4c48-afd6-ee4e9808dfbe, rgba(255, 255, 255, 0.5)))",
														}}
													>
														{"Corporate"}
													</motion2.p>
												</React2.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React2.Fragment>
									<motion2.p
										className={"framer-styles-preset-fprirg"}
										data-styles-preset={"OjogGp4K9"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-a3567fc0-2c6f-4fa8-ac8f-89ddd158e98d, rgb(255, 255, 255)))",
										}}
									>
										{"Corporate"}
									</motion2.p>
								</React2.Fragment>
							</RichText>
							{isDisplayed1() && (
								<RichText
									__fromCanvasComponent={true}
									className={"framer-6asksn"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"uZM6IlwLV"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-d9d01f21-7a47-443c-a8bc-56cdb453de6f, rgba(255, 255, 255, 0.8))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={VdEpnLz0g}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.p
											className={"framer-styles-preset-smtg16"}
											data-styles-preset={"DuMLJ2VUN"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-d9d01f21-7a47-443c-a8bc-56cdb453de6f, rgba(255, 255, 255, 0.8)))",
											}}
										>
											{
												"We believe in the power of imagination and creative thinking. We strive to infuse innovation and originality into everything we do, producing unique and captivating video content."
											}
										</motion2.p>
									</React2.Fragment>
								</RichText>
							)}
						</motion2.div>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-nma0ig"}
							fonts={["GF;Syne-700"]}
							layoutDependency={layoutDependency}
							layoutId={"XEXod9RW7"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-8c47652b-dea5-4767-a9f2-5d952dcce49a, rgba(255, 255, 255, 0.3))",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
								opacity: 0.37,
							}}
							text={BRPsyl9RH}
							transformTemplate={transformTemplate12}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides2(
								{
									CiMvFKy7d: {
										children: (
											<React2.Fragment>
												<motion2.p
													style={{
														"--font-selector": "R0Y7U3luZS03MDA=",
														"--framer-font-family":
															'"Syne", "Syne Placeholder", sans-serif',
														"--framer-font-size": "121px",
														"--framer-font-weight": "700",
														"--framer-letter-spacing": "-0.05em",
														"--framer-line-height": "0.4em",
														"--framer-text-alignment": "left",
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-8c47652b-dea5-4767-a9f2-5d952dcce49a, rgba(255, 255, 255, 0.3)))",
													}}
												>
													{"01"}
												</motion2.p>
											</React2.Fragment>
										),
										transformTemplate: void 0,
									},
									zT0irbevk: {
										children: (
											<React2.Fragment>
												<motion2.p
													style={{
														"--font-selector": "R0Y7U3luZS03MDA=",
														"--framer-font-family":
															'"Syne", "Syne Placeholder", sans-serif',
														"--framer-font-size": "121px",
														"--framer-font-weight": "700",
														"--framer-letter-spacing": "-0.05em",
														"--framer-line-height": "0.4em",
														"--framer-text-alignment": "left",
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-8c47652b-dea5-4767-a9f2-5d952dcce49a, rgba(255, 255, 255, 0.3)))",
													}}
												>
													{"01"}
												</motion2.p>
											</React2.Fragment>
										),
										transformTemplate: void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React2.Fragment>
								<motion2.p
									style={{
										"--font-selector": "R0Y7U3luZS03MDA=",
										"--framer-font-family":
											'"Syne", "Syne Placeholder", sans-serif',
										"--framer-font-size": "190px",
										"--framer-font-weight": "700",
										"--framer-letter-spacing": "-0.05em",
										"--framer-line-height": "0.4em",
										"--framer-text-alignment": "left",
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-8c47652b-dea5-4767-a9f2-5d952dcce49a, rgba(255, 255, 255, 0.3)))",
									}}
								>
									{"01"}
								</motion2.p>
							</React2.Fragment>
						</RichText>
						<ComponentViewportProvider>
							<motion2.div
								className={"framer-1715g4m-container"}
								layoutDependency={layoutDependency}
								layoutId={"vbdO8Uh6N-container"}
								style={{
									rotate: -180,
								}}
								variants={{
									"wi2qDkgJj-hover": {
										rotate: 0,
									},
									CiMvFKy7d: {
										rotate: 0,
									},
									wi2qDkgJj: {
										rotate: -90,
									},
								}}
							>
								<Icon
									color={
										"var(--token-d9d01f21-7a47-443c-a8bc-56cdb453de6f, rgba(255, 255, 255, 0.8))"
									}
									height={"100%"}
									iconSearch={"House"}
									iconSelection={"ArrowDown"}
									id={"vbdO8Uh6N"}
									layoutId={"vbdO8Uh6N"}
									mirrored={false}
									selectByList={true}
									style={{
										height: "100%",
										width: "100%",
									}}
									weight={"thin"}
									width={"100%"}
									{...addPropertyOverrides2(
										{
											"wi2qDkgJj-hover": {
												color:
													"var(--token-4fdd7769-e1d0-45b2-8e3d-fe484baba321, rgb(255, 122, 59))",
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</motion2.div>
						</ComponentViewportProvider>
					</motion2.div>
				</Transition2>
			</Variants>
		</LayoutGroup2>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-fc9ZM.framer-svs345, .framer-fc9ZM .framer-svs345 { display: block; }",
	".framer-fc9ZM.framer-1qpqfxv { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 20px; position: relative; width: 1400px; }",
	".framer-fc9ZM .framer-1xvspow { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 13px; height: min-content; justify-content: center; overflow: visible; padding: 50px 50px 30px 110px; position: relative; width: 1px; z-index: 2; }",
	".framer-fc9ZM .framer-6zysw-container { flex: none; height: 210px; position: relative; width: 380px; }",
	".framer-fc9ZM .framer-1cpg24q { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-fc9ZM .framer-6asksn { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 70%; word-break: break-word; word-wrap: break-word; }",
	".framer-fc9ZM .framer-nma0ig { flex: none; height: 100%; left: 0px; position: absolute; top: 50%; white-space: pre; width: auto; z-index: 1; }",
	".framer-fc9ZM .framer-1715g4m-container { flex: none; height: 52px; position: relative; width: 52px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-fc9ZM.framer-1qpqfxv, .framer-fc9ZM .framer-1xvspow { gap: 0px; } .framer-fc9ZM.framer-1qpqfxv > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-fc9ZM.framer-1qpqfxv > :first-child { margin-left: 0px; } .framer-fc9ZM.framer-1qpqfxv > :last-child { margin-right: 0px; } .framer-fc9ZM .framer-1xvspow > * { margin: 0px; margin-bottom: calc(13px / 2); margin-top: calc(13px / 2); } .framer-fc9ZM .framer-1xvspow > :first-child { margin-top: 0px; } .framer-fc9ZM .framer-1xvspow > :last-child { margin-bottom: 0px; } }",
	".framer-fc9ZM.framer-v-1qqe8ut.framer-1qpqfxv { flex-direction: column; justify-content: flex-start; }",
	".framer-fc9ZM.framer-v-1qqe8ut .framer-1xvspow { flex: none; padding: 4px 0px 30px 0px; width: 100%; }",
	".framer-fc9ZM.framer-v-1qqe8ut .framer-6asksn { width: 100%; }",
	".framer-fc9ZM.framer-v-1qqe8ut .framer-nma0ig { height: auto; top: 0px; }",
	".framer-fc9ZM.framer-v-1qqe8ut .framer-1715g4m-container, .framer-fc9ZM.framer-v-178e25m .framer-1715g4m-container { height: 28px; width: 28px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-fc9ZM.framer-v-1qqe8ut.framer-1qpqfxv { gap: 0px; } .framer-fc9ZM.framer-v-1qqe8ut.framer-1qpqfxv > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-fc9ZM.framer-v-1qqe8ut.framer-1qpqfxv > :first-child { margin-top: 0px; } .framer-fc9ZM.framer-v-1qqe8ut.framer-1qpqfxv > :last-child { margin-bottom: 0px; } }",
	".framer-fc9ZM.framer-v-178e25m.framer-1qpqfxv { align-content: flex-start; align-items: flex-start; padding: 20px 0px 20px 20px; }",
	".framer-fc9ZM.framer-v-178e25m .framer-1xvspow { padding: 2px 50px 30px 0px; }",
	".framer-fc9ZM.framer-v-178e25m .framer-nma0ig { height: 101%; top: 0px; }",
	".framer-fc9ZM.framer-v-1bbko61.hover .framer-1xvspow { padding: 50px 50px 30px 130px; }",
	...css2,
	...css,
];
var FramerEGhl5RkCf = withCSS2(Component2, css4, "framer-fc9ZM");
var stdin_default3 = FramerEGhl5RkCf;
FramerEGhl5RkCf.displayName = "Service Page - Category Details";
FramerEGhl5RkCf.defaultProps = {
	height: 460,
	width: 1400,
};
addPropertyControls2(FramerEGhl5RkCf, {
	variant: {
		options: ["Lg1Zenq5X", "wi2qDkgJj", "zT0irbevk", "CiMvFKy7d"],
		optionTitles: [
			"Desktop - Expanded",
			"Desktop - Collapsed",
			"Phone - Expanded",
			"Phone - Collapsed",
		],
		title: "Variant",
		type: ControlType2.Enum,
	},
	BRPsyl9RH: {
		defaultValue: "01",
		displayTextArea: false,
		title: "Serial",
		type: ControlType2.String,
	},
	H5PsDbGue: {
		defaultValue: "Corporate",
		displayTextArea: true,
		title: "Catagory",
		type: ControlType2.String,
	},
	VdEpnLz0g: {
		defaultValue:
			"We believe in the power of imagination and creative thinking. We strive to infuse innovation and originality into everything we do, producing unique and captivating video content.",
		displayTextArea: true,
		title: "Description",
		type: ControlType2.String,
	},
	Bu7z7eHlo: {
		title: "Image 1",
		type: ControlType2.ResponsiveImage,
	},
	wgvCliqxO: {
		title: "Image 2",
		type: ControlType2.ResponsiveImage,
	},
	uGIlsRwAH: {
		title: "Image 3",
		type: ControlType2.ResponsiveImage,
	},
	VPtaTMmsx: {
		title: "Project Link",
		type: ControlType2.Link,
	},
});
addFonts2(
	FramerEGhl5RkCf,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://app.framerstatic.com/Inter-Regular.cyrillic-ext-CFTLRB35.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://app.framerstatic.com/Inter-Regular.cyrillic-KKLZBALH.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://app.framerstatic.com/Inter-Regular.greek-ext-ULEBLIFV.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://app.framerstatic.com/Inter-Regular.greek-IRHSNFQB.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://app.framerstatic.com/Inter-Regular.latin-ext-VZDUGU3Q.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://app.framerstatic.com/Inter-Regular.latin-JLQMKCHE.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://app.framerstatic.com/Inter-Regular.vietnamese-QK7VSWXK.woff2",
					weight: "400",
				},
				{
					family: "Syne",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/syne/v22/8vIS7w4qzmVxsWxjBZRjr0FKM_3fvj6hR47NCV5Z.woff2",
					weight: "700",
				},
			],
		},
		...ImageSlideshowCategoryDetailsFonts,
		...PhosphorFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:service-page-category-details
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "CiMvFKy7d",
	xl: "wi2qDkgJj",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8a429189ff65f2fafed7ae45547e59ca6084759351dbe5c21bdecf003cf56825"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ServicePageCategoryDetailsFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8a429189ff65f2fafed7ae45547e59ca6084759351dbe5c21bdecf003cf56825"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var service_page_category_details_default = ComponentWithRoot;
export { service_page_category_details_default as default };
