// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 8a429189ff65f2fa "Shareye Films", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * name?: string // Name
 * designation?: string // Designation
 * link1?: string // Link 1
 * link2?: string // Link 2
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-SZNAUKB7.js";
import { className, css, fonts } from "./chunks/chunk-PU5SU6N7.js";
import { Icon } from "./chunks/chunk-47KIQF6Z.js";
import { routes } from "./chunks/chunk-W2AWTVWO.js";

// virtual:team-member-card
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/AXxOYw8AnVIqH6HncWtX/5hQRoZyijefnyYtmADoL/IzNbzx2sA.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider as ComponentViewportProvider2,
	ControlType as ControlType2,
	cx as cx2,
	getFonts as getFonts2,
	getFontsFromSharedStyle as getFontsFromSharedStyle2,
	getLoadingLazyAtYPosition,
	Image,
	RichText as RichText2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";

// /:https://framerusercontent.com/modules/LBCyxjOj5uFpNHh9ayeX/rjHRZNPQP4g0KUv2jwds/n6i6RBk5n.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getPropertyControls,
	Link,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var PhosphorFonts = getFonts(Icon);
var PhosphorControls = getPropertyControls(Icon);
var cycleOrder = ["lgILjzb9w", "UnS_oTMTU"];
var serializationHash = "framer-HUHBD";
var variantClassNames = {
	lgILjzb9w: "framer-v-ogw5e5",
	UnS_oTMTU: "framer-v-91mhwd",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 349,
	type: "spring",
};
var transition2 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 300,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Default: "lgILjzb9w",
	Hover: "UnS_oTMTU",
};
var getProps = ({
	height,
	icon,
	id,
	link,
	socialMediaName,
	width,
	...props
}) => {
	var _ref, _ref1, _humanReadableVariantMap_props_variant, _ref2;
	return {
		...props,
		iArpwkBSn:
			(_ref = icon !== null && icon !== void 0 ? icon : props.iArpwkBSn) !==
				null && _ref !== void 0
				? _ref
				: "FacebookLogo",
		saPomcVlj:
			(_ref1 =
				socialMediaName !== null && socialMediaName !== void 0
					? socialMediaName
					: props.saPomcVlj) !== null && _ref1 !== void 0
				? _ref1
				: "Facebook",
		T4czBcC64: link !== null && link !== void 0 ? link : props.T4czBcC64,
		variant:
			(_ref2 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref2 !== void 0
				? _ref2
				: "lgILjzb9w",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		saPomcVlj,
		T4czBcC64,
		iArpwkBSn,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "lgILjzb9w",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onMouseEnter1ifb4gz = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: true,
		});
		setVariant("UnS_oTMTU");
	});
	const onMouseLeaverp4crg = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: false,
		});
		setVariant("lgILjzb9w");
	});
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition
					value={transition1}
					{...addPropertyOverrides(
						{
							UnS_oTMTU: {
								value: transition2,
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<Link href={T4czBcC64}>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(serializationHash, ...sharedStyleClassNames, "framer-ogw5e5", className3, classNames)} framer-d4wmp7`}
							data-border={true}
							data-framer-name={"Default"}
							data-highlight={true}
							layoutDependency={layoutDependency}
							layoutId={"lgILjzb9w"}
							onMouseEnter={onMouseEnter1ifb4gz}
							ref={ref !== null && ref !== void 0 ? ref : ref1}
							style={{
								"--border-bottom-width": "1px",
								"--border-color": "rgba(255, 171, 66, 0)",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								borderBottomLeftRadius: 54,
								borderBottomRightRadius: 54,
								borderTopLeftRadius: 54,
								borderTopRightRadius: 54,
								...style,
							}}
							variants={{
								UnS_oTMTU: {
									"--border-color":
										"var(--token-8296390c-3e4f-4c48-afd6-ee4e9808dfbe, rgba(255, 255, 255, 0.5))",
								},
							}}
							{...addPropertyOverrides(
								{
									UnS_oTMTU: {
										"data-framer-name": "Hover",
										onMouseLeave: onMouseLeaverp4crg,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-b6jh32"}
								layoutDependency={layoutDependency}
								layoutId={"dJF9WpUyA"}
								style={{
									backgroundColor: "rgba(255, 255, 255, 0.07)",
									borderBottomRightRadius: 0,
									borderTopRightRadius: 0,
								}}
								variants={{
									UnS_oTMTU: {
										backgroundColor:
											"var(--token-16cecdcd-c5a5-4884-abaa-e0abd93e3514, rgba(255, 255, 255, 0.1))",
										borderBottomRightRadius: 39,
										borderTopRightRadius: 39,
									},
								}}
							>
								<ComponentViewportProvider>
									<motion.div
										className={"framer-1mqp3w-container"}
										layoutDependency={layoutDependency}
										layoutId={"LIJUj4Ll4-container"}
									>
										<Icon
											color={
												"var(--token-d9d01f21-7a47-443c-a8bc-56cdb453de6f, rgba(255, 255, 255, 0.8))"
											}
											height={"100%"}
											iconSearch={"House"}
											iconSelection={iArpwkBSn}
											id={"LIJUj4Ll4"}
											layoutId={"LIJUj4Ll4"}
											mirrored={false}
											selectByList={true}
											style={{
												height: "100%",
												width: "100%",
											}}
											weight={"duotone"}
											width={"100%"}
											{...addPropertyOverrides(
												{
													UnS_oTMTU: {
														color:
															"var(--token-4fdd7769-e1d0-45b2-8e3d-fe484baba321, rgb(255, 171, 66))",
													},
												},
												baseVariant,
												gestureVariant,
											)}
										/>
									</motion.div>
								</ComponentViewportProvider>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-7qnntl"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"LhFvq1zfY"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={saPomcVlj}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-5vsgqx"}
											data-styles-preset={"urlDCZwpF"}
										>
											{"Facebook"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-17rzrow"}
								layoutDependency={layoutDependency}
								layoutId={"o_xQBsjpL"}
								style={{
									backgroundColor: "rgba(255, 255, 255, 0.07)",
									borderBottomLeftRadius: 0,
									borderBottomRightRadius: 0,
									borderTopLeftRadius: 0,
									borderTopRightRadius: 0,
								}}
								variants={{
									UnS_oTMTU: {
										backgroundColor:
											"var(--token-16cecdcd-c5a5-4884-abaa-e0abd93e3514, rgba(255, 255, 255, 0.1))",
										borderBottomLeftRadius: 39,
										borderBottomRightRadius: 39,
										borderTopLeftRadius: 39,
										borderTopRightRadius: 39,
									},
								}}
							>
								<ComponentViewportProvider>
									<motion.div
										className={"framer-dazx9k-container"}
										layoutDependency={layoutDependency}
										layoutId={"AtrBe71Wf-container"}
										style={{
											rotate: 90,
										}}
										variants={{
											UnS_oTMTU: {
												rotate: 45,
											},
										}}
									>
										<Icon
											color={
												"var(--token-d9d01f21-7a47-443c-a8bc-56cdb453de6f, rgba(255, 255, 255, 0.8))"
											}
											height={"100%"}
											iconSearch={"House"}
											iconSelection={"ArrowUp"}
											id={"AtrBe71Wf"}
											layoutId={"AtrBe71Wf"}
											mirrored={false}
											selectByList={true}
											style={{
												height: "100%",
												width: "100%",
											}}
											weight={"regular"}
											width={"100%"}
											{...addPropertyOverrides(
												{
													UnS_oTMTU: {
														color:
															"var(--token-a3567fc0-2c6f-4fa8-ac8f-89ddd158e98d, rgb(255, 255, 255))",
													},
												},
												baseVariant,
												gestureVariant,
											)}
										/>
									</motion.div>
								</ComponentViewportProvider>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-HUHBD.framer-d4wmp7, .framer-HUHBD .framer-d4wmp7 { display: block; }",
	".framer-HUHBD.framer-ogw5e5 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: 694px; will-change: var(--framer-will-change-override, transform); }",
	".framer-HUHBD .framer-b6jh32 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 33px; justify-content: flex-start; overflow: visible; padding: 30px 20px 30px 20px; position: relative; width: 1px; }",
	".framer-HUHBD .framer-1mqp3w-container { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 28px); position: relative; width: 25px; }",
	".framer-HUHBD .framer-7qnntl { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-HUHBD .framer-17rzrow { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 60px); justify-content: center; overflow: visible; padding: 0px; position: relative; width: 60px; }",
	".framer-HUHBD .framer-dazx9k-container { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 22px); position: relative; width: 20px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-HUHBD.framer-ogw5e5, .framer-HUHBD .framer-b6jh32, .framer-HUHBD .framer-17rzrow { gap: 0px; } .framer-HUHBD.framer-ogw5e5 > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-HUHBD.framer-ogw5e5 > :first-child, .framer-HUHBD .framer-b6jh32 > :first-child { margin-left: 0px; } .framer-HUHBD.framer-ogw5e5 > :last-child, .framer-HUHBD .framer-b6jh32 > :last-child { margin-right: 0px; } .framer-HUHBD .framer-b6jh32 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-HUHBD .framer-17rzrow > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-HUHBD .framer-17rzrow > :first-child { margin-top: 0px; } .framer-HUHBD .framer-17rzrow > :last-child { margin-bottom: 0px; } }",
	".framer-HUHBD.framer-v-91mhwd.framer-ogw5e5 { gap: 12px; padding: 0px 4px 0px 0px; }",
	".framer-HUHBD.framer-v-91mhwd .framer-1mqp3w-container { height: var(--framer-aspect-ratio-supported, 38px); width: 35px; }",
	".framer-HUHBD.framer-v-91mhwd .framer-17rzrow { height: var(--framer-aspect-ratio-supported, 50px); width: 50px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-HUHBD.framer-v-91mhwd.framer-ogw5e5 { gap: 0px; } .framer-HUHBD.framer-v-91mhwd.framer-ogw5e5 > * { margin: 0px; margin-left: calc(12px / 2); margin-right: calc(12px / 2); } .framer-HUHBD.framer-v-91mhwd.framer-ogw5e5 > :first-child { margin-left: 0px; } .framer-HUHBD.framer-v-91mhwd.framer-ogw5e5 > :last-child { margin-right: 0px; } }",
	...css,
	'.framer-HUHBD[data-border="true"]::after, .framer-HUHBD [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var Framern6i6RBk5n = withCSS(Component, css3, "framer-HUHBD");
var stdin_default = Framern6i6RBk5n;
Framern6i6RBk5n.displayName = "Button - Social Media Links";
Framern6i6RBk5n.defaultProps = {
	height: 60,
	width: 694,
};
addPropertyControls(Framern6i6RBk5n, {
	variant: {
		options: ["lgILjzb9w", "UnS_oTMTU"],
		optionTitles: ["Default", "Hover"],
		title: "Variant",
		type: ControlType.Enum,
	},
	saPomcVlj: {
		defaultValue: "Facebook",
		displayTextArea: false,
		title: "Social Media Name",
		type: ControlType.String,
	},
	T4czBcC64: {
		title: "Link",
		type: ControlType.Link,
	},
	iArpwkBSn: (PhosphorControls === null || PhosphorControls === void 0
		? void 0
		: PhosphorControls["iconSelection"]) && {
		...PhosphorControls["iconSelection"],
		defaultValue: "FacebookLogo",
		description: void 0,
		hidden: void 0,
		title: "Icon",
	},
});
addFonts(
	Framern6i6RBk5n,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...PhosphorFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/AXxOYw8AnVIqH6HncWtX/5hQRoZyijefnyYtmADoL/IzNbzx2sA.js
var ButtonSocialMediaLinksFonts = getFonts2(stdin_default);
var serializationHash2 = "framer-POr04";
var variantClassNames2 = {
	eIvyRomZA: "framer-v-1fw4vp3",
};
var transition12 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var getProps2 = ({
	designation,
	height,
	id,
	image,
	link1,
	link2,
	name1,
	width,
	...props
}) => {
	var _ref, _ref1, _ref2;
	return {
		...props,
		cX1MWIkmR:
			(_ref = name1 !== null && name1 !== void 0 ? name1 : props.cX1MWIkmR) !==
				null && _ref !== void 0
				? _ref
				: "John Davis",
		GLryOUcY_: link2 !== null && link2 !== void 0 ? link2 : props.GLryOUcY_,
		gxzeidSGi: link1 !== null && link1 !== void 0 ? link1 : props.gxzeidSGi,
		n4Vv7K1JV:
			(_ref1 =
				designation !== null && designation !== void 0
					? designation
					: props.n4Vv7K1JV) !== null && _ref1 !== void 0
				? _ref1
				: "Creative Director",
		YAwq5kUf7:
			(_ref2 = image !== null && image !== void 0 ? image : props.YAwq5kUf7) !==
				null && _ref2 !== void 0
				? _ref2
				: {
						src: "https://framerusercontent.com/images/w0oSzxhE78SbS84ZLy8UonOJZRE.jpg?scale-down-to=1024",
						srcSet:
							"https://framerusercontent.com/images/w0oSzxhE78SbS84ZLy8UonOJZRE.jpg?scale-down-to=1024 682w,https://framerusercontent.com/images/w0oSzxhE78SbS84ZLy8UonOJZRE.jpg?scale-down-to=2048 1365w,https://framerusercontent.com/images/w0oSzxhE78SbS84ZLy8UonOJZRE.jpg?scale-down-to=4096 2730w,https://framerusercontent.com/images/w0oSzxhE78SbS84ZLy8UonOJZRE.jpg 4160w",
					},
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo2();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		YAwq5kUf7,
		cX1MWIkmR,
		n4Vv7K1JV,
		gxzeidSGi,
		GLryOUcY_,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		defaultVariant: "eIvyRomZA",
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const ref1 = React2.useRef(null);
	const defaultLayoutId = React2.useId();
	const sharedStyleClassNames = [className2, className];
	const componentViewport = useComponentViewport2();
	return (
		<LayoutGroup2
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							serializationHash2,
							...sharedStyleClassNames,
							"framer-1fw4vp3",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"eIvyRomZA"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-16cecdcd-c5a5-4884-abaa-e0abd93e3514, rgba(255, 255, 255, 0.1))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							borderBottomLeftRadius: 20,
							borderBottomRightRadius: 20,
							borderTopLeftRadius: 20,
							borderTopRightRadius: 20,
							...style,
						}}
					>
						<motion2.div
							className={"framer-1kat24w"}
							data-framer-name={"Image Wrapper"}
							layoutDependency={layoutDependency}
							layoutId={"cS9srdvNN"}
							style={{
								borderBottomLeftRadius: 20,
								borderBottomRightRadius: 20,
								borderTopLeftRadius: 20,
								borderTopRightRadius: 20,
							}}
						>
							<Image
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										((componentViewport === null || componentViewport === void 0
											? void 0
											: componentViewport.y) || 0) +
											10 +
											((((componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.height) || 548) -
												30 -
												(Math.max(
													0,
													(((componentViewport === null ||
													componentViewport === void 0
														? void 0
														: componentViewport.height) || 548) -
														30 -
														303) /
														1,
												) *
													1 +
													147 +
													130 +
													26)) /
												2 +
												0 +
												0) +
											(Math.max(
												0,
												(((componentViewport === null ||
												componentViewport === void 0
													? void 0
													: componentViewport.height) || 548) -
													30 -
													303) /
													1,
											) *
												1 *
												0.5000000000000002 -
												((Math.max(
													0,
													(((componentViewport === null ||
													componentViewport === void 0
														? void 0
														: componentViewport.height) || 548) -
														30 -
														303) /
														1,
												) *
													1 -
													0) *
													1) /
													2),
									),
									sizes: `calc(${(componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || "100vw"} - 20px)`,
									...toResponsiveImage(YAwq5kUf7),
								}}
								className={"framer-1nfa93k"}
								data-framer-name={"Image"}
								layoutDependency={layoutDependency}
								layoutId={"RmmSWtaFa"}
							/>
						</motion2.div>
						<motion2.div
							className={"framer-j9dimg"}
							layoutDependency={layoutDependency}
							layoutId={"bi9guNnJ1"}
						>
							<RichText2
								__fromCanvasComponent={true}
								className={"framer-3qptgj"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"ljLY16XhN"}
								style={{
									"--extracted-1eung3n":
										"var(--token-a3567fc0-2c6f-4fa8-ac8f-89ddd158e98d, rgb(255, 255, 255))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={cX1MWIkmR}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React2.Fragment>
									<motion2.h4
										className={"framer-styles-preset-usmfc9"}
										data-styles-preset={"IsgMMPEHU"}
										style={{
											"--framer-text-alignment": "center",
											"--framer-text-color":
												"var(--extracted-1eung3n, var(--token-a3567fc0-2c6f-4fa8-ac8f-89ddd158e98d, rgb(255, 255, 255)))",
										}}
									>
										{"John Davis"}
									</motion2.h4>
								</React2.Fragment>
							</RichText2>
							<RichText2
								__fromCanvasComponent={true}
								className={"framer-r83qb0"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"RiPmUSS9_"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-a3567fc0-2c6f-4fa8-ac8f-89ddd158e98d, rgb(255, 255, 255))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={n4Vv7K1JV}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React2.Fragment>
									<motion2.p
										className={"framer-styles-preset-5vsgqx"}
										data-styles-preset={"urlDCZwpF"}
										style={{
											"--framer-text-alignment": "center",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-a3567fc0-2c6f-4fa8-ac8f-89ddd158e98d, rgb(255, 255, 255)))",
										}}
									>
										{"Creative Director"}
									</motion2.p>
								</React2.Fragment>
							</RichText2>
						</motion2.div>
						<motion2.div
							className={"framer-10ju4fj"}
							layoutDependency={layoutDependency}
							layoutId={"vgXdF6m98"}
						>
							<ComponentViewportProvider2
								height={60}
								width={`calc(${(componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || "100vw"} - 20px)`}
								y={
									((componentViewport === null || componentViewport === void 0
										? void 0
										: componentViewport.y) || 0) +
									10 +
									((((componentViewport === null || componentViewport === void 0
										? void 0
										: componentViewport.height) || 548) -
										30 -
										(Math.max(
											0,
											(((componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.height) || 548) -
												30 -
												303) /
												1,
										) *
											1 +
											147 +
											130 +
											26)) /
										2 +
										(Math.max(
											0,
											(((componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.height) || 548) -
												30 -
												303) /
												1,
										) *
											1 +
											147) +
										26) +
									0 +
									0
								}
							>
								<motion2.div
									className={"framer-12nbpgx-container"}
									layoutDependency={layoutDependency}
									layoutId={"dArLkVRGF-container"}
								>
									{_jsx2(stdin_default, {
										height: "100%",
										iArpwkBSn: "FacebookLogo",
										id: "dArLkVRGF",
										layoutId: "dArLkVRGF",
										saPomcVlj: "Facebook",
										style: {
											height: "100%",
											width: "100%",
										},
										T4czBcC64: gxzeidSGi,
										variant: "lgILjzb9w",
										width: "100%",
									})}
								</motion2.div>
							</ComponentViewportProvider2>
							<ComponentViewportProvider2
								height={60}
								width={`calc(${(componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || "100vw"} - 20px)`}
								y={
									((componentViewport === null || componentViewport === void 0
										? void 0
										: componentViewport.y) || 0) +
									10 +
									((((componentViewport === null || componentViewport === void 0
										? void 0
										: componentViewport.height) || 548) -
										30 -
										(Math.max(
											0,
											(((componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.height) || 548) -
												30 -
												303) /
												1,
										) *
											1 +
											147 +
											130 +
											26)) /
										2 +
										(Math.max(
											0,
											(((componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.height) || 548) -
												30 -
												303) /
												1,
										) *
											1 +
											147) +
										26) +
									0 +
									70
								}
							>
								<motion2.div
									className={"framer-8rrw7m-container"}
									layoutDependency={layoutDependency}
									layoutId={"a0RWJUHTc-container"}
								>
									{_jsx2(stdin_default, {
										height: "100%",
										iArpwkBSn: "LinkedinLogo",
										id: "a0RWJUHTc",
										layoutId: "a0RWJUHTc",
										saPomcVlj: "Linkedin",
										style: {
											height: "100%",
											width: "100%",
										},
										T4czBcC64: GLryOUcY_,
										variant: "lgILjzb9w",
										width: "100%",
									})}
								</motion2.div>
							</ComponentViewportProvider2>
						</motion2.div>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-POr04.framer-1xuj7vy, .framer-POr04 .framer-1xuj7vy { display: block; }",
	".framer-POr04.framer-1fw4vp3 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 13px; height: 548px; justify-content: center; overflow: hidden; padding: 10px 10px 20px 10px; position: relative; width: 392px; will-change: var(--framer-will-change-override, transform); }",
	".framer-POr04 .framer-1kat24w { flex: 1 0 0px; height: 1px; overflow: hidden; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-POr04 .framer-1nfa93k { flex: none; height: 100%; left: calc(49.89561586638833% - 100% / 2); overflow: hidden; position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; }",
	".framer-POr04 .framer-j9dimg { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px 10px 0px 10px; position: relative; width: 100%; }",
	".framer-POr04 .framer-3qptgj, .framer-POr04 .framer-r83qb0 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-POr04 .framer-10ju4fj { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-POr04 .framer-12nbpgx-container, .framer-POr04 .framer-8rrw7m-container { flex: none; height: 60px; position: relative; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-POr04.framer-1fw4vp3, .framer-POr04 .framer-j9dimg, .framer-POr04 .framer-10ju4fj { gap: 0px; } .framer-POr04.framer-1fw4vp3 > * { margin: 0px; margin-bottom: calc(13px / 2); margin-top: calc(13px / 2); } .framer-POr04.framer-1fw4vp3 > :first-child, .framer-POr04 .framer-j9dimg > :first-child, .framer-POr04 .framer-10ju4fj > :first-child { margin-top: 0px; } .framer-POr04.framer-1fw4vp3 > :last-child, .framer-POr04 .framer-j9dimg > :last-child, .framer-POr04 .framer-10ju4fj > :last-child { margin-bottom: 0px; } .framer-POr04 .framer-j9dimg > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-POr04 .framer-10ju4fj > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } }",
	...css2,
	...css,
	'.framer-POr04[data-border="true"]::after, .framer-POr04 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerIzNbzx2sA = withCSS2(Component2, css4, "framer-POr04");
var stdin_default2 = FramerIzNbzx2sA;
FramerIzNbzx2sA.displayName = "Team Member - Card";
FramerIzNbzx2sA.defaultProps = {
	height: 548,
	width: 392,
};
addPropertyControls2(FramerIzNbzx2sA, {
	YAwq5kUf7: {
		__defaultAssetReference:
			"data:framer/asset-reference,w0oSzxhE78SbS84ZLy8UonOJZRE.jpg?originalFilename=photo-1600603405959-6d623e92445c%3Fcrop%3Dentropy%26cs%3Dsrgb%26fm%3Djpg%26ixid%3DM3wxMzc5NjJ8MHwxfHNlYXJjaHwzNXx8bWFufGVufDB8fHx8MTY5Njc5ODEwM3ww%26ixlib%3Drb-4.0.jpg&preferredSize=auto",
		title: "Image",
		type: ControlType2.ResponsiveImage,
	},
	cX1MWIkmR: {
		defaultValue: "John Davis",
		displayTextArea: true,
		title: "Name",
		type: ControlType2.String,
	},
	n4Vv7K1JV: {
		defaultValue: "Creative Director",
		displayTextArea: true,
		title: "Designation",
		type: ControlType2.String,
	},
	gxzeidSGi: {
		title: "Link 1",
		type: ControlType2.Link,
	},
	GLryOUcY_: {
		title: "Link 2",
		type: ControlType2.Link,
	},
});
addFonts2(
	FramerIzNbzx2sA,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ButtonSocialMediaLinksFonts,
		...getFontsFromSharedStyle2(fonts2),
		...getFontsFromSharedStyle2(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:team-member-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8a429189ff65f2fafed7ae45547e59ca6084759351dbe5c21bdecf003cf56825"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TeamMemberCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8a429189ff65f2fafed7ae45547e59ca6084759351dbe5c21bdecf003cf56825"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var team_member_card_default = ComponentWithRoot;
export { team_member_card_default as default };
