// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 8a429189ff65f2fa "Shareye Films", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Hover' // Variant
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * quote?: string // Quote
 * clientName?: string // Client Name
 * company?: string // Company
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-ULIILFHK.js";
import { className, css, fonts } from "./chunks/chunk-PPTQYH4F.js";
import { Icon } from "./chunks/chunk-47KIQF6Z.js";
import { routes } from "./chunks/chunk-W2AWTVWO.js";

// virtual:testimonial-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/vesvGHn3ykwxCl2ktuPZ/plsNMC6tim0cUX7ODYWZ/KtpKWPd0G.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	Image,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var PhosphorFonts = getFonts(Icon);
var cycleOrder = ["dizu1qwCu", "IsHHPhWzy"];
var serializationHash = "framer-KYOzX";
var variantClassNames = {
	dizu1qwCu: "framer-v-jkcni0",
	IsHHPhWzy: "framer-v-8f53uf",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 270,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var humanReadableVariantMap = {
	Default: "dizu1qwCu",
	Hover: "IsHHPhWzy",
};
var getProps = ({
	clientName,
	company,
	height,
	id,
	image,
	quote,
	width,
	...props
}) => {
	var _ref, _humanReadableVariantMap_props_variant, _ref1, _ref2, _ref3, _ref4;
	return {
		...props,
		TYrIC1xIe:
			(_ref = image !== null && image !== void 0 ? image : props.TYrIC1xIe) !==
				null && _ref !== void 0
				? _ref
				: {
						src: "https://framerusercontent.com/images/or0Wlg5UKFRZGfVPFnLR5bath6I.svg",
					},
		variant:
			(_ref1 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref1 !== void 0
				? _ref1
				: "dizu1qwCu",
		XQebMLGjf:
			(_ref2 =
				company !== null && company !== void 0 ? company : props.XQebMLGjf) !==
				null && _ref2 !== void 0
				? _ref2
				: "Chief Marketing Officer, HorizonTech Solutions",
		xWK1trTmf:
			(_ref3 =
				clientName !== null && clientName !== void 0
					? clientName
					: props.xWK1trTmf) !== null && _ref3 !== void 0
				? _ref3
				: "Sarah Adams",
		zid21k45x:
			(_ref4 = quote !== null && quote !== void 0 ? quote : props.zid21k45x) !==
				null && _ref4 !== void 0
				? _ref4
				: "We are thrilled with our new corporate videos. The team was incredibly calm, patient, and fostered a pleasant atmosphere. Everything came together seamlessly! We wholeheartedly endorse and would recommend them anytime.",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		TYrIC1xIe,
		zid21k45x,
		xWK1trTmf,
		XQebMLGjf,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureHandlers,
		gestureVariant,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "dizu1qwCu",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onMouseEnter3nc5qe = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: true,
		});
		await delay(() => setVariant("IsHHPhWzy"), 100);
	});
	const onMouseLeave4f2hjs = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: false,
		});
		await delay(() => setVariant("dizu1qwCu"), 100);
	});
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className, className2];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-jkcni0",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Default"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"dizu1qwCu"}
						onMouseEnter={onMouseEnter3nc5qe}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-8c47652b-dea5-4767-a9f2-5d952dcce49a, rgba(255, 255, 255, 0.3))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backdropFilter: "blur(8px)",
							background:
								"linear-gradient(95deg, rgba(255, 255, 255, 0.08) 2.210024196147939%, hsla(0, 0%, 100%, 0) 100%)",
							borderBottomLeftRadius: 40,
							borderBottomRightRadius: 40,
							borderTopLeftRadius: 40,
							borderTopRightRadius: 40,
							WebkitBackdropFilter: "blur(8px)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								IsHHPhWzy: {
									"data-framer-name": "Hover",
									onMouseEnter: void 0,
									onMouseLeave: onMouseLeave4f2hjs,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1lbv3kr"}
							layoutDependency={layoutDependency}
							layoutId={"tuwP5ZCso"}
						>
							<Image
								background={{
									alt: "",
									fit: "fit",
									sizes: "172px",
									...toResponsiveImage(TYrIC1xIe),
									...{
										positionX: "left",
										positionY: "center",
									},
								}}
								className={"framer-11zp32l"}
								layoutDependency={layoutDependency}
								layoutId={"AxPTxMxyY"}
							/>
						</motion.div>
						<motion.div
							className={"framer-1joqzw9"}
							layoutDependency={layoutDependency}
							layoutId={"a1HJ0DaWI"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-wp93yv"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"wCWyHiMGR"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={zid21k45x}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-fprirg"}
										data-styles-preset={"OjogGp4K9"}
									>
										<motion.span
											data-text-fill={"true"}
											style={{
												backgroundImage:
													"linear-gradient(107deg, var(--token-a3567fc0-2c6f-4fa8-ac8f-89ddd158e98d, rgb(255, 255, 255)) 0%, var(--token-d9d01f21-7a47-443c-a8bc-56cdb453de6f, rgba(255, 255, 255, 0.8)) 100%)",
											}}
										>
											{
												"We are thrilled with our new corporate videos. The team was incredibly calm, patient, and fostered a pleasant atmosphere. Everything came together seamlessly! We wholeheartedly endorse and would recommend them anytime."
											}
										</motion.span>
									</motion.p>
								</React.Fragment>
							</RichText>
							<ComponentViewportProvider>
								<motion.div
									className={"framer-yoh4i0-container"}
									layoutDependency={layoutDependency}
									layoutId={"QQWNhn6Ue-container"}
								>
									<Icon
										color={
											"var(--token-a3567fc0-2c6f-4fa8-ac8f-89ddd158e98d, rgb(255, 255, 255))"
										}
										height={"100%"}
										iconSearch={"House"}
										iconSelection={"Quotes"}
										id={"QQWNhn6Ue"}
										layoutId={"QQWNhn6Ue"}
										mirrored={false}
										selectByList={true}
										style={{
											height: "100%",
											width: "100%",
										}}
										weight={"fill"}
										width={"100%"}
									/>
								</motion.div>
							</ComponentViewportProvider>
						</motion.div>
						<motion.div
							className={"framer-11pl6e7"}
							layoutDependency={layoutDependency}
							layoutId={"Pfy8stEMx"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-prb8w4"}
								fonts={["GF;Syne-regular"]}
								layoutDependency={layoutDependency}
								layoutId={"Yxy9TDfD4"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-d9d01f21-7a47-443c-a8bc-56cdb453de6f, rgba(255, 255, 255, 0.8))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={xWK1trTmf}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										style={{
											"--font-selector": "R0Y7U3luZS1yZWd1bGFy",
											"--framer-font-family":
												'"Syne", "Syne Placeholder", sans-serif',
											"--framer-font-size": "20px",
											"--framer-letter-spacing": "-0.08em",
											"--framer-line-height": "1.5em",
											"--framer-text-alignment": "left",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-d9d01f21-7a47-443c-a8bc-56cdb453de6f, rgba(255, 255, 255, 0.8)))",
											"--framer-text-transform": "uppercase",
										}}
									>
										{"Sarah Adams"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-fhuua2"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"DaFz3G6ot"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-8296390c-3e4f-4c48-afd6-ee4e9808dfbe, rgba(255, 255, 255, 0.5))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={XQebMLGjf}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-g6micz"}
										data-styles-preset={"iLvBdfOs8"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-8296390c-3e4f-4c48-afd6-ee4e9808dfbe, rgba(255, 255, 255, 0.5)))",
										}}
									>
										{"Chief Marketing Officer, HorizonTech Solutions"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						<motion.div
							className={"framer-e3m1f"}
							layoutDependency={layoutDependency}
							layoutId={"QpaHgpxAe"}
							style={{
								backdropFilter: "blur(5px)",
								rotate: 9,
								WebkitBackdropFilter: "blur(5px)",
							}}
						>
							<motion.div
								className={"framer-qzlp2h"}
								layoutDependency={layoutDependency}
								layoutId={"p2_fXBl8b"}
								style={{
									backdropFilter: "blur(0px)",
									backgroundColor: "rgb(255, 255, 255)",
									opacity: 0.12,
									WebkitBackdropFilter: "blur(0px)",
								}}
							/>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-KYOzX.framer-6s41k2, .framer-KYOzX .framer-6s41k2 { display: block; }",
	".framer-KYOzX.framer-jkcni0 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 25px; height: min-content; justify-content: center; overflow: hidden; padding: 50px 40px 70px 40px; position: relative; width: 926px; will-change: var(--framer-will-change-override, transform); }",
	".framer-KYOzX .framer-1lbv3kr { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 88px; justify-content: center; overflow: hidden; padding: 0px; pointer-events: none; position: relative; width: 172px; }",
	".framer-KYOzX .framer-11zp32l { flex: none; height: 100%; overflow: visible; position: relative; width: 100%; }",
	".framer-KYOzX .framer-1joqzw9 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 11px; height: min-content; justify-content: center; mix-blend-mode: difference; overflow: visible; padding: 0px; pointer-events: none; position: relative; width: 100%; }",
	".framer-KYOzX .framer-wp93yv { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-KYOzX .framer-yoh4i0-container { flex: none; height: 60px; position: relative; width: 60px; }",
	".framer-KYOzX .framer-11pl6e7 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; pointer-events: none; position: relative; width: 100%; }",
	".framer-KYOzX .framer-prb8w4, .framer-KYOzX .framer-fhuua2 { -webkit-user-select: none; flex: none; height: auto; pointer-events: none; position: relative; user-select: none; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-KYOzX .framer-e3m1f { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 180%; justify-content: center; left: -288px; overflow: visible; padding: 0px; pointer-events: none; position: absolute; top: calc(45.820895522388085% - 179.8507462686567% / 2); width: 169px; }",
	".framer-KYOzX .framer-qzlp2h { flex: none; height: 100%; left: calc(50.11389521640094% - 100% / 2); overflow: hidden; position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; z-index: 1; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-KYOzX.framer-jkcni0, .framer-KYOzX .framer-1lbv3kr, .framer-KYOzX .framer-1joqzw9, .framer-KYOzX .framer-11pl6e7, .framer-KYOzX .framer-e3m1f { gap: 0px; } .framer-KYOzX.framer-jkcni0 > * { margin: 0px; margin-bottom: calc(25px / 2); margin-top: calc(25px / 2); } .framer-KYOzX.framer-jkcni0 > :first-child, .framer-KYOzX .framer-1joqzw9 > :first-child, .framer-KYOzX .framer-11pl6e7 > :first-child { margin-top: 0px; } .framer-KYOzX.framer-jkcni0 > :last-child, .framer-KYOzX .framer-1joqzw9 > :last-child, .framer-KYOzX .framer-11pl6e7 > :last-child { margin-bottom: 0px; } .framer-KYOzX .framer-1lbv3kr > *, .framer-KYOzX .framer-e3m1f > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-KYOzX .framer-1lbv3kr > :first-child, .framer-KYOzX .framer-e3m1f > :first-child { margin-left: 0px; } .framer-KYOzX .framer-1lbv3kr > :last-child, .framer-KYOzX .framer-e3m1f > :last-child { margin-right: 0px; } .framer-KYOzX .framer-1joqzw9 > * { margin: 0px; margin-bottom: calc(11px / 2); margin-top: calc(11px / 2); } .framer-KYOzX .framer-11pl6e7 > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } }",
	".framer-KYOzX.framer-v-8f53uf .framer-e3m1f { height: 120%; left: unset; right: -281px; top: -74px; }",
	...css,
	...css2,
	'.framer-KYOzX[data-border="true"]::after, .framer-KYOzX [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerKtpKWPd0G = withCSS(Component, css3, "framer-KYOzX");
var stdin_default = FramerKtpKWPd0G;
FramerKtpKWPd0G.displayName = "Testimonial - Card";
FramerKtpKWPd0G.defaultProps = {
	height: 471,
	width: 926,
};
addPropertyControls(FramerKtpKWPd0G, {
	variant: {
		options: ["dizu1qwCu", "IsHHPhWzy"],
		optionTitles: ["Default", "Hover"],
		title: "Variant",
		type: ControlType.Enum,
	},
	TYrIC1xIe: {
		__defaultAssetReference:
			"data:framer/asset-reference,or0Wlg5UKFRZGfVPFnLR5bath6I.svg?originalFilename=logoipsum-220.svg&preferredSize=auto",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	zid21k45x: {
		defaultValue:
			"We are thrilled with our new corporate videos. The team was incredibly calm, patient, and fostered a pleasant atmosphere. Everything came together seamlessly! We wholeheartedly endorse and would recommend them anytime.",
		displayTextArea: true,
		title: "Quote",
		type: ControlType.String,
	},
	xWK1trTmf: {
		defaultValue: "Sarah Adams",
		displayTextArea: false,
		title: "Client Name",
		type: ControlType.String,
	},
	XQebMLGjf: {
		defaultValue: "Chief Marketing Officer, HorizonTech Solutions",
		displayTextArea: false,
		title: "Company",
		type: ControlType.String,
	},
});
addFonts(
	FramerKtpKWPd0G,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://app.framerstatic.com/Inter-Regular.cyrillic-ext-CFTLRB35.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://app.framerstatic.com/Inter-Regular.cyrillic-KKLZBALH.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://app.framerstatic.com/Inter-Regular.greek-ext-ULEBLIFV.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://app.framerstatic.com/Inter-Regular.greek-IRHSNFQB.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://app.framerstatic.com/Inter-Regular.latin-ext-VZDUGU3Q.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://app.framerstatic.com/Inter-Regular.latin-JLQMKCHE.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://app.framerstatic.com/Inter-Regular.vietnamese-QK7VSWXK.woff2",
					weight: "400",
				},
				{
					family: "Syne",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/syne/v22/8vIS7w4qzmVxsWxjBZRjr0FKM_04uT6hR47NCV5Z.woff2",
					weight: "400",
				},
			],
		},
		...PhosphorFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:testimonial-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8a429189ff65f2fafed7ae45547e59ca6084759351dbe5c21bdecf003cf56825"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TestimonialCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8a429189ff65f2fafed7ae45547e59ca6084759351dbe5c21bdecf003cf56825"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var testimonial_card_default = ComponentWithRoot;
export { testimonial_card_default as default };
