// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 8a429189ff65f2fa "Shareye Films", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' | 'Variant 3' // Variant
 * hover?: Function // Hover
}} Props

 */
import {
	Icon,
	NullState,
	defaultEvents,
	useIconSelection,
} from "./chunks/chunk-47KIQF6Z.js";
import { routes } from "./chunks/chunk-W2AWTVWO.js";

// virtual:toast
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/jrem5R0H3AHOGveZnbWb/7nqn8ODInZcDBaJcezxk/aq1Wy0p__.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx,
	getFonts,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import { LayoutGroup, motion as motion2, MotionConfigContext } from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/tYScH7LTqUtz5KUaUAYP/CAjjxbTJBxHwH1MagCef/Phosphor.js
import { jsx as _jsx } from "react/jsx-runtime";
import * as React from "react";
import { useState, useEffect, useRef } from "react";
import { addPropertyControls, ControlType, RenderTarget } from "unframer";
import { motion } from "unframer";

// /:https://framerusercontent.com/modules/Qc8yuHkQmGO0kFiSWbkX/i6WSiDLftYVS2GvUElTz/House.js
var Component;
var House_default = (React3) => {
	if (!Component) {
		const weights = /* @__PURE__ */ new Map([
			[
				"bold",
				/* @__PURE__ */ React3.createElement(
					React3.Fragment,
					null,
					/* @__PURE__ */ React3.createElement("path", {
						d: "M221.56,100.85,141.61,25.38l-.16-.15a19.93,19.93,0,0,0-26.91,0l-.17.15L34.44,100.85A20.07,20.07,0,0,0,28,115.55V208a20,20,0,0,0,20,20H96a20,20,0,0,0,20-20V164h24v44a20,20,0,0,0,20,20h48a20,20,0,0,0,20-20V115.55A20.07,20.07,0,0,0,221.56,100.85ZM204,204H164V160a20,20,0,0,0-20-20H112a20,20,0,0,0-20,20v44H52V117.28l76-71.75,76,71.75Z",
					}),
				),
			],
			[
				"duotone",
				/* @__PURE__ */ React3.createElement(
					React3.Fragment,
					null,
					/* @__PURE__ */ React3.createElement("path", {
						d: "M216,115.54V208a8,8,0,0,1-8,8H160a8,8,0,0,1-8-8V160a8,8,0,0,0-8-8H112a8,8,0,0,0-8,8v48a8,8,0,0,1-8,8H48a8,8,0,0,1-8-8V115.54a8,8,0,0,1,2.62-5.92l80-75.54a8,8,0,0,1,10.77,0l80,75.54A8,8,0,0,1,216,115.54Z",
						opacity: "0.2",
					}),
					/* @__PURE__ */ React3.createElement("path", {
						d: "M218.83,103.77l-80-75.48a1.14,1.14,0,0,1-.11-.11,16,16,0,0,0-21.53,0l-.11.11L37.17,103.77A16,16,0,0,0,32,115.55V208a16,16,0,0,0,16,16H96a16,16,0,0,0,16-16V160h32v48a16,16,0,0,0,16,16h48a16,16,0,0,0,16-16V115.55A16,16,0,0,0,218.83,103.77ZM208,208H160V160a16,16,0,0,0-16-16H112a16,16,0,0,0-16,16v48H48V115.55l.11-.1L128,40l79.9,75.43.11.1Z",
					}),
				),
			],
			[
				"fill",
				/* @__PURE__ */ React3.createElement(
					React3.Fragment,
					null,
					/* @__PURE__ */ React3.createElement("path", {
						d: "M224,115.55V208a16,16,0,0,1-16,16H168a16,16,0,0,1-16-16V168a8,8,0,0,0-8-8H112a8,8,0,0,0-8,8v40a16,16,0,0,1-16,16H48a16,16,0,0,1-16-16V115.55a16,16,0,0,1,5.17-11.78l80-75.48.11-.11a16,16,0,0,1,21.53,0,1.14,1.14,0,0,0,.11.11l80,75.48A16,16,0,0,1,224,115.55Z",
					}),
				),
			],
			[
				"light",
				/* @__PURE__ */ React3.createElement(
					React3.Fragment,
					null,
					/* @__PURE__ */ React3.createElement("path", {
						d: "M217.47,105.24l-80-75.5-.09-.08a13.94,13.94,0,0,0-18.83,0l-.09.08-80,75.5A14,14,0,0,0,34,115.55V208a14,14,0,0,0,14,14H96a14,14,0,0,0,14-14V160a2,2,0,0,1,2-2h32a2,2,0,0,1,2,2v48a14,14,0,0,0,14,14h48a14,14,0,0,0,14-14V115.55A14,14,0,0,0,217.47,105.24ZM210,208a2,2,0,0,1-2,2H160a2,2,0,0,1-2-2V160a14,14,0,0,0-14-14H112a14,14,0,0,0-14,14v48a2,2,0,0,1-2,2H48a2,2,0,0,1-2-2V115.55a2,2,0,0,1,.65-1.48l.09-.08,79.94-75.48a2,2,0,0,1,2.63,0L209.26,114l.08.08a2,2,0,0,1,.66,1.48Z",
					}),
				),
			],
			[
				"regular",
				/* @__PURE__ */ React3.createElement(
					React3.Fragment,
					null,
					/* @__PURE__ */ React3.createElement("path", {
						d: "M218.83,103.77l-80-75.48a1.14,1.14,0,0,1-.11-.11,16,16,0,0,0-21.53,0l-.11.11L37.17,103.77A16,16,0,0,0,32,115.55V208a16,16,0,0,0,16,16H96a16,16,0,0,0,16-16V160h32v48a16,16,0,0,0,16,16h48a16,16,0,0,0,16-16V115.55A16,16,0,0,0,218.83,103.77ZM208,208H160V160a16,16,0,0,0-16-16H112a16,16,0,0,0-16,16v48H48V115.55l.11-.1L128,40l79.9,75.43.11.1Z",
					}),
				),
			],
			[
				"thin",
				/* @__PURE__ */ React3.createElement(
					React3.Fragment,
					null,
					/* @__PURE__ */ React3.createElement("path", {
						d: "M216.13,106.72,136.07,31.13a12,12,0,0,0-16.2.05L39.93,106.67A12,12,0,0,0,36,115.54V208a12,12,0,0,0,12,12H96a12,12,0,0,0,12-12V160a4,4,0,0,1,4-4h32a4,4,0,0,1,4,4v48a12,12,0,0,0,12,12h48a12,12,0,0,0,12-12V115.54A12,12,0,0,0,216.13,106.72ZM212,208a4,4,0,0,1-4,4H160a4,4,0,0,1-4-4V160a12,12,0,0,0-12-12H112a12,12,0,0,0-12,12v48a4,4,0,0,1-4,4H48a4,4,0,0,1-4-4V115.54a4.09,4.09,0,0,1,1.36-3L125.3,37.05a4,4,0,0,1,5.33,0l80.06,75.58a4,4,0,0,1,1.31,3Z",
					}),
				),
			],
		]);
		const House = React3.forwardRef((props, ref) =>
			/* @__PURE__ */ React3.createElement(
				"g",
				{
					ref,
					...props,
				},
				weights.get(props.weight),
			),
		);
		House.displayName = "House";
		Component = House;
	}
	return Component;
};

// /:https://framerusercontent.com/modules/tYScH7LTqUtz5KUaUAYP/CAjjxbTJBxHwH1MagCef/Phosphor.js
var iconKeys = [
	"AddressBook",
	"AirTrafficControl",
	"Airplane",
	"AirplaneInFlight",
	"AirplaneLanding",
	"AirplaneTakeoff",
	"AirplaneTilt",
	"Airplay",
	"Alarm",
	"Alien",
	"AlignBottom",
	"AlignBottomSimple",
	"AlignCenterVertical",
	"AlignLeft",
	"AlignLeftSimple",
	"AlignRight",
	"AlignRightSimple",
	"AlignTop",
	"AlignTopSimple",
	"AmazonLogo",
	"Anchor",
	"AnchorSimple",
	"AndroidLogo",
	"AngularLogo",
	"Aperture",
	"AppStoreLogo",
	"AppWindow",
	"AppleLogo",
	"ApplePodcastsLogo",
	"Archive",
	"ArchiveBox",
	"ArchiveTray",
	"Armchair",
	"ArrowArcLeft",
	"ArrowArcRight",
	"ArrowBendDownLeft",
	"ArrowBendDownRight",
	"ArrowBendLeftDown",
	"ArrowBendLeftUp",
	"ArrowBendRightDown",
	"ArrowBendRightUp",
	"ArrowBendUpLeft",
	"ArrowBendUpRight",
	"ArrowCircleDown",
	"ArrowCircleDownLeft",
	"ArrowCircleDownRight",
	"ArrowCircleLeft",
	"ArrowCircleRight",
	"ArrowCircleUp",
	"ArrowCircleUpLeft",
	"ArrowCircleUpRight",
	"ArrowClockwise",
	"ArrowDown",
	"ArrowDownLeft",
	"ArrowDownRight",
	"ArrowElbowDownLeft",
	"ArrowElbowDownRight",
	"ArrowElbowLeft",
	"ArrowElbowLeftDown",
	"ArrowElbowLeftUp",
	"ArrowElbowRight",
	"ArrowElbowRightDown",
	"ArrowElbowRightUp",
	"ArrowElbowUpLeft",
	"ArrowElbowUpRight",
	"ArrowFatDown",
	"ArrowFatLeft",
	"ArrowFatLineDown",
	"ArrowFatLineLeft",
	"ArrowFatLineRight",
	"ArrowFatLineUp",
	"ArrowFatLinesDown",
	"ArrowFatLinesLeft",
	"ArrowFatLinesRight",
	"ArrowFatLinesUp",
	"ArrowFatRight",
	"ArrowFatUp",
	"ArrowLeft",
	"ArrowLineDown",
	"ArrowLineDownLeft",
	"ArrowLineDownRight",
	"ArrowLineLeft",
	"ArrowLineRight",
	"ArrowLineUp",
	"ArrowLineUpLeft",
	"ArrowLineUpRight",
	"ArrowRight",
	"ArrowSquareDown",
	"ArrowSquareDownLeft",
	"ArrowSquareDownRight",
	"ArrowSquareIn",
	"ArrowSquareLeft",
	"ArrowSquareOut",
	"ArrowSquareRight",
	"ArrowSquareUp",
	"ArrowSquareUpLeft",
	"ArrowSquareUpRight",
	"ArrowUDownLeft",
	"ArrowUDownRight",
	"ArrowULeftDown",
	"ArrowULeftUp",
	"ArrowURightDown",
	"ArrowURightUp",
	"ArrowUUpLeft",
	"ArrowUUpRight",
	"ArrowUp",
	"ArrowUpLeft",
	"ArrowUpRight",
	"ArrowsClockwise",
	"ArrowsDownUp",
	"ArrowsHorizontal",
	"ArrowsIn",
	"ArrowsInCardinal",
	"ArrowsInLineVertical",
	"ArrowsInSimple",
	"ArrowsLeftRight",
	"ArrowsMerge",
	"ArrowsOut",
	"ArrowsOutCardinal",
	"ArrowsOutSimple",
	"ArrowsSplit",
	"ArrowsVertical",
	"Article",
	"ArticleMedium",
	"ArticleNyTimes",
	"Asterisk",
	"AsteriskSimple",
	"At",
	"Atom",
	"Baby",
	"Backpack",
	"Backspace",
	"Bag",
	"BagSimple",
	"Balloon",
	"Bandaids",
	"Bank",
	"Barbell",
	"Barcode",
	"Barricade",
	"Baseball",
	"BaseballCap",
	"Basket",
	"Basketball",
	"Bathtub",
	"BatteryCharging",
	"BatteryEmpty",
	"BatteryFull",
	"BatteryHigh",
	"BatteryLow",
	"BatteryMedium",
	"BatteryPlus",
	"BatteryPlusVertical",
	"BatteryVerticalEmpty",
	"BatteryVerticalFull",
	"BatteryVerticalHigh",
	"BatteryVerticalLow",
	"BatteryWarning",
	"Bed",
	"BeerBottle",
	"BeerStein",
	"BehanceLogo",
	"Bell",
	"BellRinging",
	"BellSimple",
	"BellSimpleRinging",
	"BellSimpleSlash",
	"BellSimpleZ",
	"BellSlash",
	"BellZ",
	"BezierCurve",
	"Bicycle",
	"Binoculars",
	"Bird",
	"Bluetooth",
	"BluetoothConnected",
	"BluetoothSlash",
	"BluetoothX",
	"Boat",
	"Bone",
	"Book",
	"BookBookmark",
	"BookOpen",
	"BookOpenText",
	"Bookmark",
	"BookmarkSimple",
	"Bookmarks",
	"BookmarksSimple",
	"Books",
	"Boot",
	"BoundingBox",
	"BowlFood",
	"BracketsAngle",
	"BracketsCurly",
	"BracketsRound",
	"BracketsSquare",
	"Brain",
	"Brandy",
	"Bridge",
	"Briefcase",
	"BriefcaseMetal",
	"Broadcast",
	"Broom",
	"Browser",
	"Browsers",
	"Bug",
	"BugBeetle",
	"BugDroid",
	"Buildings",
	"Bus",
	"Butterfly",
	"Cactus",
	"Cake",
	"Calculator",
	"Calendar",
	"CalendarBlank",
	"CalendarCheck",
	"CalendarPlus",
	"CalendarX",
	"CallBell",
	"Camera",
	"CameraPlus",
	"CameraRotate",
	"CameraSlash",
	"Campfire",
	"Car",
	"CarProfile",
	"CarSimple",
	"Cardholder",
	"Cards",
	"CaretCircleDoubleUp",
	"CaretCircleDown",
	"CaretCircleLeft",
	"CaretCircleRight",
	"CaretCircleUp",
	"CaretCircleUpDown",
	"CaretDoubleDown",
	"CaretDoubleLeft",
	"CaretDoubleRight",
	"CaretDoubleUp",
	"CaretDown",
	"CaretLeft",
	"CaretRight",
	"CaretUp",
	"CaretUpDown",
	"Carrot",
	"CassetteTape",
	"CastleTurret",
	"Cat",
	"CellSignalFull",
	"CellSignalHigh",
	"CellSignalLow",
	"CellSignalMedium",
	"CellSignalNone",
	"CellSignalSlash",
	"CellSignalX",
	"Certificate",
	"Chair",
	"Chalkboard",
	"ChalkboardSimple",
	"ChalkboardTeacher",
	"Champagne",
	"ChargingStation",
	"ChartBar",
	"ChartBarHorizontal",
	"ChartDonut",
	"ChartLine",
	"ChartLineDown",
	"ChartLineUp",
	"ChartPie",
	"ChartPieSlice",
	"ChartPolar",
	"ChartScatter",
	"Chat",
	"ChatCentered",
	"ChatCenteredDots",
	"ChatCenteredText",
	"ChatCircle",
	"ChatCircleDots",
	"ChatCircleText",
	"ChatDots",
	"ChatTeardrop",
	"ChatTeardropDots",
	"ChatTeardropText",
	"ChatText",
	"Chats",
	"ChatsCircle",
	"ChatsTeardrop",
	"Check",
	"CheckCircle",
	"CheckFat",
	"CheckSquare",
	"CheckSquareOffset",
	"Checks",
	"Church",
	"Circle",
	"CircleDashed",
	"CircleHalf",
	"CircleHalfTilt",
	"CircleNotch",
	"CirclesFour",
	"CirclesThree",
	"CirclesThreePlus",
	"Circuitry",
	"Clipboard",
	"ClipboardText",
	"Clock",
	"ClockAfternoon",
	"ClockClockwise",
	"ClockCounterClockwise",
	"ClockCountdown",
	"ClosedCaptioning",
	"Cloud",
	"CloudArrowDown",
	"CloudArrowUp",
	"CloudCheck",
	"CloudFog",
	"CloudLightning",
	"CloudMoon",
	"CloudRain",
	"CloudSlash",
	"CloudSnow",
	"CloudSun",
	"CloudWarning",
	"CloudX",
	"Club",
	"CoatHanger",
	"CodaLogo",
	"Code",
	"CodeBlock",
	"CodeSimple",
	"CodepenLogo",
	"CodesandboxLogo",
	"Coffee",
	"Coin",
	"CoinVertical",
	"Coins",
	"Columns",
	"Command",
	"Compass",
	"CompassTool",
	"ComputerTower",
	"Confetti",
	"ContactlessPayment",
	"Control",
	"Cookie",
	"CookingPot",
	"Copy",
	"CopySimple",
	"Copyleft",
	"Copyright",
	"CornersIn",
	"CornersOut",
	"Couch",
	"Cpu",
	"CreditCard",
	"Crop",
	"Cross",
	"Crosshair",
	"CrosshairSimple",
	"Crown",
	"CrownSimple",
	"Cube",
	"CubeFocus",
	"CubeTransparent",
	"CurrencyBtc",
	"CurrencyCircleDollar",
	"CurrencyCny",
	"CurrencyDollar",
	"CurrencyDollarSimple",
	"CurrencyEth",
	"CurrencyEur",
	"CurrencyGbp",
	"CurrencyInr",
	"CurrencyJpy",
	"CurrencyKrw",
	"CurrencyKzt",
	"CurrencyNgn",
	"CurrencyRub",
	"Cursor",
	"CursorClick",
	"CursorText",
	"Cylinder",
	"Database",
	"Desktop",
	"DesktopTower",
	"Detective",
	"DevToLogo",
	"DeviceMobile",
	"DeviceMobileCamera",
	"DeviceMobileSpeaker",
	"DeviceTablet",
	"DeviceTabletCamera",
	"DeviceTabletSpeaker",
	"Devices",
	"Diamond",
	"DiamondsFour",
	"DiceFive",
	"DiceFour",
	"DiceOne",
	"DiceSix",
	"DiceThree",
	"DiceTwo",
	"Disc",
	"DiscordLogo",
	"Divide",
	"Dna",
	"Dog",
	"Door",
	"DoorOpen",
	"Dot",
	"DotOutline",
	"DotsNine",
	"DotsSix",
	"DotsSixVertical",
	"DotsThree",
	"DotsThreeCircle",
	"DotsThreeOutline",
	"DotsThreeVertical",
	"Download",
	"DownloadSimple",
	"Dress",
	"DribbbleLogo",
	"Drop",
	"DropHalf",
	"DropHalfBottom",
	"DropboxLogo",
	"Ear",
	"EarSlash",
	"Egg",
	"EggCrack",
	"Eject",
	"EjectSimple",
	"Elevator",
	"Engine",
	"Envelope",
	"EnvelopeOpen",
	"EnvelopeSimple",
	"EnvelopeSimpleOpen",
	"Equalizer",
	"Equals",
	"Eraser",
	"EscalatorDown",
	"EscalatorUp",
	"Exam",
	"Exclude",
	"ExcludeSquare",
	"Export",
	"Eye",
	"EyeClosed",
	"EyeSlash",
	"Eyedropper",
	"EyedropperSample",
	"Eyeglasses",
	"FaceMask",
	"FacebookLogo",
	"Factory",
	"Faders",
	"FadersHorizontal",
	"Fan",
	"FastForward",
	"FastForwardCircle",
	"Feather",
	"FigmaLogo",
	"File",
	"FileArchive",
	"FileArrowDown",
	"FileArrowUp",
	"FileAudio",
	"FileCloud",
	"FileCode",
	"FileCss",
	"FileCsv",
	"FileDashed",
	"FileDoc",
	"FileHtml",
	"FileImage",
	"FileJpg",
	"FileJs",
	"FileJsx",
	"FileLock",
	"FileMagnifyingGlass",
	"FileMinus",
	"FilePdf",
	"FilePlus",
	"FilePng",
	"FilePpt",
	"FileRs",
	"FileSql",
	"FileSvg",
	"FileText",
	"FileTs",
	"FileTsx",
	"FileVideo",
	"FileVue",
	"FileX",
	"FileXls",
	"FileZip",
	"Files",
	"FilmReel",
	"FilmScript",
	"FilmSlate",
	"FilmStrip",
	"Fingerprint",
	"FingerprintSimple",
	"FinnTheHuman",
	"Fire",
	"FireExtinguisher",
	"FireSimple",
	"FirstAid",
	"FirstAidKit",
	"Fish",
	"FishSimple",
	"Flag",
	"FlagBanner",
	"FlagCheckered",
	"FlagPennant",
	"Flame",
	"Flashlight",
	"Flask",
	"FloppyDisk",
	"FloppyDiskBack",
	"FlowArrow",
	"Flower",
	"FlowerLotus",
	"FlowerTulip",
	"FlyingSaucer",
	"Folder",
	"FolderDashed",
	"FolderLock",
	"FolderMinus",
	"FolderNotch",
	"FolderNotchMinus",
	"FolderNotchOpen",
	"FolderNotchPlus",
	"FolderOpen",
	"FolderPlus",
	"FolderSimple",
	"FolderSimpleDashed",
	"FolderSimpleLock",
	"FolderSimpleMinus",
	"FolderSimplePlus",
	"FolderSimpleStar",
	"FolderSimpleUser",
	"FolderStar",
	"FolderUser",
	"Folders",
	"Football",
	"Footprints",
	"ForkKnife",
	"FrameCorners",
	"FramerLogo",
	"Function",
	"Funnel",
	"FunnelSimple",
	"GameController",
	"Garage",
	"GasCan",
	"GasPump",
	"Gauge",
	"Gavel",
	"Gear",
	"GearFine",
	"GearSix",
	"GenderFemale",
	"GenderIntersex",
	"GenderMale",
	"GenderNeuter",
	"GenderNonbinary",
	"GenderTransgender",
	"Ghost",
	"Gif",
	"Gift",
	"GitBranch",
	"GitCommit",
	"GitDiff",
	"GitFork",
	"GitMerge",
	"GitPullRequest",
	"GithubLogo",
	"GitlabLogo",
	"GitlabLogoSimple",
	"Globe",
	"GlobeHemisphereEast",
	"GlobeHemisphereWest",
	"GlobeSimple",
	"GlobeStand",
	"Goggles",
	"GoodreadsLogo",
	"GoogleCardboardLogo",
	"GoogleChromeLogo",
	"GoogleDriveLogo",
	"GoogleLogo",
	"GooglePhotosLogo",
	"GooglePlayLogo",
	"GooglePodcastsLogo",
	"Gradient",
	"GraduationCap",
	"Grains",
	"GrainsSlash",
	"Graph",
	"GridFour",
	"GridNine",
	"Guitar",
	"Hamburger",
	"Hammer",
	"Hand",
	"HandCoins",
	"HandEye",
	"HandFist",
	"HandGrabbing",
	"HandHeart",
	"HandPalm",
	"HandPointing",
	"HandSoap",
	"HandSwipeLeft",
	"HandSwipeRight",
	"HandTap",
	"HandWaving",
	"Handbag",
	"HandbagSimple",
	"HandsClapping",
	"HandsPraying",
	"Handshake",
	"HardDrive",
	"HardDrives",
	"Hash",
	"HashStraight",
	"Headlights",
	"Headphones",
	"Headset",
	"Heart",
	"HeartBreak",
	"HeartHalf",
	"HeartStraight",
	"HeartStraightBreak",
	"Heartbeat",
	"Hexagon",
	"HighHeel",
	"HighlighterCircle",
	"Hoodie",
	"Horse",
	"Hourglass",
	"HourglassHigh",
	"HourglassLow",
	"HourglassMedium",
	"HourglassSimple",
	"HourglassSimpleHigh",
	"HourglassSimpleLow",
	"House",
	"HouseLine",
	"HouseSimple",
	"IceCream",
	"IdentificationBadge",
	"IdentificationCard",
	"Image",
	"ImageSquare",
	"Images",
	"ImagesSquare",
	"Infinity",
	"Info",
	"InstagramLogo",
	"Intersect",
	"IntersectSquare",
	"IntersectThree",
	"Jeep",
	"Kanban",
	"Key",
	"KeyReturn",
	"Keyboard",
	"Keyhole",
	"Knife",
	"Ladder",
	"LadderSimple",
	"Lamp",
	"Laptop",
	"Layout",
	"Leaf",
	"Lifebuoy",
	"Lightbulb",
	"LightbulbFilament",
	"Lighthouse",
	"Lightning",
	"LightningA",
	"LightningSlash",
	"LineSegment",
	"LineSegments",
	"Link",
	"LinkBreak",
	"LinkSimple",
	"LinkSimpleBreak",
	"LinkSimpleHorizontal",
	"LinkedinLogo",
	"LinuxLogo",
	"List",
	"ListBullets",
	"ListChecks",
	"ListDashes",
	"ListMagnifyingGlass",
	"ListNumbers",
	"ListPlus",
	"Lock",
	"LockKey",
	"LockKeyOpen",
	"LockLaminated",
	"LockLaminatedOpen",
	"LockOpen",
	"LockSimple",
	"LockSimpleOpen",
	"Lockers",
	"MagicWand",
	"Magnet",
	"MagnetStraight",
	"MagnifyingGlass",
	"MagnifyingGlassMinus",
	"MagnifyingGlassPlus",
	"MapPin",
	"MapPinLine",
	"MapTrifold",
	"MarkerCircle",
	"Martini",
	"MaskHappy",
	"MaskSad",
	"MathOperations",
	"Medal",
	"MedalMilitary",
	"MediumLogo",
	"Megaphone",
	"MegaphoneSimple",
	"MessengerLogo",
	"MetaLogo",
	"Metronome",
	"Microphone",
	"MicrophoneSlash",
	"MicrophoneStage",
	"MicrosoftExcelLogo",
	"MicrosoftOutlookLogo",
	"MicrosoftTeamsLogo",
	"MicrosoftWordLogo",
	"Minus",
	"MinusCircle",
	"MinusSquare",
	"Money",
	"Monitor",
	"MonitorPlay",
	"Moon",
	"MoonStars",
	"Moped",
	"MopedFront",
	"Mosque",
	"Motorcycle",
	"Mountains",
	"Mouse",
	"MouseSimple",
	"MusicNote",
	"MusicNoteSimple",
	"MusicNotes",
	"MusicNotesPlus",
	"MusicNotesSimple",
	"NavigationArrow",
	"Needle",
	"Newspaper",
	"NewspaperClipping",
	"Notches",
	"Note",
	"NoteBlank",
	"NotePencil",
	"Notebook",
	"Notepad",
	"Notification",
	"NotionLogo",
	"NumberCircleEight",
	"NumberCircleFive",
	"NumberCircleFour",
	"NumberCircleNine",
	"NumberCircleOne",
	"NumberCircleSeven",
	"NumberCircleSix",
	"NumberCircleThree",
	"NumberCircleTwo",
	"NumberCircleZero",
	"NumberEight",
	"NumberFive",
	"NumberFour",
	"NumberNine",
	"NumberOne",
	"NumberSeven",
	"NumberSix",
	"NumberSquareEight",
	"NumberSquareFive",
	"NumberSquareFour",
	"NumberSquareNine",
	"NumberSquareOne",
	"NumberSquareSeven",
	"NumberSquareSix",
	"NumberSquareThree",
	"NumberSquareTwo",
	"NumberSquareZero",
	"NumberThree",
	"NumberTwo",
	"NumberZero",
	"Nut",
	"NyTimesLogo",
	"Octagon",
	"OfficeChair",
	"Option",
	"OrangeSlice",
	"Package",
	"PaintBrush",
	"PaintBrushBroad",
	"PaintBrushHousehold",
	"PaintBucket",
	"PaintRoller",
	"Palette",
	"Pants",
	"PaperPlane",
	"PaperPlaneRight",
	"PaperPlaneTilt",
	"Paperclip",
	"PaperclipHorizontal",
	"Parachute",
	"Paragraph",
	"Parallelogram",
	"Park",
	"Password",
	"Path",
	"PatreonLogo",
	"Pause",
	"PauseCircle",
	"PawPrint",
	"PaypalLogo",
	"Peace",
	"Pen",
	"PenNib",
	"PenNibStraight",
	"Pencil",
	"PencilCircle",
	"PencilLine",
	"PencilSimple",
	"PencilSimpleLine",
	"PencilSimpleSlash",
	"PencilSlash",
	"Pentagram",
	"Pepper",
	"Percent",
	"Person",
	"PersonArmsSpread",
	"PersonSimple",
	"PersonSimpleBike",
	"PersonSimpleRun",
	"PersonSimpleThrow",
	"PersonSimpleWalk",
	"Perspective",
	"Phone",
	"PhoneCall",
	"PhoneDisconnect",
	"PhoneIncoming",
	"PhoneOutgoing",
	"PhonePlus",
	"PhoneSlash",
	"PhoneX",
	"PhosphorLogo",
	"Pi",
	"PianoKeys",
	"PictureInPicture",
	"PiggyBank",
	"Pill",
	"PinterestLogo",
	"Pinwheel",
	"Pizza",
	"Placeholder",
	"Planet",
	"Plant",
	"Play",
	"PlayCircle",
	"PlayPause",
	"Playlist",
	"Plug",
	"PlugCharging",
	"Plugs",
	"PlugsConnected",
	"Plus",
	"PlusCircle",
	"PlusMinus",
	"PlusSquare",
	"PokerChip",
	"PoliceCar",
	"Polygon",
	"Popcorn",
	"PottedPlant",
	"Power",
	"Prescription",
	"Presentation",
	"PresentationChart",
	"Printer",
	"Prohibit",
	"ProhibitInset",
	"ProjectorScreen",
	"ProjectorScreenChart",
	"Pulse",
	"PushPin",
	"PushPinSimple",
	"PushPinSimpleSlash",
	"PushPinSlash",
	"PuzzlePiece",
	"QrCode",
	"Question",
	"Queue",
	"Quotes",
	"Radical",
	"Radio",
	"RadioButton",
	"Radioactive",
	"Rainbow",
	"RainbowCloud",
	"ReadCvLogo",
	"Receipt",
	"ReceiptX",
	"Record",
	"Rectangle",
	"Recycle",
	"RedditLogo",
	"Repeat",
	"RepeatOnce",
	"Rewind",
	"RewindCircle",
	"RoadHorizon",
	"Robot",
	"Rocket",
	"RocketLaunch",
	"Rows",
	"Rss",
	"RssSimple",
	"Rug",
	"Ruler",
	"Scales",
	"Scan",
	"Scissors",
	"Scooter",
	"Screencast",
	"ScribbleLoop",
	"Scroll",
	"Seal",
	"SealCheck",
	"SealQuestion",
	"SealWarning",
	"Selection",
	"SelectionAll",
	"SelectionBackground",
	"SelectionForeground",
	"SelectionInverse",
	"SelectionPlus",
	"SelectionSlash",
	"Shapes",
	"Share",
	"ShareFat",
	"ShareNetwork",
	"Shield",
	"ShieldCheck",
	"ShieldCheckered",
	"ShieldChevron",
	"ShieldPlus",
	"ShieldSlash",
	"ShieldStar",
	"ShieldWarning",
	"ShirtFolded",
	"ShootingStar",
	"ShoppingBag",
	"ShoppingBagOpen",
	"ShoppingCart",
	"ShoppingCartSimple",
	"Shower",
	"Shrimp",
	"Shuffle",
	"ShuffleAngular",
	"ShuffleSimple",
	"Sidebar",
	"SidebarSimple",
	"Sigma",
	"SignIn",
	"SignOut",
	"Signature",
	"Signpost",
	"SimCard",
	"Siren",
	"SketchLogo",
	"SkipBack",
	"SkipBackCircle",
	"SkipForward",
	"SkipForwardCircle",
	"Skull",
	"SlackLogo",
	"Sliders",
	"SlidersHorizontal",
	"Slideshow",
	"Smiley",
	"SmileyAngry",
	"SmileyBlank",
	"SmileyMeh",
	"SmileyNervous",
	"SmileySad",
	"SmileySticker",
	"SmileyWink",
	"SmileyXEyes",
	"SnapchatLogo",
	"Sneaker",
	"SneakerMove",
	"Snowflake",
	"SoccerBall",
	"SortAscending",
	"SortDescending",
	"SoundcloudLogo",
	"Spade",
	"Sparkle",
	"SpeakerHifi",
	"SpeakerHigh",
	"SpeakerLow",
	"SpeakerNone",
	"SpeakerSimpleHigh",
	"SpeakerSimpleLow",
	"SpeakerSimpleNone",
	"SpeakerSimpleSlash",
	"SpeakerSimpleX",
	"SpeakerSlash",
	"SpeakerX",
	"Spinner",
	"SpinnerGap",
	"Spiral",
	"SplitHorizontal",
	"SplitVertical",
	"SpotifyLogo",
	"Square",
	"SquareHalf",
	"SquareHalfBottom",
	"SquareLogo",
	"SquareSplitVertical",
	"SquaresFour",
	"Stack",
	"StackOverflowLogo",
	"StackSimple",
	"Stairs",
	"Stamp",
	"Star",
	"StarAndCrescent",
	"StarFour",
	"StarHalf",
	"StarOfDavid",
	"SteeringWheel",
	"Steps",
	"Stethoscope",
	"Sticker",
	"Stool",
	"Stop",
	"StopCircle",
	"Storefront",
	"Strategy",
	"StripeLogo",
	"Student",
	"Subtitles",
	"Subtract",
	"SubtractSquare",
	"Suitcase",
	"SuitcaseRolling",
	"SuitcaseSimple",
	"Sun",
	"SunDim",
	"SunHorizon",
	"Sunglasses",
	"Swap",
	"Swatches",
	"SwimmingPool",
	"Sword",
	"Synagogue",
	"Syringe",
	"TShirt",
	"Table",
	"Tabs",
	"Tag",
	"TagChevron",
	"TagSimple",
	"Target",
	"Taxi",
	"TelegramLogo",
	"Television",
	"TelevisionSimple",
	"TennisBall",
	"Tent",
	"Terminal",
	"TerminalWindow",
	"TestTube",
	"TextAUnderline",
	"TextAa",
	"TextAlignCenter",
	"TextAlignJustify",
	"TextAlignLeft",
	"TextAlignRight",
	"TextB",
	"TextColumns",
	"TextH",
	"TextHFive",
	"TextHFour",
	"TextHOne",
	"TextHSix",
	"TextHThree",
	"TextHTwo",
	"TextIndent",
	"TextItalic",
	"TextOutdent",
	"TextStrikethrough",
	"TextT",
	"TextUnderline",
	"Textbox",
	"Thermometer",
	"ThermometerCold",
	"ThermometerHot",
	"ThermometerSimple",
	"ThumbsDown",
	"ThumbsUp",
	"Ticket",
	"TidalLogo",
	"TiktokLogo",
	"Timer",
	"Tipi",
	"ToggleLeft",
	"ToggleRight",
	"Toilet",
	"ToiletPaper",
	"Toolbox",
	"Tooth",
	"Tote",
	"ToteSimple",
	"Trademark",
	"TrademarkRegistered",
	"TrafficCone",
	"TrafficSign",
	"TrafficSignal",
	"Train",
	"TrainRegional",
	"TrainSimple",
	"Tram",
	"Translate",
	"Trash",
	"TrashSimple",
	"Tray",
	"Tree",
	"TreeEvergreen",
	"TreePalm",
	"TreeStructure",
	"TrendDown",
	"TrendUp",
	"Triangle",
	"Trophy",
	"Truck",
	"TwitchLogo",
	"TwitterLogo",
	"Umbrella",
	"UmbrellaSimple",
	"Unite",
	"UniteSquare",
	"Upload",
	"UploadSimple",
	"Usb",
	"User",
	"UserCircle",
	"UserCircleGear",
	"UserCircleMinus",
	"UserCirclePlus",
	"UserFocus",
	"UserGear",
	"UserList",
	"UserMinus",
	"UserPlus",
	"UserRectangle",
	"UserSquare",
	"UserSwitch",
	"Users",
	"UsersFour",
	"UsersThree",
	"Van",
	"Vault",
	"Vibrate",
	"Video",
	"VideoCamera",
	"VideoCameraSlash",
	"Vignette",
	"VinylRecord",
	"VirtualReality",
	"Virus",
	"Voicemail",
	"Volleyball",
	"Wall",
	"Wallet",
	"Warehouse",
	"Warning",
	"WarningCircle",
	"WarningDiamond",
	"WarningOctagon",
	"Watch",
	"WaveSawtooth",
	"WaveSine",
	"WaveSquare",
	"WaveTriangle",
	"Waveform",
	"Waves",
	"Webcam",
	"WebcamSlash",
	"WebhooksLogo",
	"WechatLogo",
	"WhatsappLogo",
	"Wheelchair",
	"WheelchairMotion",
	"WifiHigh",
	"WifiLow",
	"WifiMedium",
	"WifiNone",
	"WifiSlash",
	"WifiX",
	"Wind",
	"WindowsLogo",
	"Wine",
	"Wrench",
	"X",
	"XCircle",
	"XSquare",
	"YinYang",
	"YoutubeLogo",
];
var moduleBaseUrl = "https://framer.com/m/phosphor-icons/";
var weightOptions = ["thin", "light", "regular", "bold", "fill", "duotone"];
var lowercaseIconKeyPairs = iconKeys.reduce((res, key) => {
	res[key.toLowerCase()] = key;
	return res;
}, {});
function Icon2(props) {
	const {
		color,
		selectByList,
		iconSearch,
		iconSelection,
		onClick,
		onMouseDown,
		onMouseUp,
		onMouseEnter,
		onMouseLeave,
		weight,
		mirrored,
	} = props;
	const isMounted = useRef(false);
	const iconKey = useIconSelection(
		iconKeys,
		selectByList,
		iconSearch,
		iconSelection,
		lowercaseIconKeyPairs,
	);
	const [SelectedIcon, setSelectedIcon] = useState(
		iconKey === "Home" ? House_default(React) : null,
	);
	async function importModule() {
		try {
			const version = "0.0.53";
			const iconModuleUrl = `${moduleBaseUrl}${iconKey}.js@${version}`;
			const module = await import(
				/* webpackIgnore: true */
				/* @vite-ignore */
				iconModuleUrl
			);
			if (isMounted.current) setSelectedIcon(module.default(React));
		} catch (err) {
			if (isMounted.current) setSelectedIcon(null);
		}
	}
	useEffect(() => {
		isMounted.current = true;
		importModule();
		return () => {
			isMounted.current = false;
		};
	}, [iconKey]);
	const isOnCanvas = RenderTarget.current() === RenderTarget.canvas;
	const emptyState = isOnCanvas ? <NullState /> : null;
	return (
		<motion.div
			style={{
				display: "contents",
			}}
			onClick={onClick}
			onMouseEnter={onMouseEnter}
			onMouseLeave={onMouseLeave}
			onMouseDown={onMouseDown}
			onMouseUp={onMouseUp}
		>
			{SelectedIcon ? (
				<svg
					xmlns={"http://www.w3.org/2000/svg"}
					viewBox={"0 0 256 256"}
					style={{
						userSelect: "none",
						width: "100%",
						height: "100%",
						display: "inline-block",
						fill: color,
						color,
						flexShrink: 0,
						transform: mirrored ? "scale(-1, 1)" : void 0,
					}}
					focusable={"false"}
					color={color}
				>
					<SelectedIcon color={color} weight={weight} />
				</svg>
			) : (
				emptyState
			)}
		</motion.div>
	);
}
Icon2.displayName = "Phosphor";
Icon2.defaultProps = {
	width: 24,
	height: 24,
	iconSelection: "House",
	iconSearch: "House",
	color: "#66F",
	selectByList: true,
	weight: "regular",
	mirrored: false,
};
addPropertyControls(Icon2, {
	selectByList: {
		type: ControlType.Boolean,
		title: "Select",
		enabledTitle: "List",
		disabledTitle: "Search",
		defaultValue: Icon2.defaultProps.selectByList,
	},
	iconSelection: {
		type: ControlType.Enum,
		options: iconKeys,
		defaultValue: Icon2.defaultProps.iconSelection,
		title: "Name",
		hidden: ({ selectByList }) => !selectByList,
		description:
			"Find every icon name on the [Phosphor site](https://phosphoricons.com/)",
	},
	iconSearch: {
		type: ControlType.String,
		title: "Name",
		placeholder: "Menu, Wifi, Box\u2026",
		hidden: ({ selectByList }) => selectByList,
	},
	color: {
		type: ControlType.Color,
		title: "Color",
		defaultValue: Icon2.defaultProps.color,
	},
	weight: {
		type: ControlType.Enum,
		title: "Weight",
		optionTitles: weightOptions.map(
			(piece) => piece.charAt(0).toUpperCase() + piece.slice(1),
		),
		options: weightOptions,
		defaultValue: Icon2.defaultProps.weight,
	},
	mirrored: {
		type: ControlType.Boolean,
		enabledTitle: "Yes",
		disabledTitle: "No",
		defaultValue: Icon2.defaultProps.mirrored,
	},
	...defaultEvents,
});

// /:https://framerusercontent.com/modules/jrem5R0H3AHOGveZnbWb/7nqn8ODInZcDBaJcezxk/aq1Wy0p__.js
var PhosphorFonts = getFonts(Icon);
var Phosphor1Fonts = getFonts(Icon2);
var MotionDivWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(motion2.div),
);
var enabledGestures = {
	UNYnnQPnT: {
		hover: true,
	},
};
var cycleOrder = ["UNYnnQPnT", "ycj4Jdg5w", "dzrF5wp2J"];
var serializationHash = "framer-dE5v8";
var variantClassNames = {
	dzrF5wp2J: "framer-v-1cp9c3l",
	UNYnnQPnT: "framer-v-vvi31g",
	ycj4Jdg5w: "framer-v-frs7wj",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 4,
	duration: 1,
	type: "spring",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition1,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 0.5,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transition2 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion2.create(React2.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "UNYnnQPnT",
	"Variant 2": "ycj4Jdg5w",
	"Variant 3": "dzrF5wp2J",
};
var getProps = ({ height, hover, id, width, ...props }) => {
	return {
		...props,
		Qlq6hycMg: hover ?? props.Qlq6hycMg,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "UNYnnQPnT",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, Qlq6hycMg, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "UNYnnQPnT",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1wsls4 = activeVariantCallback(async (...args) => {
		setVariant("ycj4Jdg5w");
	});
	const onMouseEnter1cthpjs = activeVariantCallback(async (...args) => {
		if (Qlq6hycMg) {
			const res = await Qlq6hycMg(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [];
	const isDisplayed = () => {
		if (baseVariant === "ycj4Jdg5w") return false;
		return true;
	};
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				{isDisplayed() && (
					<Transition value={transition2}>
						<MotionDivWithFXWithOptimizedAppearEffect
							{...restProps}
							{...gestureHandlers}
							__framer__presenceAnimate={animation}
							__framer__presenceInitial={animation1}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							className={cx(
								scopingClassNames,
								"framer-vvi31g",
								className,
								classNames,
							)}
							data-framer-appear-id={"vvi31g"}
							data-framer-name={"Variant 1"}
							layoutDependency={layoutDependency}
							layoutId={"UNYnnQPnT"}
							optimized={true}
							ref={refBinding}
							style={{
								backgroundColor: "rgb(255, 255, 255)",
								borderBottomLeftRadius: 20,
								borderBottomRightRadius: 20,
								borderTopLeftRadius: 20,
								borderTopRightRadius: 20,
								boxShadow:
									"-0.4777151241141837px 0.39809593676181976px 3.1092286610737587px 0px rgba(0, 0, 0, 0.02), -1.4487036858627107px 1.207253071552259px 9.428947910828343px 0px rgba(0, 0, 0, 0.05), -3.829592112890677px 3.1913267607422307px 24.92505879879924px 0px rgba(0, 0, 0, 0.13), -12px 10px 78.10249675906654px 0px rgba(0, 0, 0, 0.4)",
								...style,
							}}
							{...addPropertyOverrides(
								{
									"UNYnnQPnT-hover": {
										"data-framer-name": void 0,
									},
									dzrF5wp2J: {
										"data-framer-name": "Variant 3",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion2.div
								className={"framer-mtzrfp"}
								data-highlight={true}
								layoutDependency={layoutDependency}
								layoutId={"pzYcMJZwT"}
								onTap={onTap1wsls4}
							>
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-171i4kf-container"}
										isAuthoredByUser={true}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"xp8e04nut-container"}
										nodeId={"xp8e04nut"}
										rendersWithMotion={true}
										scopeId={"aq1Wy0p__"}
									>
										<Icon
											color={
												"var(--token-7cfab920-9d1e-4f38-8c7a-a58d533b8508, rgb(255, 255, 255))"
											}
											height={"100%"}
											iconSearch={"House"}
											iconSelection={"XCircle"}
											id={"xp8e04nut"}
											layoutId={"xp8e04nut"}
											mirrored={false}
											selectByList={true}
											style={{
												height: "100%",
												width: "100%",
											}}
											weight={"regular"}
											width={"100%"}
										/>
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion2.div>
							<Link
								href={"https://framer.link/LvEWI8I"}
								motionChild={true}
								nodeId={"IPv_Cr0Pe"}
								openInNewTab={true}
								scopeId={"aq1Wy0p__"}
							>
								<motion2.a
									className={"framer-ijf8m2 framer-1kiwbwi"}
									layoutDependency={layoutDependency}
									layoutId={"IPv_Cr0Pe"}
								>
									<Image
										background={{
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) +
													(6 +
														((componentViewport?.height || 150) - 12 - 152.5) /
															2) +
													7.25,
											),
											pixelHeight: 1440,
											pixelWidth: 1200,
											src: "https://framerusercontent.com/images/Moi0yCw8SYlze07K0EvYAt3iKq8.png?scale-down-to=1024&width=1200&height=1440",
										}}
										className={"framer-1tjoscb"}
										layoutDependency={layoutDependency}
										layoutId={"Cae9IwSQ8"}
										style={{
											borderBottomLeftRadius: 20,
											borderBottomRightRadius: 20,
											borderTopLeftRadius: 20,
											borderTopRightRadius: 20,
										}}
										{...addPropertyOverrides(
											{
												"UNYnnQPnT-hover": {
													background: {
														alt: "",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																(6 +
																	((componentViewport?.height || 150) -
																		12 -
																		152.5) /
																		2) +
																7.25,
														),
														pixelHeight: 1709,
														pixelWidth: 2519,
														sizes: "138px",
														src: "https://framerusercontent.com/images/BhAHPGxS3hSP4q7kQxwd05EUIc.png?width=2519&height=1709",
														srcSet:
															"https://framerusercontent.com/images/BhAHPGxS3hSP4q7kQxwd05EUIc.png?scale-down-to=512&width=2519&height=1709 512w,https://framerusercontent.com/images/BhAHPGxS3hSP4q7kQxwd05EUIc.png?scale-down-to=1024&width=2519&height=1709 1024w,https://framerusercontent.com/images/BhAHPGxS3hSP4q7kQxwd05EUIc.png?scale-down-to=2048&width=2519&height=1709 2048w,https://framerusercontent.com/images/BhAHPGxS3hSP4q7kQxwd05EUIc.png?width=2519&height=1709 2519w",
													},
												},
												dzrF5wp2J: {
													background: {
														alt: "",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																(6 +
																	((componentViewport?.height || 124) -
																		12 -
																		152.5) /
																		2) +
																7.25,
														),
														pixelHeight: 1440,
														pixelWidth: 1200,
														src: "https://framerusercontent.com/images/Moi0yCw8SYlze07K0EvYAt3iKq8.png?scale-down-to=1024&width=1200&height=1440",
													},
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
									<motion2.div
										className={"framer-1i3enrb"}
										layoutDependency={layoutDependency}
										layoutId={"yAmIIKsre"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-4tuktz"}
											fonts={["FS;Satoshi-bold"]}
											layoutDependency={layoutDependency}
											layoutId={"T0mhlnpA_"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-620fac81-7c2e-4342-b93a-72603d1fc89e, rgb(13, 13, 13))",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React2.Fragment>
												<motion2.p
													style={{
														"--font-selector": "RlM7U2F0b3NoaS1ib2xk",
														"--framer-font-family":
															'"Satoshi", "Satoshi Placeholder", sans-serif',
														"--framer-font-size": "18px",
														"--framer-font-weight": "700",
														"--framer-letter-spacing": "-0.02em",
														"--framer-text-alignment": "left",
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-620fac81-7c2e-4342-b93a-72603d1fc89e, rgb(13, 13, 13)))",
													}}
												>
													{"Check out my photography template"}
												</motion2.p>
											</React2.Fragment>
										</RichText>
										<motion2.div
											className={"framer-j7akxu"}
											data-framer-name={"Text Button"}
											data-highlight={true}
											layoutDependency={layoutDependency}
											layoutId={"KyOi6PzzD"}
											onMouseEnter={onMouseEnter1cthpjs}
										>
											<motion2.div
												className={"framer-e2sp6d"}
												layoutDependency={layoutDependency}
												layoutId={"J7m3nWHlf"}
											>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-40pims"}
													fonts={["GF;Inter-700"]}
													layoutDependency={layoutDependency}
													layoutId={"ZRTs80VKs"}
													style={{
														"--extracted-r6o4lv":
															"var(--token-9e4d3cd9-c6a1-4d3f-93c0-3bd54ca04155, rgb(5, 5, 5))",
														"--framer-link-text-color": "rgb(0, 153, 255)",
														"--framer-link-text-decoration": "underline",
													}}
													variants={{
														"UNYnnQPnT-hover": {
															"--extracted-r6o4lv":
																"var(--token-2f560859-5998-4075-847c-9f666c5cfc0b, rgb(10, 10, 10))",
														},
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
													{...addPropertyOverrides(
														{
															"UNYnnQPnT-hover": {
																children: (
																	<React2.Fragment>
																		<motion2.p
																			style={{
																				"--font-selector": "R0Y7SW50ZXItNzAw",
																				"--framer-font-size": "13px",
																				"--framer-font-weight": "700",
																				"--framer-letter-spacing": "-0.05em",
																				"--framer-line-height": "150%",
																				"--framer-text-alignment": "left",
																				"--framer-text-color":
																					"var(--extracted-r6o4lv, var(--token-2f560859-5998-4075-847c-9f666c5cfc0b, rgb(10, 10, 10)))",
																			}}
																		>
																			{"REMIX NOW"}
																		</motion2.p>
																	</React2.Fragment>
																),
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<React2.Fragment>
														<motion2.p
															style={{
																"--font-selector": "R0Y7SW50ZXItNzAw",
																"--framer-font-size": "13px",
																"--framer-font-weight": "700",
																"--framer-letter-spacing": "-0.05em",
																"--framer-line-height": "150%",
																"--framer-text-alignment": "left",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-9e4d3cd9-c6a1-4d3f-93c0-3bd54ca04155, rgb(5, 5, 5)))",
															}}
														>
															{"REMIX NOW"}
														</motion2.p>
													</React2.Fragment>
												</RichText>
												<ComponentViewportProvider>
													<SmartComponentScopedContainer
														className={"framer-1qomvjh-container"}
														isModuleExternal={true}
														layoutDependency={layoutDependency}
														layoutId={"omIkZy2vA-container"}
														nodeId={"omIkZy2vA"}
														rendersWithMotion={true}
														scopeId={"aq1Wy0p__"}
														style={{
															rotate: -90,
														}}
													>
														<Icon2
															color={
																"var(--token-6486a9ac-e9e8-4ced-becb-afb4c654ba35, rgb(13, 13, 13))"
															}
															height={"100%"}
															iconSearch={"House"}
															iconSelection={"ArrowDown"}
															id={"omIkZy2vA"}
															layoutId={"omIkZy2vA"}
															mirrored={false}
															selectByList={true}
															style={{
																height: "100%",
																width: "100%",
															}}
															weight={"regular"}
															width={"100%"}
															{...addPropertyOverrides(
																{
																	"UNYnnQPnT-hover": {
																		weight: "fill",
																	},
																},
																baseVariant,
																gestureVariant,
															)}
														/>
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											</motion2.div>
										</motion2.div>
									</motion2.div>
								</motion2.a>
							</Link>
						</MotionDivWithFXWithOptimizedAppearEffect>
					</Transition>
				)}
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-dE5v8.framer-1kiwbwi, .framer-dE5v8 .framer-1kiwbwi { display: block; }",
	".framer-dE5v8.framer-vvi31g { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 15px; height: min-content; justify-content: center; overflow: visible; padding: 6px; position: relative; width: 336px; }",
	".framer-dE5v8 .framer-mtzrfp { cursor: pointer; flex: none; height: 42px; overflow: hidden; position: absolute; right: 0px; top: -47px; width: 42px; }",
	".framer-dE5v8 .framer-171i4kf-container { bottom: 0px; flex: none; left: 0px; position: absolute; right: 0px; top: 0px; z-index: 1; }",
	".framer-dE5v8 .framer-ijf8m2 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: 1px; }",
	".framer-dE5v8 .framer-1tjoscb { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 138px); overflow: hidden; position: relative; width: 138px; will-change: var(--framer-will-change-override, transform); }",
	".framer-dE5v8 .framer-1i3enrb { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 17px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-dE5v8 .framer-4tuktz { --framer-text-wrap: balance; flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-dE5v8 .framer-j7akxu { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 4px 0px 4px 0px; position: relative; width: min-content; }",
	".framer-dE5v8 .framer-e2sp6d { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-dE5v8 .framer-40pims { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
	".framer-dE5v8 .framer-1qomvjh-container { flex: none; height: 19px; position: relative; width: 18px; }",
	".framer-dE5v8.framer-v-1cp9c3l.framer-vvi31g { cursor: unset; height: 124px; width: 323px; }",
	".framer-dE5v8.framer-v-vvi31g.hover .framer-e2sp6d { gap: 13px; }",
];
var Frameraq1Wy0p__ = withCSS(Component2, css, "framer-dE5v8");
var stdin_default = Frameraq1Wy0p__;
Frameraq1Wy0p__.displayName = "Toast";
Frameraq1Wy0p__.defaultProps = {
	height: 150,
	width: 336,
};
addPropertyControls2(Frameraq1Wy0p__, {
	variant: {
		options: ["UNYnnQPnT", "ycj4Jdg5w", "dzrF5wp2J"],
		optionTitles: ["Variant 1", "Variant 2", "Variant 3"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	Qlq6hycMg: {
		title: "Hover",
		type: ControlType2.EventHandler,
	},
});
addFonts(
	Frameraq1Wy0p__,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Satoshi",
					source: "fontshare",
					style: "normal",
					uiFamilyName: "Satoshi",
					url: "https://framerusercontent.com/third-party-assets/fontshare/wf/LAFFD4SDUCDVQEXFPDC7C53EQ4ZELWQI/PXCT3G6LO6ICM5I3NTYENYPWJAECAWDD/GHM6WVH6MILNYOOCXHXB5GTSGNTMGXZR.woff2",
					weight: "700",
				},
				{
					cssFamilyName: "Inter",
					source: "google",
					style: "normal",
					uiFamilyName: "Inter",
					url: "https://fonts.gstatic.com/s/inter/v20/UcCO3FwrK3iLTeHuS_nVMrMxCp50SjIw2boKoduKmMEVuFuYMZ1rib2Bg-4.woff2",
					weight: "700",
				},
			],
		},
		...PhosphorFonts,
		...Phosphor1Fonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:toast
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8a429189ff65f2fafed7ae45547e59ca6084759351dbe5c21bdecf003cf56825"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ToastFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8a429189ff65f2fafed7ae45547e59ca6084759351dbe5c21bdecf003cf56825"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var toast_default = ComponentWithRoot;
export { toast_default as default };
