// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 8a429189ff65f2fa "Shareye Films", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Phone' // Variant
 * serial?: string // Serial
 * title?: string // Title
 * text?: string // Text
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-PPTQYH4F.js";
import { className, css, fonts } from "./chunks/chunk-J47HK3IR.js";
import { routes } from "./chunks/chunk-W2AWTVWO.js";

// virtual:values
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/xML3MA4IsaNYyQXgzixb/fTgsLRHlISGE2vlEenNI/pQiCaFaBC.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["yGQiVvRme", "k1rtLE5OP"];
var serializationHash = "framer-6mJjb";
var variantClassNames = {
	k1rtLE5OP: "framer-v-1d9pij5",
	yGQiVvRme: "framer-v-5ni71h",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateY(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Default: "yGQiVvRme",
	Phone: "k1rtLE5OP",
};
var getProps = ({ height, id, serial, text, title, width, ...props }) => {
	var _ref, _ref1, _ref2, _humanReadableVariantMap_props_variant, _ref3;
	return {
		...props,
		dLsraBPWZ:
			(_ref = text !== null && text !== void 0 ? text : props.dLsraBPWZ) !==
				null && _ref !== void 0
				? _ref
				: "We believe in the power of imagination and creative thinking. We strive to infuse innovation and originality into everything we do, producing unique and captivating video content.",
		ihc4Hrl2N:
			(_ref1 = title !== null && title !== void 0 ? title : props.ihc4Hrl2N) !==
				null && _ref1 !== void 0
				? _ref1
				: "Creativity",
		QP7ergSwF:
			(_ref2 =
				serial !== null && serial !== void 0 ? serial : props.QP7ergSwF) !==
				null && _ref2 !== void 0
				? _ref2
				: "01",
		variant:
			(_ref3 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref3 !== void 0
				? _ref3
				: "yGQiVvRme",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		QP7ergSwF,
		ihc4Hrl2N,
		dLsraBPWZ,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "yGQiVvRme",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className2, className];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-5ni71h",
							className3,
							classNames,
						)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"yGQiVvRme"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								k1rtLE5OP: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-239g84"}
							layoutDependency={layoutDependency}
							layoutId={"zIWAu42Ik"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-170321i"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"aQ_eS5mXa"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-d9d01f21-7a47-443c-a8bc-56cdb453de6f, rgba(255, 255, 255, 0.8))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={ihc4Hrl2N}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-fprirg"}
										data-styles-preset={"OjogGp4K9"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-d9d01f21-7a47-443c-a8bc-56cdb453de6f, rgba(255, 255, 255, 0.8)))",
										}}
									>
										{"Creativity"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-107c9hc"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"o8tBvLZz9"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-d9d01f21-7a47-443c-a8bc-56cdb453de6f, rgba(255, 255, 255, 0.8))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={dLsraBPWZ}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-smtg16"}
										data-styles-preset={"DuMLJ2VUN"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-d9d01f21-7a47-443c-a8bc-56cdb453de6f, rgba(255, 255, 255, 0.8)))",
										}}
									>
										{
											"We believe in the power of imagination and creative thinking. We strive to infuse innovation and originality into everything we do, producing unique and captivating video content."
										}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-ergiu7"}
							fonts={["GF;Syne-700"]}
							layoutDependency={layoutDependency}
							layoutId={"YwMxj41TZ"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-8c47652b-dea5-4767-a9f2-5d952dcce49a, rgba(255, 255, 255, 0.3))",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
								opacity: 0.37,
							}}
							text={QP7ergSwF}
							transformTemplate={transformTemplate1}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--font-selector": "R0Y7U3luZS03MDA=",
										"--framer-font-family":
											'"Syne", "Syne Placeholder", sans-serif',
										"--framer-font-size": "190px",
										"--framer-font-weight": "700",
										"--framer-letter-spacing": "-0.05em",
										"--framer-line-height": "0.4em",
										"--framer-text-alignment": "left",
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-8c47652b-dea5-4767-a9f2-5d952dcce49a, rgba(255, 255, 255, 0.3)))",
									}}
								>
									{"01"}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-6mJjb.framer-1hgip0h, .framer-6mJjb .framer-1hgip0h { display: block; }",
	".framer-6mJjb.framer-5ni71h { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1100px; }",
	".framer-6mJjb .framer-239g84 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 13px; height: min-content; justify-content: center; overflow: visible; padding: 50px 50px 30px 110px; position: relative; width: 1px; z-index: 2; }",
	".framer-6mJjb .framer-170321i, .framer-6mJjb .framer-107c9hc { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-6mJjb .framer-ergiu7 { flex: none; height: 100%; left: 0px; position: absolute; top: 50%; white-space: pre; width: auto; z-index: 1; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-6mJjb.framer-5ni71h, .framer-6mJjb .framer-239g84 { gap: 0px; } .framer-6mJjb.framer-5ni71h > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-6mJjb.framer-5ni71h > :first-child { margin-left: 0px; } .framer-6mJjb.framer-5ni71h > :last-child { margin-right: 0px; } .framer-6mJjb .framer-239g84 > * { margin: 0px; margin-bottom: calc(13px / 2); margin-top: calc(13px / 2); } .framer-6mJjb .framer-239g84 > :first-child { margin-top: 0px; } .framer-6mJjb .framer-239g84 > :last-child { margin-bottom: 0px; } }",
	".framer-6mJjb.framer-v-1d9pij5 .framer-239g84 { padding: 50px 20px 30px 30px; }",
	...css2,
	...css,
];
var FramerpQiCaFaBC = withCSS(Component, css3, "framer-6mJjb");
var stdin_default = FramerpQiCaFaBC;
FramerpQiCaFaBC.displayName = "Values";
FramerpQiCaFaBC.defaultProps = {
	height: 197,
	width: 1100,
};
addPropertyControls(FramerpQiCaFaBC, {
	variant: {
		options: ["yGQiVvRme", "k1rtLE5OP"],
		optionTitles: ["Default", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
	QP7ergSwF: {
		defaultValue: "01",
		displayTextArea: false,
		title: "Serial",
		type: ControlType.String,
	},
	ihc4Hrl2N: {
		defaultValue: "Creativity",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	dLsraBPWZ: {
		defaultValue:
			"We believe in the power of imagination and creative thinking. We strive to infuse innovation and originality into everything we do, producing unique and captivating video content.",
		displayTextArea: true,
		title: "Text",
		type: ControlType.String,
	},
});
addFonts(
	FramerpQiCaFaBC,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					family: "Syne",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/syne/v22/8vIS7w4qzmVxsWxjBZRjr0FKM_3fvj6hR47NCV5Z.woff2",
					weight: "700",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:values
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "k1rtLE5OP",
	xl: "yGQiVvRme",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8a429189ff65f2fafed7ae45547e59ca6084759351dbe5c21bdecf003cf56825"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ValuesFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"8a429189ff65f2fafed7ae45547e59ca6084759351dbe5c21bdecf003cf56825"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var values_default = ComponentWithRoot;
export { values_default as default };
